### ISSUE TITLE
安装问题

### ISSUE THREAD

**Issue by benqy** [NetEase/pomelo#1]
windows和ubuntu用npm都没安装成功过....是不是少装了什么东西

**Comment by uSmile-Y** [comment]
> heapdump@0.2.9 install /root/chatofpomelo-websocket-master/game-server/node_modules/heapdump
> node-gyp rebuild

install                   ▄ ╢███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████
gyp info it worked if it ends with ok
gyp info using node-gyp@3.2.1
gyp info using node@5.4.1 | linux | x64
gyp info spawn /usr/local/bin/python2
gyp info spawn args [ '/usr/local/node/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/root/chatofpomelo-websocket-master/game-server/node_modules/heapdump/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/local/node/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/root/.node-gyp/5.4.1/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/root/.node-gyp/5.4.1',
gyp info spawn args   '-Dnode_gyp_dir=/usr/local/node/lib/node_modules/npm/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=node.lib',
gyp info spawn args   '-Dmodule_root_dir=/root/chatofpomelo-websocket-master/game-server/node_modules/heapdump',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
make: Entering directory `/root/chatofpomelo-websocket-master/game-server/node_modules/heapdump/build'
  CXX(target) Release/obj.target/heapdump/src/heapdump.o
../src/heapdump.cc: In function ‘bool heapdump::WriteSnapshotHelper(v8::Isolate*, const char*)’:
../src/heapdump.cc:158:74: error: no matching function for call to ‘v8::HeapProfiler::TakeHeapSnapshot(v8::Local<v8::String>)’
       isolate->GetHeapProfiler()->TakeHeapSnapshot(String::Empty(isolate)));
                                                                          ^
../src/heapdump.cc:36:25: note: in definition of macro ‘COMPAT’
 # define COMPAT(_, exp) exp
                         ^
../src/heapdump.cc:158:74: note: candidate is:
       isolate->GetHeapProfiler()->TakeHeapSnapshot(String::Empty(isolate)));
                                                                          ^
../src/heapdump.cc:36:25: note: in definition of macro ‘COMPAT’
 # define COMPAT(_, exp) exp
                         ^
In file included from ../src/heapdump.cc:23:0:
/root/.node-gyp/5.4.1/include/node/v8-profiler.h:486:23: note: const v8::HeapSnapshot* v8::HeapProfiler::TakeHeapSnapshot(v8::ActivityControl*, v8::HeapProfiler::ObjectNameResolver*)
   const HeapSnapshot* TakeHeapSnapshot(
                       ^
/root/.node-gyp/5.4.1/include/node/v8-profiler.h:486:23: note:   no known conversion for argument 1 from ‘v8::Local<v8::String>’ to ‘v8::ActivityControl*’
make: *** [Release/obj.target/heapdump/src/heapdump.o] Error 1
make: Leaving directory `/root/chatofpomelo-websocket-master/game-server/node_modules/heapdump/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/node/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 3.10.0-327.4.4.el7.x86_64
gyp ERR! command "/usr/local/node/bin/node" "/usr/local/node/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /root/chatofpomelo-websocket-master/game-server/node_modules/heapdump
gyp ERR! node -v v5.4.1
gyp ERR! node-gyp -v v3.2.1
gyp ERR! not ok 

install                   ▄ ╢███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████
npm info lifecycle heapdump@0.2.9~install: Failed to exec install script
install                   ▀ ╢███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████install → rollbackFailedO ▄ ╢███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████install → rollbackFailedO ▌ ╢███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████
runTopLevelLifecycles     ▄ ╢███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████
chatofpomelo-websocket@0.0.1 /root/chatofpomelo-websocket-master/game-server
└── (empty)

runTopLevelLifecycles     ▄ ╢███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████
npm WARN chatofpomelo-websocket@0.0.1 No description
runTopLevelLifecycles     ▌ ╢███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████
npm WARN chatofpomelo-websocket@0.0.1 No repository field.
runTopLevelLifecycles     ▀ ╢███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████
npm WARN chatofpomelo-websocket@0.0.1 No license field.
runTopLevelLifecycles     ▐ ╢████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████
npm ERR! Linux 3.10.0-327.4.4.el7.x86_64
npm ERR! argv "/usr/local/node/bin/node" "/usr/local/node/bin/npm" "install" "-d"
npm ERR! node v5.4.1
npm ERR! npm  v3.5.3
npm ERR! code ELIFECYCLE

npm ERR! heapdump@0.2.9 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the heapdump@0.2.9 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the heapdump package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs heapdump
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls heapdump
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /root/chatofpomelo-websocket-master/game-server/npm-debug.log
npm ERR! code 1

总是遇到这些错误，我的chatofpomelo-websocket-master 例子程序就没有运行成功过，麻烦大大帮我看看啊，都弄了好多天了，资料太少了

**Comment by gocpplua** [comment]
这问题还存在的
