### ISSUE TITLE
 如何在多个服务器之间共享变量？

### ISSUE THREAD

**Issue by halsn** [NetEase/pomelo#1028]
例如我有两台chat-server，前端用户连过来后会随机分配一个chat-server进行处理，但是不同的chat-server处理逻辑需要用到同一个变量，请问pomelo有没有对应的API可以设置全局共享变量？

**Comment by whtiehack** [comment]
可以加到 session上。或者用redis

**Comment by yangfch3** [comment]
进程间共享数据的话用 redis 或者 mc 做中介，但要注意数据一致性（锁）
