### ISSUE TITLE
负载能力问题

### ISSUE THREAD

**Issue by jesonxie** [NetEase/pomelo#1029]
目前在压测过程中，发现：
1、单个 connector 在承载2400个客户端连接（每个客户端 1次/s）时，客户端延迟很高，接收socket响应花费时间很长。分析 pomelo-robot 测试结果，发现 Avg在 1-2s，Max在 30-480s。
2、单个 connector 在承载400个客户端连接（每个客户端 10次/s）时，跟上一个测试结果雷同。

请问大佬们，单个 connector 的负载能力一般是多少？

**Comment by whtiehack** [comment]
https://github.com/NetEase/pomelo/wiki/Home-in-Chinese#%E6%80%A7%E8%83%BD%E6%B5%8B%E8%AF%95%E6%8A%A5%E5%91%8A

**Comment by jesonxie** [comment]
“pomelo rpc性能测试报告” 么？ 多谢指点
