### ISSUE TITLE
[北京海淀] 搜狐招聘 游戏服务器端工程师 (17K~35K) 2名 

### ISSUE THREAD

**Issue by lwcbest** [NetEase/pomelo#1073]
##招聘类型：社招 工作地点：北京海淀区科学院南路2号院3号楼搜狐媒体大厦 工资范围：17K~35K 
##岗位概况： 搜狐视频-互娱创新事业部，游戏开发(目前主要是棋牌类、小游戏)，上升期，机会多。 
##岗位要求：
 1、负责基于Node.js的游戏服务端程序设计和开发、项目维护；
 2、分析项目需求，给出良好的解决方案并予以实施；
 3、进行系统功能模块的开发与优化； 
4、完成其他服务器端相关工作；
 5、工作稳定性较高，不曾频繁更换工作；
##希望寻找这样的你: 
1、热爱游戏行业，2年以上游戏服务端开发经验。 
2、精通node.js/JS网络编程，熟悉高并发、高吞吐量、分布式系统开发； 
3、熟悉pomelo的开发框架，了解pomelo内部的实现原理； 
4、熟悉tcp/ip, tcp, https, websocket, mqtt网络协议; 
5、熟悉Linux系统的常用命令与软件； 
6、熟悉Mysql，redis等常用数据库； 
7、具备良好的分析解决问题能力和Bug解决能力，能独立承担开发工作; 
8、良好的团队协作精神，认真负责，有良好的抗压能力； 
9、本科以上学历，计算机相关专业; 
##福利： 可提供有竞争力的薪酬 弹性工作时间，不强制加班，结果导向，带薪15天年假 饭补、加班餐、免费饮料咖啡、节假日福利等应有尽有，各种兴趣群及活动俱乐部 
##联系方式: 接收简历邮箱：chengxinsun@sohu-inc.com 标题请注明：xxx应聘游戏服务器端高级工程师【来源pomelo】
 坐标：北京海淀区科学院南路2号院3号楼搜狐媒体大厦1层 1.地铁路线： 地铁10号线知春里A出口； 地铁4号线中关村B出口;　
 2.公交车路线： 中关村二桥南(途径 384,579); 中关村一街站(途径 740外，运通113，47，641，特9内，特9外

**Comment by wildwolf113** [comment]
哎呀呀，文凭不够。

**Comment by whtiehack** [comment]
哎呀呀，其它都够，就文凭不够。

**Comment by lwcbest** [comment]
我不管搜狐的团队了，我在京东入职了

**Comment by lwcbest** [comment]
> 
> 
> 哎呀呀，文凭不够。
我在京东招nodejs，可以投简历来
https://cnodejs.org/topic/5b8ca27782f0728f354d736a

**Comment by lwcbest** [comment]
> 
> 
> 哎呀呀，其它都够，就文凭不够。

我在京东招nodejs，可以投简历来
https://cnodejs.org/topic/5b8ca27782f0728f354d736a
