### ISSUE TITLE
pomelo-admin-web跨域访问问题

### ISSUE THREAD

**Issue by cheungfai** [NetEase/pomelo#1094]
使用admin-cli可以正常查询服务器的状态，但是使用浏览器访问pomelo-admin-web时，浏览器的控制台会报错，如下所示：
  已拦截跨源请求：同源策略禁止读取位于 http://*****:3005/socket.io/1/?t=1533782906994 的远程资源。（原因：CORS 请求未能成功）。

game-server不是express服务器，怎么解决跨域的问题？

**Comment by whtiehack** [comment]
https://github.com/whtiehack/pomelo-admin-web-new   这是我改过的，可以参考下。

**Comment by cheungfai** [comment]
@whtiehack 问题解决了，谢谢兄弟，好人一生平安
