### ISSUE TITLE
PomeloRobot有在用的吗？本地client连不上master怎么解决？跟socket.io版本有关系吗？

### ISSUE THREAD

**Issue by liuguolai** [NetEase/pomelo#1098]

**Comment by whtiehack** [comment]
pomelorobot  不需要连master啊。只是模拟客户端的。 你说的master是 robot的master吧。 是通过robot启动参数来决定的。

**Comment by liuguolai** [comment]
说的是robot的master。因为库里面用的socket.io版本太老了，我用的是最新的socket.io，把agent连接的代码改了就好了
