### ISSUE TITLE
官网已经打不开了吗？还有其他地方查看api吗？

### ISSUE THREAD

**Issue by chenandjian** [NetEase/pomelo#1134]
http://pomelo.netease.com/api.html 突然发现网站打不开了

**Comment by le888** [comment]
同问

**Comment by le888** [comment]
希望能把api搬到github上面来

**Comment by markgege** [comment]
是啊，github上项目都还在，咋就把api下线了呢？

**Comment by le888** [comment]
@fantasyni  能把api般大github上面吗？

**Comment by chenmins** [comment]
https://web.archive.org/web/20180614214750/http://pomelo.netease.com/api.html

**Comment by chenmins** [comment]
我也是 在互联网档案馆 看到的

**Comment by chenandjian** [comment]
> 我也是 在互联网档案馆 看到的



> https://web.archive.org/web/20180614214750/http://pomelo.netease.com/api.html

**Comment by chenandjian** [comment]
> https://web.archive.org/web/20180614214750/http://pomelo.netease.com/api.html

这个网站也打不开了吗？

**Comment by le888** [comment]
https://github.com/NetEase/pomelo/wiki/pomelo-API 我已经把他搬过来了

**Comment by honghui** [comment]
是不是意味着 pomelo 要挂了
