### ISSUE TITLE
mqtt rpc client checkKeepAlive error timeout for 120000

### ISSUE THREAD

**Issue by lh348753987** [NetEase/pomelo#1140]
求教，最近开发过程中总是出现这个问题，导致我某个服务器和master断开连接，有大佬知道怎么解决吗？

**Comment by Ruan5** [comment]
mqtt rpc client 請更新到3.2.0

**Comment by whtiehack** [comment]
> mqtt rpc client 請更新到3.2.0

具体一点就是更新 pomelo-admin 里的   mqtt-connection版本。

**Comment by yunmin97** [comment]
我的mqtt-connection版本已经是3.2.0了，还是会出现这样的问题？

**Comment by whtiehack** [comment]
win10的话就换用 git bash 不要用 cmd

**Comment by yunmin97** [comment]
嗯，确实是用了cmd，用powershell也一样！等我换bash试试再反馈，谢谢🙏


On 08/19/2019 09:45, smallwhite wrote:

win10的话就换用 git bash 不要用 cmd

**Comment by yunmin97** [comment]
win10下git bash运行pomelo start，闲置一段时间后还是会出现这个问题：
[2019-08-20 19:51:05.469] [ERROR] pomelo-admin - [MqttClient] mqtt rpc client checkKeepAlive error timeout for 120000
@whtiehack

**Comment by awhlmycn** [comment]
@yunmin97 请问你的问题解决了吗?我这边也是这个问题了,跑一段时间就主动和master断开连接了. 也是windows 系统的了.

**Comment by yunmin97** [comment]
我在阿里云上面跑没问题，就是自己的电脑上跑才出现，现在没时间去研究，后面再仔细看看源码




On 09/30/2019 11:20, awhlmycn wrote:

@yunmin97 请问你的问题解决了吗?我这边也是这个问题了,跑一段时间就主动和master断开连接了. 也是windows 系统的了.
