### ISSUE TITLE
servers目录下的handler和remote都有什么作用，换个名字行不行？

### ISSUE THREAD

**Issue by peiweippww** [NetEase/pomelo#121]
1.servers目录下的handler和remote都有什么作用，换个名字行不行？

2.由客户端发起一个websocket通信，比如说是connerctor.enteryHandler.entry，这样回去访问servers下connector下的handler文件内的enteryHandler。路由解析是不是与enteryHandler这个名字有关，还是这只是个名字。

3.再就是又在connector中使用了app.rpc.chat.chatRemote.add，这里的chatRemote与路由解析有关系没，为什么这里要调用remote，而不直接调用handler，把add方法放在其中。

**Comment by shunhua** [comment]
> handler 是客户端调用，remote是rcp调用
> 
> ------------------ 原始邮件 ------------------
> 发件人: "peiweippww"[notifications@github.com](mailto:notifications@github.com);
> 发送时间: 2013年3月13日(星期三) 上午10:03
> 收件人: "NetEase/pomelo"[pomelo@noreply.github.com](mailto:pomelo@noreply.github.com);
> 
> 主题: Re: [pomelo] servers目录下的handler和remote都有什么作用，换个名字行不行？ (#121)
> 
> 谁能精辟的概括下
> 
> —
> Reply to this email directly or view it on GitHub.

rcp?  哈哈哈哈
