### ISSUE TITLE
关于 area 服务器

### ISSUE THREAD

**Issue by newebug** [NetEase/pomelo#166]
现在看起来每个area对应一个地图， 如果我有100个地图，是否必须配置出100个area server？ 

我现在测试有四个地图，也配置了4个area server，但是切换地图有问题，player 是undefined，目前还没有定位出问题在哪。

**Comment by cnlamplighter** [comment]
现在的RPG，地图一般都能上百张，开100个area服，服务器资源扛不住。请问可以不以建立一个分支，共享一下，一个area服务器上启动多个场景的demo早期代码呢？拜谢~~！
@demon0925 @fantasyni @newebug

**Comment by newebug** [comment]
Pomelo 的 设计是分布式的，一台服务器可以配置任意多的area，上百个area也可以分布部署在多个服务器上

**Comment by cnlamplighter** [comment]
@newebug 感谢回答！
