### ISSUE TITLE
A question about the communication performance of Pomelo

### ISSUE THREAD

**Issue by stormzm** [NetEase/pomelo#228]
Hi, 
I use Pomelo to do some performance test with the following code.
 With single client, the response time is 30ms per request(10000request cost 306s)
 With 100 clients, the response time is about 38 ms per request
 With 1000 clients, the response time is about 150ms per request.(Connector's CPU is near 100%, probably this is hardware bottleneck)

My question is if this performance is normal and OK for MMORPG considering there are logical cost and link latency>
Would you please give some topic about the performance optimization of Pomelo?Thx
## client code:

int counter = 0;
int start_time;

static struct router routes[] = {
        { NULL, NULL },
        {"connector.entryHandler.enter", NULL },
        {"hall.playerHandler.test", NULL},
        {"hall.playerHandler.enterHall", NULL },
        {"hall.playerHandler.battle", NULL}
};

void do_request(pc_client_t *client, int cmd);
// request callback
void on_request_cb(pc_request_t *req, int status, json_t *resp) {
       char nm[128];
    int fd;

```
if (status == -1) {
    printf("Fail to send request to server.\n");
} else if (status == 0) {
    char *json_str = json_dumps(resp, 0);
    if (json_str != NULL) {
        //printf("server response: %s\n", json_str);
        free(json_str);
    }
}
json_t *code = json_object_get(resp, "code");
//printf("code=%d\n", json_integer_value(code));

// release relative resource with pc_request_t
json_t *msg = req->msg;
pc_client_t *client = req->client;
json_decref(msg);
pc_request_destroy(req);
counter++;
if(counter==10000) {
    char timd[128];
    sprintf(timd, "%d", time(NULL)-start_time);
    sprintf(nm, "testfile_%d", getpid());
    fd = open(nm,  O_CREAT|O_RDWR, 309);
    printf("%s\n", timd);
    write(fd, timd, strlen(timd));
    close(fd);  
}
    do_request(client, 2);
```
# if 0

```
pc_client_stop(client);
```
# endif

}
void do_request(pc_client_t *client, int cmd) {
    // compose request
    const char *route = routes[cmd].route;
    json_t *msg = json_object();
    json_t *str = json_string("123");
    json_object_set(msg, "uid", str);
    // decref for json object
    json_decref(str);

```
pc_request_t *request = pc_request_new();
pc_request(client, request, route, msg, on_request_cb);
```
## }

Server side
1) connector (just create a session)
var enter_test = function(msg, session, next) {
    var self = this;
    acc_id++;
    session.bind(acc_id);
    session.on('closed', onUserLeave.bind(null, self.app));
    session.pushAll();
    next(null, msgs.gen_msg(msg, consts.Code.OK));
}
2) app server
handler.test = function(msg, session, next) {
    next(null, msgs.gen_msg(msg, consts.Code.OK));
    return;
## }

Data Flow:  client->connector-> app server->client， there is no RPC

**Comment by rathore-digvijay** [comment]
I am facing the issue of 100 percent utilization of CPU. I am running single core google cloud instance with 4gb RAM for each connector, logic and gate servers of mine.
I am connecting clients from game build as well as automated code behaving like bots.
When these starts the playing the game, the connectors CPU isn't used that much but the logic's CPU utilization reached 100% and then broadcast starts failing silently.

Can you suggest anything to resolve and debug the issue?
