### ISSUE TITLE
很多ECONNRESET異常

### ISSUE THREAD

**Issue by gsxiang** [NetEase/pomelo#247]
我們的pomelo服務器出現很多  Caught exception: Error: read ECONNRESET 錯誤，不知道是pomelo裡面哪個模塊的socket沒有處理這個異常，個人懷疑在rpc模塊，pomelo  version 0.3.8

**Comment by 362663496** [comment]
能帮我解决下吗 定位不到原因 也是这种问题 。 362663496@qq.com

**Comment by lixw1994** [comment]
@362663496 在pomelo源码中搜索`net.createServer`，在回调函数中手动捕获这个异常，别被抛到`uncaughtException`即可。

**Comment by 362663496** [comment]
还是会有问题。 我试着在createSever里面写匿名函数 function(socket){
    socket.on('error')……   也是没有用的 之后还是蹦了一次
}




------------------ 原始邮件 ------------------
发件人: "XW Lee"<notifications@github.com>; 
发送时间: 2019年5月21日(星期二) 晚上6:30
收件人: "NetEase/pomelo"<pomelo@noreply.github.com>; 
抄送: "362663496"<362663496@qq.com>; "Mention"<mention@noreply.github.com>; 
主题: Re: [NetEase/pomelo] 很多ECONNRESET異常 (#247)




@362663496 在pomelo源码中搜索net.createServer，在回调函数中手动捕获这个异常，别被抛到uncaughtException即可。
 
- 
你收到这个是因为你被提到了。
直接回复此电子邮件，在GitHub上查看，或将该线程静音。
