### ISSUE TITLE
请教一些问题?

### ISSUE THREAD

**Issue by hbyscpp** [NetEase/pomelo#28]
Hi,感谢开源pomelo框架，有一些问题请教下。
假设我有3个frontend server分别是A B C用于管理client的连接，1个backend server D处理聊天逻辑，假设user 1到user 10连接上A，user 11-user20连接上了B,user 21-user30连接上了C，global session是指单个front server中session集合，还是所有的front server中session集合? 
如果user1 发送一条消息，A直接通过消息路由到D服务器处理，通过rpc来调用D的服务，此时D会copy一份user1的session是不是被称为local session?
backend server是基于功能的划分即垂直划分 如果单个backend server D处理不了那么多聊天请求，能否将垂直功能进一步的水平扩展，即将某个频道用户分布在不同的机器来处理?

**Comment by ipengyo** [comment]
mark
