### ISSUE TITLE
timeout filter的問題

### ISSUE THREAD

**Issue by jiangzhuo** [NetEase/pomelo#369]
這個filter有一個問題 有一個timeouts的集合，
在bfore函數中有添加，再after中有刪除
在一種極端的情況下（比如某人寫錯了邏輯爆出錯沒有catch，只有before進行了調用，沒有調用after），這個集合會不斷增大，最終導致問題。希望有修改一下。

**Comment by wuxian** [comment]
我觉得TIMEOUT在开发的时候可以用用，生产的时候应该关闭，他的timeout功能本身serail那个也带了，timeout会跟它冲突，因为两个都带超时，但是时间却可能不一样，就会奇奇怪怪的，具体的我忘记了，反正我没用这个就是了，而且这个东西都带定时器，一个包上来带两个定时器就太坑了，生产上还是不要用这个timeout比较好
