### ISSUE TITLE
pomelo.on 没有响应

### ISSUE THREAD

**Issue by jacky9003** [NetEase/pomelo#398]
在web-server 中加入了如下方法，
pomelo.on('onReceiveData', function(data) {
                console.log("orvs");
                console.log(data.data);
});

---

在area.js中加入了如下方法：
var getChannel = exp.getChannel= function() {
    if(channel) {
        return channel;
    }

```
channel = pomelo.app.get('channelService').getChannel('area_' + id, true);
return channel;
```

};

---

在playerHandler.js中加入了如下方法：
handler.testStream = function (msg, session, next) {
    console.log("addImageToPOI");
    var readStream = fs.createReadStream("media_files/images/square_thumbnail/2014-01-22-19:25:056sqcnNBgmz6mhdww0.jpeg", {flags:'r', encoding:'base64', mode:0666, bufferSize:64*1024});
    readStream.on("data", function(data){
        console.log(data);
        area.getChannel().pushMessage({route:'onReceiveData', data:data});
    });
};

---

目前在game-server 的控制台上能看到 area.getChannel().pushMessage({route:'onReceiveData', data:data}); 的输出，但是web-server的 pomelo.on('onReceiveData', function(data)  方法没有被执行。请问我是有什么地方做的不对吗？

有劳了！谢谢！

**Comment by xcyxiner** [comment]
```
groups: {}, --->这个正常情况下应该是不为空的，看起来像session 绑定的时候出问题了
```
