### ISSUE TITLE
Pomelo support wss?

### ISSUE THREAD

**Issue by MQuy** [NetEase/pomelo#410]
I build a simple multiplayer game and upload to facebook. Everything work fine except Firefox because the ws protocal doesn't support due to ssl privacy. It have to be wss, i try but pomelo can't handle that kind of request.

Is there anyway to config or workaround to do that?

Thanks

**Comment by creatiosoft** [comment]
Hi
I have implemented wss on our server.Now client taking 4x time to connect with server.Please let me know know how i can solve this issue.

**Comment by wuxian** [comment]
@MQuy  :D  https://github.com/NetEase/pomelo/pull/683

**Comment by wuxian** [comment]
@creatiosoft  :D  https://github.com/NetEase/pomelo/pull/683

**Comment by cynron** [comment]
@creatiosoft @MQuy Now, we have support wss, closing, :)
