### ISSUE TITLE
客户端短暂断网后重连返回错误500的问题。

### ISSUE THREAD

**Issue by danlanxiaohei** [NetEase/pomelo#540]
ios客户端，运行期间发现一个问题，具体复现步骤如下：
1，用手机客户端正常连接上服务器。（iphone5s ios7连接wifi）
2，把手机调成飞行模式。于是就断网了。
3，过5秒钟重现打开网络，这时去发消息什么的都发送失败，因为刚才断网了，客户端的连接断开了。
4，这时去重连，但是服务器返回code=500,意思是已经加入了。。。

想了一下原因，客户端闪断网络的情况下，服务器并不知道客户端断了，还以为在线呢，再去连接就会返回500。

怎么解决这个问题呢？

**Comment by xFairs** [comment]
之前的session如何清理？
if( !! sessionService.getByUid(uid)) {
	sessionService.kick(usign, onSessionKick.bind(null, uid));
}

**Comment by yaoqiang** [comment]
应该依赖disconnectOnTimeout之类的配置吧，每次登录就先T会挺蛋疼吧
