### ISSUE TITLE
后端服务器调用pushMessageByUids出错

### ISSUE THREAD

**Issue by jh1982yc** [NetEase/pomelo#565]
后端服务器调用pomelo.app.get('channelService').pushMessageByUids时，提示：
rpc server process message error: "TypeError: Cannot call method 'getByUid' of undefined......
是不是我的方法不对啊，以前在前端服务器调用是没有问题的，代码重构改到后端服务器后就不行了。

**Comment by lightmemory** [comment]
请问找到用户所在前端服务器id之后，用什么去调用pushMessageByUids发送呢？我也是用pomelo.app.get('channelService').pushMessageByUids这句碰到同样的报错

**Comment by lightmemory** [comment]
哦 明白了 就是pushMessageByUids参数里的sid要写前端服务器id
