### ISSUE TITLE
文档也太乱了，并且demo写的代码太乱，运行不了

### ISSUE THREAD

**Issue by design365** [NetEase/pomelo#568]
能不能demo写的规整点，烂七八糟堆在一起，并且那个treasures根本运行不起来，点击登陆没反应。

**Comment by xingxiaoxiong** [comment]
目前，treasures demo还是运行不了。不知道大家是不是有相同的问题。我点击登录后，Chrome console显示：

socket close:  CloseEvent {reason: "", code: 1000, wasClean: true, path: NodeList[0], cancelBubble: false…}
build.js:1451 disconnect
