### ISSUE TITLE
10,000 Concurrent users issue

### ISSUE THREAD

**Issue by acylum** [NetEase/pomelo#603]
I've been trying to achieve 10,000 concurrent users on a high-end 8 core, 16G memory Dell server.

Looking at palmtoy's post on concurrency issues:
https://github.com/NetEase/pomelo/issues/520

I used his robot4chat:
https://github.com/palmtoy/robot4chat

and made a modification in console.js, line 22:
var data = {agent:1,maxuser:8000,robot:'',time:10};

In config.js,
the time interval was set to 201ms:
"master": {"host": "127.0.0.1", "port":8888, "webport":8889, "cwebport":8890, "interval": 201}

The robots were running on a separate physical server from the chatofpomelo server.  I launched chatofpomelo with 24 servers for connector and chat.

The linux server running chatofpomelo had these settings:
net.core.rmem_max = 33554432
net.core.wmem_max = 33554432
net.ipv4.tcp_rmem = 4096 16384 33554432
net.ipv4.tcp_wmem = 4096 16384 33554432
net.ipv4.tcp_mem = 786432 1048576 26777216
net.ipv4.tcp_max_tw_buckets = 360000
net.core.netdev_max_backlog = 2500
vm.min_free_kbytes = 65536
vm.swappiness = 0
net.ipv4.ip_local_port_range = 1024 65535
ulimit -n 999999

I started up a chatofPomelo game and webserver, then started up the robots by running  http.js, app.js, and console.js

By about 360 bot connections – bots started disconnecting  a minute after login(disconnect-undefined).
![screen shot 2014-08-24 at 9 39 51 pm](https://cloud.githubusercontent.com/assets/1613809/4026448/6be8e2f2-2c19-11e4-9640-55384fbc1ccc.png)

I noticed that all of the bots where assigned to just one connector server, so to load balance, I modified the bots to connect to one of the 24 connector servers in a round robin fashion to connect directly to a connector server without having to get a port assignment from the gate.server.

Chat.js:
var connectPort = ((bot_numb-0) - (Math.floor((bot_numb-0)/totalConnectServers)*totalConnectServers))+3050;

pomelo.init({
    host: "xxx.xxx.xxx.xxx",
    port: connectPort,
    log: true
  }, function() {

With the bots being more evenly distributed among the 24 connector servers, I got this result – 420 bots connect before bots start disconnecting after a minute:
![screen shot 2014-08-24 at 9 51 12 pm](https://cloud.githubusercontent.com/assets/1613809/4026457/b25d6776-2c19-11e4-8fe5-7b285091d5f1.png)

Looking at the logs, I noticed that all the bots were joining room “xx”.  This room was on chat-server-19.  I suspected that maybe chat-server-19 was becoming “saturated” with connections and was causing bots to disconnect.

So, I made another change.  I created 24 rooms and used a round robin system to load balance the bots joining these chat rooms as well.

I modified chat.js:
var connectPort = ((bot_numb-0) - (Math.floor((bot_numb-0)/totalConnectServers)*totalConnectServers))+3050;

var rid = 'xx'+connectPort;

var route = "connector.entryHandler.enter";
    pomelo.request(route, {
      username: username,
      rid: rid
    }, function(data) {……

Running this test resulted in 1800 bots connected before bots would be disconnected after 2 - 5 minutes:

![03](https://cloud.githubusercontent.com/assets/1613809/4026499/ebbdf174-2c1a-11e4-9861-16d5b1c0c328.jpg)

Next, I thought that maybe changing the login interval might also have an affect, so I changed the interval from 201ms to 3001ms in config.json
"master": {"host": "127.0.0.1", "port":8888, "webport":8889, "cwebport":8890, "interval": 3001},

and made a modification in console.js, line 22:
var data = {agent:1,maxuser:10000,robot:'',time:10};

and also ran chatofpomelo game and web servers in production mode using this:
NODE_ENV=production node app.js –nouse-idle-notification –max-old-space-size=8192 –max-new-space-size=2048

The results of this – 8320 bots would connect before bots would disconnect 76 – 220 minutes later.
![04](https://cloud.githubusercontent.com/assets/1613809/4026500/140c9f68-2c1b-11e4-8130-3d42c45dfeca.jpg)

In the logs, each connector server and chat server has about 340-345 concurrent connections.  Going above this and connections start to fail.

So, it seems that individual server processes might be limited in Pomelo to around 340 concurrent connections – which doesn't seem right. 

So, while I was able to go from only 360 concurrent connections to 8300 ccu, how I did it seems wrong...

In my research, I’ve found that Socket.io should achieve around 1000 concurrent connections per process.  I also think it is weird that I have to run so many server processes - 24 server processes for a 8 core - shouldn't it only be 8 server processes? - one for each core? but with concurrency of 1000 per server process?

So, my questions are:
1.  How can I increase the number of concurrent connections per server process – can I get above 340 connections and reach 1000 connections per server process?
2.  To achieve 8300 connections, I felt I had to implement a “hack” to load balance.  What would be the proper way of getting the chat-servers load balanced? It seems like when a room is created, it gets assigned to only one chat-server.  Is there a way to take a room and divide it among the chat-servers while still acting as a single room?  My hack, basically create 24 individual rooms that were not connected to each other, but I think there should be a better way to do this.

**Comment by rachelxj** [comment]
@acylum would you please tell me how to run the robot4chat? I used the latest node (0.12) and latest chatofpomelo, but when I built robot4chat, the understore version used in this project is not available, so I changed it into 1.8.2, but when I started app, it shows FAILED TO RUN, return code: 1, 
I don't know how to run this robot chat client to do a performance test. Would you please give me some guide? Thanks alot
