### ISSUE TITLE
Help for English Speakers

### ISSUE THREAD

**Issue by joshjung** [NetEase/pomelo#632]
I love Pomelo, however most of the logged bugs and even some of the documentation is either in Chinese or appears to be translated from Chinese in a way that some of the information seems to be lost.

Are there any plans to help English speakers? Does the Pomelo team want help writing pure English documentation by a native speaker?

Thank you! Most of the documentation has been fantastic but some is difficult to understand.

**Comment by w3hacker** [comment]
I love pomelo and mqtt.

**Comment by impcyber** [comment]
Hi guys, so, how is it going?
