### ISSUE TITLE
channelService的实现

### ISSUE THREAD

**Issue by rangercyh** [NetEase/pomelo#634]
请问，当客户端连接上之后，客户端的一个消息过来，执行connector的某个函数时，函数里调用了 this.app.get('channelService').broadcast('connector', 'onHey', {content:'hey~'}, {}, function(err) {
    if (err) {
        console.error(err.stack);
    }
});
然后在客户端这边，我用的是libpomelo，连接之前，已经添加了 onHey 事件的监听，但是结果没有收到，不过客户端发给服务的消息，服务端倒是确实收到了，而且服务端之后发送的 disconnect 消息，客户端也收到了，只是这个自定义的事件客户端没有收到。
pc_add_listener(client, "onHey", on_hey);
pc_add_listener(client, PC_EVENT_DISCONNECT, on_close);

**Comment by hzhxyz** [comment]
我也遇到了类似的问题。我在connector中添加了一个自定义组件，组件中使用到了channelService，通过load的方式加载组件到connector中。然而组件打印的信息显示，channelService的其他函数都能正常调用，但是调用broadcast就会出现Caught exception: TypeError: Cannot call method 'broadcast' of undefined的错误。

另外，在connector中通过channelService获取的channel中并没有任何用户，而我所有的channel都是在connector服务器中创建的。
