### ISSUE TITLE
[建议]优化[].slice.call的用法

### ISSUE THREAD

**Issue by hairui219** [NetEase/pomelo#648]
研读源码时发现，在/lib/application.js的Application.configure方法中，使用了如下方法：

``` json
[].slice.call(arguments);
```

在[这篇讨论](http://stackoverflow.com/questions/23509312/does-node-js-really-not-optimize-calls-to-slice-callarguments)中，提到这种用法的运行效率十分低下，并提供了例子可供证明（见原文）。同时，node.js官方也对这种使用方式进行了修复（[链接](https://github.com/joyent/node/commit/91f1b250ecb4fb8151cd17423dd4460652d0ce97))。

实际使用场景中，Application.configure只会在初始化时进行调用，因此对性能影响不大。不过我建议修复此种用法，为研读学习pomelo的人群提供效率更高的实现方式。

**Comment by fantasyni** [comment]
已经优化了
