### ISSUE TITLE
Unity Pomelo broadcast message is not received sometimes.

### ISSUE THREAD

**Issue by SagarDabas** [NetEase/pomelo#650]
Hi,
We are using Pomelo for networking in our game. Unity Client is registered for some broadcast events, in very rare cases broadcast messages are not received by the unity client. But the messages are broadcasted from the server.

I have tried putting logs in SocketMessage method of PomeloClient but no logs were printed. If anyone has any clue or suggestions about the problem, then please reply.

Thanks

**Comment by saied63** [comment]
Hi,
I have a same problem . i used pomelo pushMessageByUid for sending messages to unity client but messages does not reach to unity in  many cases . i asked my question hear : 
http://stackoverflow.com/questions/28194361/pomelo-cant-pushmessage-to-unity3d-when-the-number-of-requests-are-high
but i had no answer !  . I spent one month for learning pomelo But now i think i wast my time .. .

**Comment by SagarDabas** [comment]
There are many issues with this client .. I replaced websocket4net with websocket4sharp and most of the issues were gone. Including this one.
