### ISSUE TITLE
LINUX 下安装报错

### ISSUE THREAD

**Issue by whuhenrylee** [NetEase/pomelo#652]
> heapdump@0.2.9 install /data/nodejs/node_modules/pomelo/node_modules/pomelo-admin/node_modules/heapdump
> node-gyp rebuild

make: Entering directory `/data/nodejs/node_modules/pomelo/node_modules/pomelo-admin/node_modules/heapdump/build'
  CXX(target) Release/obj.target/heapdump/src/heapdump.o
  CXX(target) Release/obj.target/heapdump/src/platform-posix.o
  SOLINK_MODULE(target) Release/obj.target/heapdump.node
./Release/linker.lock: No such file or directory
make: *** [Release/obj.target/heapdump.node] Error 3
make: Leaving directory`/data/nodejs/node_modules/pomelo/node_modules/pomelo-admin/node_modules/heapdump/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:809:12)
gyp ERR! System Linux 2.6.16.60-0.21-TENCENT64-120327
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /data/nodejs/node_modules/pomelo/node_modules/pomelo-admin/node_modules/heapdump
gyp ERR! node -v v0.10.29
gyp ERR! node-gyp -v v0.13.1
gyp ERR! not ok 

> ws@0.4.25 install /data/nodejs/node_modules/pomelo/node_modules/ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)
## \

npm ERR! Error: ENOENT, utime '/data/nodejs/node_modules/pomelo/node_modules/pomelo-admin/node_modules/pomelo-scheduler/node_modules/log4js/test/categoryFilter-test.js'
npm ERR! If you need help, you may report this _entire_ log,
npm ERR! including the npm and node versions, at:
npm ERR!     http://github.com/npm/npm/issues
npm ERR! System Linux 2.6.16.60-0.21-TENCENT64-120327
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "install" "pomelo"
npm ERR! cwd /data/nodejs
npm ERR! node -v v0.10.29
npm ERR! npm -v 1.4.14
npm ERR! path /data/nodejs/node_modules/pomelo/node_modules/pomelo-admin/node_modules/pomelo-scheduler/node_modules/log4js/test/categoryFilter-test.js
npm ERR! fstream_path /data/nodejs/node_modules/pomelo/node_modules/pomelo-admin/node_modules/pomelo-scheduler/node_modules/log4js/test/categoryFilter-test.js
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! fstream_finish_call utimes
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! fstream_stack /usr/local/lib/node_modules/npm/node_modules/fstream/lib/writer.js:305:19
npm ERR! fstream_stack Object.oncomplete (fs.js:107:15)
npm ERR! Error: ENOENT, lstat '/data/nodejs/node_modules/pomelo/node_modules/mqtt/node_modules/bops/node_modules/to-utf8/test.js'
npm ERR! If you need help, you may report this _entire_ log,
npm ERR! including the npm and node versions, at:
npm ERR!     http://github.com/npm/npm/issues
npm ERR! System Linux 2.6.16.60-0.21-TENCENT64-120327
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "install" "pomelo"
npm ERR! cwd /data/nodejs
npm ERR! node -v v0.10.29
npm ERR! npm -v 1.4.14
npm ERR! path /data/nodejs/node_modules/pomelo/node_modules/mqtt/node_modules/bops/node_modules/to-utf8/test.js
npm ERR! fstream_path /data/nodejs/node_modules/pomelo/node_modules/mqtt/node_modules/bops/node_modules/to-utf8/test.js
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! fstream_stack /usr/local/lib/node_modules/npm/node_modules/fstream/lib/writer.js:284:26
npm ERR! fstream_stack Object.oncomplete (fs.js:107:15)
npm ERR! error rolling back Error: ENOTEMPTY, rmdir '/data/nodejs/node_modules/pomelo/node_modules/mqtt/node_modules/bops/node_modules/base64-js'
npm ERR! error rolling back  pomelo@1.1.3 { [Error: ENOTEMPTY, rmdir '/data/nodejs/node_modules/pomelo/node_modules/mqtt/node_modules/bops/node_modules/base64-js']
npm ERR! error rolling back   errno: 53,
npm ERR! error rolling back   code: 'ENOTEMPTY',
npm ERR! error rolling back   path: '/data/nodejs/node_modules/pomelo/node_modules/mqtt/node_modules/bops/node_modules/base64-js' }
npm ERR! heapdump@0.2.9 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the heapdump@0.2.9 install script.
npm ERR! This is most likely a problem with the heapdump package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls heapdump
npm ERR! There is likely additional logging output above.
npm ERR! System Linux 2.6.16.60-0.21-TENCENT64-120327
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "install" "pomelo"
npm ERR! cwd /data/nodejs
npm ERR! node -v v0.10.29
npm ERR! npm -v 1.4.14
npm ERR! code ELIFECYCLE
npm ERR! Error: ENOENT, open '/data/nodejs/node_modules/pomelo/node_modules/pomelo-scheduler/node_modules/log4js/.bob/instrumented/test/streams/test-rolling-file-stream-write-more.1'
npm ERR! If you need help, you may report this _entire_ log,
npm ERR! including the npm and node versions, at:
npm ERR!     http://github.com/npm/npm/issues
npm ERR! System Linux 2.6.16.60-0.21-TENCENT64-120327
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "install" "pomelo"
npm ERR! cwd /data/nodejs
npm ERR! node -v v0.10.29
npm ERR! npm -v 1.4.14
npm ERR! path /data/nodejs/node_modules/pomelo/node_modules/pomelo-scheduler/node_modules/log4js/.bob/instrumented/test/streams/test-rolling-file-stream-write-more.1
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! Error: ENOENT, lstat '/data/nodejs/node_modules/pomelo/node_modules/pomelo-logger/node_modules/log4js/node_modules/readable-stream/lib/_stream_readable.js'
npm ERR! If you need help, you may report this _entire_ log,
npm ERR! including the npm and node versions, at:
npm ERR!     http://github.com/npm/npm/issues
npm ERR! System Linux 2.6.16.60-0.21-TENCENT64-120327
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "install" "pomelo"
npm ERR! cwd /data/nodejs
npm ERR! node -v v0.10.29
npm ERR! npm -v 1.4.14
npm ERR! path /data/nodejs/node_modules/pomelo/node_modules/pomelo-logger/node_modules/log4js/node_modules/readable-stream/lib/_stream_readable.js
npm ERR! fstream_path /data/nodejs/node_modules/pomelo/node_modules/pomelo-logger/node_modules/log4js/node_modules/readable-stream/lib/_stream_readable.js
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! fstream_stack /usr/local/lib/node_modules/npm/node_modules/fstream/lib/writer.js:284:26
npm ERR! fstream_stack Object.oncomplete (fs.js:107:15)
npm ERR! Error: ENOENT, lstat '/data/nodejs/node_modules/pomelo/node_modules/pomelo-logger/node_modules/log4js/node_modules/async/deps/nodeunit.js'
npm ERR! If you need help, you may report this _entire_ log,
npm ERR! including the npm and node versions, at:
npm ERR!     http://github.com/npm/npm/issues

npm ERR! System Linux 2.6.16.60-0.21-TENCENT64-120327
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "install" "pomelo"
npm ERR! cwd /data/nodejs
npm ERR! node -v v0.10.29
npm ERR! npm -v 1.4.14
npm ERR! path /data/nodejs/node_modules/pomelo/node_modules/pomelo-logger/node_modules/log4js/node_modules/async/deps/nodeunit.js
npm ERR! fstream_path /data/nodejs/node_modules/pomelo/node_modules/pomelo-logger/node_modules/log4js/node_modules/async/deps/nodeunit.js
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! fstream_stack /usr/local/lib/node_modules/npm/node_modules/fstream/lib/writer.js:284:26
npm ERR! fstream_stack Object.oncomplete (fs.js:107:15)
npm ERR! Error: ENOENT, lstat '/data/nodejs/node_modules/pomelo/node_modules/pomelo-admin/node_modules/socket.io-client/dist/WebSocketMain.swf'
npm ERR! If you need help, you may report this _entire_ log,
npm ERR! including the npm and node versions, at:
npm ERR!     http://github.com/npm/npm/issues

npm ERR! System Linux 2.6.16.60-0.21-TENCENT64-120327
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "install" "pomelo"
npm ERR! cwd /data/nodejs
npm ERR! node -v v0.10.29
npm ERR! npm -v 1.4.14
npm ERR! path /data/nodejs/node_modules/pomelo/node_modules/pomelo-admin/node_modules/socket.io-client/dist/WebSocketMain.swf
npm ERR! fstream_path /data/nodejs/node_modules/pomelo/node_modules/pomelo-admin/node_modules/socket.io-client/dist/WebSocketMain.swf
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! fstream_stack /usr/local/lib/node_modules/npm/node_modules/fstream/lib/writer.js:284:26
npm ERR! fstream_stack Object.oncomplete (fs.js:107:15)
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /data/nodejs/npm-debug.log
npm ERR! not ok code 0

**Comment by jianghust** [comment]
一样遇到类似的问题，求解决

**Comment by py8765** [comment]
make有装吗？重试几次

**Comment by jianghust** [comment]
重试过好几次，依然抱着个错误，而且在两个Linux机器上都尝试，都报错

**Comment by cynron** [comment]
确认gcc已经安装

**Comment by zhangjia517** [comment]
这里不知劝退了多少玩家！

**Comment by hottredpen** [comment]
我的是用centos
后来找到这篇文章解决了
“CentOS 升级 gcc 和 g++ 的方法”
http://www.wengweitao.com/centos-sheng-ji-gcc-he-g-de-fang-fa.html
