### ISSUE TITLE
同一个服务器，启动两个项目，怎么停止其中一个项目

### ISSUE THREAD

**Issue by zatchbell** [NetEase/pomelo#671]
我在A项目下用pomelo start启动项目A，然后在B项目下使用pomelo start 命令启动项目B。
这时候我想停掉A项目我应该怎么停？？直接输入pomelo stop 会将所有项目都停掉

**Comment by wuxian** [comment]
pomelo stop 默认是pomelo stop -P 3005 所以如果你要停其它的就跟上master的端口就行
另外应该不会两个项目都停吧，两个项目的master的端口如果一样，第二个是起不来的

**Comment by pipi32167** [comment]
直接pomelo stop将所有项目都停掉是因为你两个项目共用了一个master，这个情况的话，最好写一个脚本，一个个server进程去停。可以读取指定项目的servers.json来处理。
