### ISSUE TITLE
OS X下运行 pomelo env: node\r: No such file or directory

### ISSUE THREAD

**Issue by foodyi** [NetEase/pomelo#677]
按照步骤安装没有报错，但是在终端下执行pomelo命令报错。
node -v v0.10.35
npm -v 1.4.28

**Comment by daemonchen** [comment]
这是因为pomelo的执行文件里，有\r\n导致的。同样的原因在很多node module里都会有。你可以看我这篇blog的[解决方法](http://www.classical1988.com/post/index?stamp=1416390853540)。

如果你觉得手动解决比较麻烦，你也可以安装dos2unix:
`$brew install dos2unix`
然后到你的pomelo安装目录的bin目录下，请参考package.json：
    "bin": {
        "pomelo": "./bin/pomelo"
      },
`$cd path to pomelo module /bin`
在bin目录下，执行:
`sudo dos2unix pomelo `。

然后，enjoy yourself。

**Comment by runawaygo** [comment]
@daemonchen 应该跟这个没关系吧，你怎么还跑到pomelo这边搞这个问题？

**Comment by daemonchen** [comment]
@runawaygo  发现没人回答，就回答了一下。被你看到了😄
