### ISSUE TITLE
feature Request：每个server目录下可选配置一个event.js文件！

### ISSUE THREAD

**Issue by zj8487** [NetEase/pomelo#678]
场景：
一个项目有很多个```server```，每个server在运行时对各种事件的响应不一致。
这种情况类似```lifecycle.js```的作用

实现功能也很简单，加载```server```时检查下是否存在```event.js```，然后将事件函数绑定。
时间定义规则建议和插件功能中的事件定义一致。
代码可参考 ```Application.use```函数

@fantasyni 
@py8765

**Comment by py8765** [comment]
自定义抛出的事件？

**Comment by zj8487** [comment]
@py8765 
就是系统事件：添加服务器，删除服务器等事件。

**Comment by zj8487** [comment]
框架不支持也没有关系。自己应用层实现也ok，需求不是那么急迫，先关闭。
