### ISSUE TITLE
关于app.enable('systemMonitor') 到这在hendler 里面使用remote ,出现undefinde问题

### ISSUE THREAD

**Issue by shuhuiguo** [NetEase/pomelo#684]
如何，最近使用pomelo，碰到一个问题，在app.js里面，添加app.enable('systemMonitor')，
windows 环境下，当pomelo 启动以后 ，刚开始能在hendler里面，使用app.rpc.xxxServer.xxxRemote.fun(xx,xx)等方法，但是运行一会以后，再次调用该handler时，就出报错，出现xxxServer  undefinde.
当把app.enable('systemMonitor')去掉时，没问题
很纳闷，这关app.enable('systemMonitor') 什么事情啊，不是pomelo的一个监控插件吗。。。。？？？

**Comment by zj8487** [comment]
是不是你的xxxServer已经挂了？

**Comment by shuhuiguo** [comment]
没有，不然，handler也会报错，不能调用的

**Comment by wuxian** [comment]
windows下不要enable systemMonitor 这个东西使用到了pomelo-monitor这个库，这个东西现在只能在linux下运行，admin里面奔溃会导致进程异常
