### ISSUE TITLE
io.js support

### ISSUE THREAD

**Issue by impcyber** [NetEase/pomelo#685]
Has anyone tested Pomelo on [io.js](https://iojs.org/)? Whether it is compatible with [io.js](https://iojs.org/) and whether it is planned to support as an environment for Pomelo also like a [Node.js](http://nodejs.org/)?

**Comment by zj8487** [comment]
@impcyber 
i use pomelo on io.js, until now i did not find incompatible issues.

**Comment by impcyber** [comment]
Thanks for reply. I'll try.
