### ISSUE TITLE
pomelo stop后，怎样存档数据

### ISSUE THREAD

**Issue by jh1982yc** [NetEase/pomelo#694]
服务器中的临时数据，在pomelo stop后，需要在哪里去做最后的保存；另外，如果服务器崩溃，临时数据如何保存

**Comment by py8765** [comment]
正常结束前可以在生命周期函数中做保存，崩溃这个就没有太好的办法

**Comment by pipi32167** [comment]
使用redis之类的外部缓存来保存你的临时数据。

**Comment by jh1982yc** [comment]
那么生命周期函数在哪里

**Comment by pipi32167** [comment]
看下lifecycle.js的用法
