### ISSUE TITLE
UID is Null

### ISSUE THREAD

**Issue by renatodex** [NetEase/pomelo#698]
Im trying to use Channels. But for that i need to know the Session UID.

However, when i console.log the session varable in my handler, i got this:

![screen shot 2015-02-15 at 16 39 35](https://cloud.githubusercontent.com/assets/68507/6204415/73d1ef12-b531-11e4-801a-2b6fb0bae97d.png)

What i am doing wrong? The server should not auto generate these UIDs?

**Comment by impcyber** [comment]
Look at these chat of pomelo example:
https://github.com/NetEase/chatofpomelo/blob/master/game-server/app/servers/connector/handler/entryHandler.js

uid is generated manually:
```
var uid = msg.username + '*' + rid;
```

**Comment by renatodex** [comment]
Oh, i see.
Thanks!
