### ISSUE TITLE
Auto Disconnect User

### ISSUE THREAD

**Issue by renatodex** [NetEase/pomelo#699]
Im trying to create a setTimeout event in Pomelo to ping for all users and check its latence to allow the server to autodisconnect users who had connection problems / client crash.

However, i dont know if Pomelo has some built in feature to do this better.

Can someone help me?

**Comment by impcyber** [comment]
Pomelo connection has a "hearbeat" support, so it automatically will disconnected zombie users. Take a look here, i may wrong:
https://github.com/NetEase/pomelo/blob/master/lib/connectors/commands/heartbeat.js
