### ISSUE TITLE
Pomelo 是否适合做实时的邮件系统

### ISSUE THREAD

**Issue by lcsoftware** [NetEase/pomelo#700]
公司最近在做一个拥有实时功能的web项目，类似一个邮件系统，但必须具有实时的功能，即用户在发送了邮件后，对方立刻就可以收到。不知道pomelo是否适合做这样的应用？

**Comment by fantasyni** [comment]
发个通知把，然后收到通知拉下邮件~

**Comment by skyblue** [comment]
可以做,但感觉不适合, 毕竟只有一个通知是需要实时的

**Comment by luoyjx** [comment]
用socket.io试试呗？
