### ISSUE TITLE
pomelo 修改了程序后，服务能否自动重启？

### ISSUE THREAD

**Issue by lcsoftware** [NetEase/pomelo#701]
修改了程序后，服务能否自动重启？调度阶段太费事了。能不能像nodemon一样？

**Comment by cynron** [comment]
没有做热更新支持

**Comment by cynron** [comment]
目前缺省没有做热更新支持，但是可以通过一些途径，自己实现热更新支持

**Comment by fantasyni** [comment]
用 bearcat [hot reload](http://bearcatjs.org/topic/index.html)
