### ISSUE TITLE
websocket error

### ISSUE THREAD

**Issue by Neimd** [NetEase/pomelo#702]
When connect to the game server in IE10 or IE11, often seen "websocket parser error no handler for opcode 10" console log. but Chrome and firefox is well.

i set connector option like below.
{ 
connector : pomelo.connectors.sioconnector, 
transports : [ 'websocket', 'htmlfile', 'xhr-polling', 'jsonp-polling', flashsocket' ]
heartbeats : true, closeTImeOut : 120, heartbeatTimeout : 120, heartbeatInterval : 50
 }

pomelo version 1.1.1

how can resolve it? help me.

**Comment by cynron** [comment]
according to [https://tools.ietf.org/html/rfc6455#section-5.1](https://tools.ietf.org/html/rfc6455#section-5.1), opcode 10 means `pong` frame, IE 10 or 11 does not support `pong` frame?
