### ISSUE TITLE
这两行是否冗余?

### ISSUE THREAD

**Issue by skyblue** [NetEase/pomelo#703]
https://github.com/NetEase/pomelo/blob/master/lib/connectors/commands/handshake.js#L53
平添了handshake消息的大小
这两行是否冗余了

**Comment by cynron** [comment]
直接计算好，传到客户端，在客户端不用重新计算了.

**Comment by skyblue** [comment]
嗯 用途是清楚的, 就是觉得浪费流量, 这个转换放在客户端也能处理
