### ISSUE TITLE
进来PY,有个BUG

### ISSUE THREAD

**Issue by wuxian** [NetEase/pomelo#705]
RPC的REMOTE热更新有bug,一旦开启，会用变更的部分去替换全部RPC服务，我已经被这个把生产搞蹦了，我测试了下，这样改可以解决，你改下吧，现在POMELO代码不好提交
rpc-server/gateway.js 这个函数改成这样

``` javascript
var watchServices = function(gateway, dispatcher) {
  var paths = gateway.opts.paths;
  var app = gateway.opts.context;
  for(var i=0; i<paths.length; i++) {
    (function(index) {
      fs.watch(paths[index].path, function(event, name) {
        if(event === 'change') {
          var item = paths[index];
          var m = Loader.load(item.path, app);
          if (m) {
            dispatcher.emit('reload', item.namespace, m);
          }
        }
      });
    })(i);
  }
};
```

rpc-server/dispatcher.js改

``` javascript
var Dispatcher = function(services) {
  EventEmitter.call(this);
  var self = this;
  this.on('reload', function(namespace, m) {
      createNamespace(namespace, self.services);
      for (var s in m) {
        self.services[namespace][s] = m[s];
      }
  });
  this.services = services;
};

var createNamespace = function(namespace, proxies) {
  proxies[namespace] = proxies[namespace] || {};
};
```

**Comment by fantasyni** [comment]
这个需求最好用 bearcat 解决~

**Comment by wuxian** [comment]
@fantasyni　大神，bearcat 太复杂了，不适合我这种菜鸟

**Comment by py8765** [comment]
具体导致什么问题，能详细说明一下吗

**Comment by skyblue** [comment]
是有问题,我是这么改的
![image](https://cloud.githubusercontent.com/assets/248937/6724124/e8c30d7e-ce2c-11e4-86f0-c93bf22c9e5f.png)

**Comment by wuxian** [comment]
@py8765 只要打开　reloadRemotes: true　，在场景的scene/remote 下随便vi一个文件，linux下甚至不用改，就会触发热更新remote，这个时候你看上面这个代码也知道，remote目录是很多下面都有的，scene, manager等等，而这里只是loader 了一个目录的remote，却用他替换全部的services，于是除了这个热更新的remote的rpc还在，其它的全部丢失，然后connector那边发来的消息转给其它服的，因为remote没了，直接报no namespace sys

**Comment by wuxian** [comment]
@py8765  @skyblue 上面这个朋友的代码修改一下就能看出原来的bug是什么
