### ISSUE TITLE
你好管理，那个chat实例好像对node的版本有错误

### ISSUE THREAD

**Issue by ct0593** [NetEase/pomelo#708]
我用node0.10.1的测试chat实例可行。
但是用最新的node12测试就出错。
而且好像node12对init出来的实例都不是很好的支持。

**Comment by cynron** [comment]
报的什么错误？

**Comment by ct0593** [comment]
@cynron http://chuantu.biz/t/68/1426685567x1822611441.png 如图示的错误。

**Comment by liyunsheng** [comment]
遇到了一样的问题，用的iojs 1.0.4

**Comment by ct0593** [comment]
@liyunsheng 额，iojs可以用来跑pomelo么

**Comment by cynron** [comment]
由于无论是node，还是iojs，从0.10.x升级到0.12.x或iojs的1.x，2.x，API都有较大的变化，这使得pomelo目前不能很好地在高版本的node上运行，后续有待于兼容.

**Comment by Austuode** [comment]
你好管理，选择最稳定的支持pemole的nodejs是10的哪个版本呢？

**Comment by wuxian** [comment]
@Austuode 我线上跑0.10.35跑了非常久了，非常稳定

**Comment by zxc122333** [comment]
pomelo-protocol里面这个bug修掉就能在node 0.12和iojs上跑了。
话说pomelo-protocol 最新版0.1.6已经修掉了这个bug，但是pomelo的依赖依然写死0.1.4
为什么不用"^0.1.4"这种推荐形式？

**Comment by Austuode** [comment]
@zxc122333 具体错误在哪一行呢

**Comment by zxc122333** [comment]
你截图的堆栈里就有，decode里面

**Comment by py8765** [comment]
已经更新到0.1.6

**Comment by skyblue** [comment]
为什么不照 @zxc122333 说的
使用^0.1.4的格式呢?
