### ISSUE TITLE
In game-server how to use mongodb and mongoose?

### ISSUE THREAD

**Issue by quangmydn** [NetEase/pomelo#710]
In game-server how to use mongodb and mongoose? Please show me example.

Thanks you!

**Comment by zj8487** [comment]
@qiankanglai 
i think it has no relation with pomelo.

**Comment by quangmydn** [comment]
In Lord Of Pomelo Use MySql, but I want use mongodb how do it?

**Comment by qiankanglai** [comment]
@zj8487 I don't think it's related to me...

**Comment by zj8487** [comment]
@qiankanglai 
sorry for mistake
