### ISSUE TITLE
文档建议

### ISSUE THREAD

**Issue by lcsoftware** [NetEase/pomelo#711]
非常看好pomelo的，也一直在关注，但咱们的文档真的解决不了什么问题，太多人看完了，也不知道pomelo怎么用，能用来做什么。请看以下的文档结构，个人感觉很好
http://endymecy.gitbooks.io/spark-programming-guide-zh-cn/content/spark-streaming/basic-concepts/input-DStreams.html

**Comment by fantasyni** [comment]
会出gitbook的文档的
