### ISSUE TITLE
servers.json配置域名或public IP出错

### ISSUE THREAD

**Issue by rachelxj** [NetEase/pomelo#719]
我在Amazon EC2安装chatofpomelo, 将connector中的host改成机器的域名或公共IP地址，运行时出现

The authenticity of host 'machine-ip (machine-ip)' can't be established.
ECDSA key fingerprint is d3:cc:b4:cf:fe:41:32:24:f0:02:5b:79:ad:e0:1e:a0.
Please type 'yes' or 'no': Are you sure you want to continue connecting (yes/no)? The authenticity of host 'machine-ip (machine-ip)' can't be established.
Please type 'yes' or 'no':
但这个无法自动确认，运行后造成http://machine-ip:3014/socket.io/1/无法访问，我对Ubuntu不熟悉，不知道要怎么才能解决这个问题

我已经添加了config文件到/root/.ssh目录下，设置了
Host *
HashKnownHosts no
CheckHostIP no
StrictHostKeyChecking no
仍然显示
[2015-04-12 05:20:25.511] [WARN] pomelo - [/home/ubuntu/p2p/PomeloSignalServer/game-server/node_modules/pomelo/lib/master/starter.js] child process exit with error, error code: 255, executed command: ssh

Permission denied (publickey).

当前用户不是Root用户，是用sudo pomelo start 来执行的

**Comment by lichungod** [comment]
ec2机器有10开头的内网地址，配这个地址试试

**Comment by pipi32167** [comment]
servers.json里配置内网ip，gate返回connector信息时返回外网ip。

我的做法：

```
    "connector": [{
      "id": "connector",
      "host": "内网ip",
      "port": "内网端口++",
      "clientHost": "外网ip",
      "clientPort": "外网端口++",
      "frontend": true,
      "clusterCount": 1
    }],
```
