### ISSUE TITLE
how to use rpc to get i need area when architect multiple connector, area?

### ISSUE THREAD

**Issue by letiennam29** [NetEase/pomelo#722]
This is picture architect  of lordofpomelo:
![687474703a2f2f706f6d656c6f2e6e6574656173652e636f6d2f7265736f757263652f646f63756d656e74496d6167652f6c6f72646f66706f6d656c6f2f67616d652d7365727665722e706e67](https://cloud.githubusercontent.com/assets/5987534/7152352/3084a11c-e364-11e4-8dc1-43bea98b6f6a.png)

I don't know call from area to another area.

Can you explain help me?
## I only see  use line command at process connector:

var onUserLeave = function (app, session, reason) {
    if(!session || !session.uid) {
        return;
    }
    app.rpc.area.playerRemote.playerLeave(session, {playerId: session.get('playerId'), instanceId: session.get('instanceId')}, function(err){
        if(!!err){
            logger.error('user leave error! %j', err);
        }
    });
};
## and function handler at process area:

exp.playerLeave = function(args, cb){
  var playerId = args.playerId;
  var area = pomelo.app.areaManager.getArea(args.instanceId);
  var player = area.getPlayer(playerId);
....
....
};

**Comment by impcyber** [comment]
I don't understand your question correctly. But about RPC in Pomelo you can read here: https://github.com/NetEase/pomelo/wiki/Rpc-framework
and here:
https://github.com/NetEase/pomelo/wiki/Rpc-framework

**Comment by TrailMa** [comment]
I'm confused.
What's the diffirence between hero:
https://github.com/NetEase/pomelo/wiki/Rpc-framework
and here:
https://github.com/NetEase/pomelo/wiki/Rpc-framework.
It seems to be the same address

**Comment by TrailMa** [comment]
I'm confused.
What's the diffirence between hero:
https://github.com/NetEase/pomelo/wiki/Rpc-framework
and here:
https://github.com/NetEase/pomelo/wiki/Rpc-framework.
It seems to be the same address

**Comment by TrailMa** [comment]
I'm confused.
What's the diffirence between hero:
https://github.com/NetEase/pomelo/wiki/Rpc-framework
and here:
https://github.com/NetEase/pomelo/wiki/Rpc-framework.
It seems to be the same address

**Comment by letiennam29** [comment]
tks @impcyber  and @TrailMa .

Actually, i want a way comunication the area together. 

From area to another area.

**Comment by impcyber** [comment]
Sorry, i'm wrong, the second url is: https://github.com/NetEase/pomelo/wiki/Rpc-invocation

**Comment by impcyber** [comment]
letiennam29, why not use somthing like AreaManager and make area pool?

**Comment by letiennam29** [comment]
@impcyber correct problem i need AreaManager(area pool), but I don't know how to create and use.

Can you tell me about the sample area manager?

**Comment by letiennam29** [comment]
I have found what I needed.

Call to from area to another area using:
https://github.com/NetEase/pomelo-rpc#clientrpcinvokeserverid-msg-cb

**Comment by impcyber** [comment]
And look here:
https://github.com/NetEase/lordofpomelo/blob/master/game-server/app/domain/area/instancePool.js

**Comment by letiennam29** [comment]
thank you very much @impcyber !
