### ISSUE TITLE
Installation Problem on Windows 7 x64

### ISSUE THREAD

**Issue by talok** [NetEase/pomelo#724]
Here are steps that I did.
1. Install Node.js
2. Install Python 2.7.9 (Already checked python --version)
3. Install VC++ 2010 Express
4. Install Windows SDK 7.1
5. npm install pomelo -g

and I failed. I tried again several times.

Here is what I got.

C:\Windows\system32>npm install pomelo -g
\

> ws@0.4.25 install C:\Users\Thada\AppData\Roaming\npm\node_modules\pomelo\node_
modules\ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)

|
C:\Users\Thada\AppData\Roaming\npm\node_modules\pomelo\node_modules\ws>if not de
fined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\no
de-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (rebuil
d)
Building the projects in this solution one at a time. To enable parallel build,
please add the "/m" switch.
  bufferutil.cc
..\src\bufferutil.cc(36): error C4430: missing type specifier - int assumed. No
te: C++ does not support default-int [C:\Users\Thada\AppData\Roaming\npm\node_m
odules\pomelo\node_modules\ws\build\bufferutil.vcxproj]
..\src\bufferutil.cc(36): error C2143: syntax error : missing ',' before '&' [C
:\Users\Thada\AppData\Roaming\npm\node_modules\pomelo\node_modules\ws\build\buf
ferutil.vcxproj]
..\src\bufferutil.cc(44): error C4430: missing type specifier - int assumed. No
te: C++ does not support default-int [C:\Users\Thada\AppData\Roaming\npm\node_m
odules\pomelo\node_modules\ws\build\bufferutil.vcxproj]
..\src\bufferutil.cc(44): error C2143: syntax error : missing ',' before '&' [C
:\Users\Thada\AppData\Roaming\npm\node_modules\pomelo\node_modules\ws\build\buf
ferutil.vcxproj]
..\src\bufferutil.cc(62): error C4430: missing type specifier - int assumed. No
te: C++ does not support default-int [C:\Users\Thada\AppData\Roaming\npm\node_m
odules\pomelo\node_modules\ws\build\bufferutil.vcxproj]
..\src\bufferutil.cc(62): error C2143: syntax error : missing ',' before '&' [C
:\Users\Thada\AppData\Roaming\npm\node_modules\pomelo\node_modules\ws\build\buf
ferutil.vcxproj]
..\src\bufferutil.cc(83): error C4430: missing type specifier - int assumed. No
te: C++ does not support default-int [C:\Users\Thada\AppData\Roaming\npm\node_m
odules\pomelo\node_modules\ws\build\bufferutil.vcxproj]
..\src\bufferutil.cc(83): error C2143: syntax error : missing ',' before '&' [C
:\Users\Thada\AppData\Roaming\npm\node_modules\pomelo\node_modules\ws\build\buf
ferutil.vcxproj]
..\src\bufferutil.cc(25): error C2248: 'v8::HandleScope::HandleScope' : cannot
access protected member declared in class 'v8::HandleScope' [C:\Users\Thada\App
Data\Roaming\npm\node_modules\pomelo\node_modules\ws\build\bufferutil.vcxproj]
          C:\Users\Thada\.node-gyp\0.12.2\deps\v8\include\v8.h(816) : see decla
  ration of 'v8::HandleScope::HandleScope'
          C:\Users\Thada\.node-gyp\0.12.2\deps\v8\include\v8.h(800) : see decla
  ration of 'v8::HandleScope'
..\src\bufferutil.cc(26): error C2664: 'v8::FunctionTemplate::New' : cannot con
vert parameter 1 from 'v8::Handle<T> (__cdecl *)(const int)' to 'v8::Isolate *'
 [C:\Users\Thada\AppData\Roaming\npm\node_modules\pomelo\node_modules\ws\build\
bufferutil.vcxproj]
          with
          [
              T=v8::Value
          ]
          There is no context in which this conversion is possible
..\src\bufferutil.cc(28): error C2664: 'node::NODE_SET_METHOD' : cannot convert
 parameter 3 from 'v8::Handle<T> (__cdecl *)(const int)' to 'v8::FunctionCallba
ck' [C:\Users\Thada\AppData\Roaming\npm\node_modules\pomelo\node_modules\ws\bui
ld\bufferutil.vcxproj]
          with
          [
              T=v8::Value
          ]
          Incompatible calling conventions for UDT return value
..\src\bufferutil.cc(29): error C2664: 'node::NODE_SET_METHOD' : cannot convert
 parameter 3 from 'v8::Handle<T> (__cdecl *)(const int)' to 'v8::FunctionCallba
ck' [C:\Users\Thada\AppData\Roaming\npm\node_modules\pomelo\node_modules\ws\bui
ld\bufferutil.vcxproj]
          with
          [
              T=v8::Value
          ]
          Incompatible calling conventions for UDT return value
..\src\bufferutil.cc(30): error C2664: 'node::NODE_SET_METHOD' : cannot convert
 parameter 3 from 'v8::Handle<T> (__cdecl *)(const int)' to 'v8::FunctionCallba
ck' [C:\Users\Thada\AppData\Roaming\npm\node_modules\pomelo\node_modules\ws\bui
ld\bufferutil.vcxproj]
          with
          [
              T=v8::Value
          ]
          Incompatible calling conventions for UDT return value
..\src\bufferutil.cc(31): error C2039: 'NewSymbol' : is not a member of 'v8::St
ring' [C:\Users\Thada\AppData\Roaming\npm\node_modules\pomelo\node_modules\ws\b
uild\bufferutil.vcxproj]
          C:\Users\Thada\.node-gyp\0.12.2\deps\v8\include\v8.h(1599) : see decl
  aration of 'v8::String'
..\src\bufferutil.cc(31): error C3861: 'NewSymbol': identifier not found [C:\Us
ers\Thada\AppData\Roaming\npm\node_modules\pomelo\node_modules\ws\build\bufferu
til.vcxproj]
..\src\bufferutil.cc(38): error C2248: 'v8::HandleScope::HandleScope' : cannot
access protected member declared in class 'v8::HandleScope' [C:\Users\Thada\App
Data\Roaming\npm\node_modules\pomelo\node_modules\ws\build\bufferutil.vcxproj]
          C:\Users\Thada\.node-gyp\0.12.2\deps\v8\include\v8.h(816) : see decla
  ration of 'v8::HandleScope::HandleScope'
          C:\Users\Thada\.node-gyp\0.12.2\deps\v8\include\v8.h(800) : see decla
  ration of 'v8::HandleScope'
..\src\bufferutil.cc(40): error C2065: 'args' : undeclared identifier [C:\Users
\Thada\AppData\Roaming\npm\node_modules\pomelo\node_modules\ws\build\bufferutil
.vcxproj]
..\src\bufferutil.cc(40): error C2228: left of '.This' must have class/struct/u
nion [C:\Users\Thada\AppData\Roaming\npm\node_modules\pomelo\node_modules\ws\bu
ild\bufferutil.vcxproj]
          type is ''unknown-type''
..\src\bufferutil.cc(41): error C2065: 'args' : undeclared identifier [C:\Users
\Thada\AppData\Roaming\npm\node_modules\pomelo\node_modules\ws\build\bufferutil
.vcxproj]
..\src\bufferutil.cc(41): error C2228: left of '.This' must have class/struct/u
nion [C:\Users\Thada\AppData\Roaming\npm\node_modules\pomelo\node_modules\ws\bu
ild\bufferutil.vcxproj]
          type is ''unknown-type''
..\src\bufferutil.cc(46): error C2248: 'v8::HandleScope::HandleScope' : cannot
access protected member declared in class 'v8::HandleScope' [C:\Users\Thada\App
Data\Roaming\npm\node_modules\pomelo\node_modules\ws\build\bufferutil.vcxproj]
          C:\Users\Thada\.node-gyp\0.12.2\deps\v8\include\v8.h(816) : see decla
  ration of 'v8::HandleScope::HandleScope'
          C:\Users\Thada\.node-gyp\0.12.2\deps\v8\include\v8.h(800) : see decla
  ration of 'v8::HandleScope'
..\src\bufferutil.cc(47): error C2065: 'args' : undeclared identifier [C:\Users
\Thada\AppData\Roaming\npm\node_modules\pomelo\node_modules\ws\build\bufferutil
.vcxproj]
..\src\bufferutil.cc(47): error C2227: left of '->ToObject' must point to class
/struct/union/generic type [C:\Users\Thada\AppData\Roaming\npm\node_modules\pom
elo\node_modules\ws\build\bufferutil.vcxproj]
..\src\bufferutil.cc(49): error C2065: 'args' : undeclared identifier [C:\Users
\Thada\AppData\Roaming\npm\node_modules\pomelo\node_modules\ws\build\bufferutil
.vcxproj]
..\src\bufferutil.cc(55): warning C4267: 'initializing' : conversion from 'size
_t' to 'unsigned int', possible loss of data [C:\Users\Thada\AppData\Roaming\np
m\node_modules\pomelo\node_modules\ws\build\bufferutil.vcxproj]
..\src\bufferutil.cc(59): error C2039: 'Close' : is not a member of 'v8::Handle
Scope' [C:\Users\Thada\AppData\Roaming\npm\node_modules\pomelo\node_modules\ws\
build\bufferutil.vcxproj]
          C:\Users\Thada\.node-gyp\0.12.2\deps\v8\include\v8.h(800) : see decla
  ration of 'v8::HandleScope'
..\src\bufferutil.cc(59): error C2660: 'v8::True' : function does not take 0 ar
guments [C:\Users\Thada\AppData\Roaming\npm\node_modules\pomelo\node_modules\ws
\build\bufferutil.vcxproj]
..\src\bufferutil.cc(64): error C2248: 'v8::HandleScope::HandleScope' : cannot
access protected member declared in class 'v8::HandleScope' [C:\Users\Thada\App
Data\Roaming\npm\node_modules\pomelo\node_modules\ws\build\bufferutil.vcxproj]
          C:\Users\Thada\.node-gyp\0.12.2\deps\v8\include\v8.h(816) : see decla
  ration of 'v8::HandleScope::HandleScope'
          C:\Users\Thada\.node-gyp\0.12.2\deps\v8\include\v8.h(800) : see decla
  ration of 'v8::HandleScope'
..\src\bufferutil.cc(65): error C2065: 'args' : undeclared identifier [C:\Users
\Thada\AppData\Roaming\npm\node_modules\pomelo\node_modules\ws\build\bufferutil
.vcxproj]
..\src\bufferutil.cc(65): error C2227: left of '->ToObject' must point to class
/struct/union/generic type [C:\Users\Thada\AppData\Roaming\npm\node_modules\pom
elo\node_modules\ws\build\bufferutil.vcxproj]
..\src\bufferutil.cc(66): warning C4267: 'initializing' : conversion from 'size
_t' to 'unsigned int', possible loss of data [C:\Users\Thada\AppData\Roaming\np
m\node_modules\pomelo\node_modules\ws\build\bufferutil.vcxproj]
..\src\bufferutil.cc(67): error C2065: 'args' : undeclared identifier [C:\Users
\Thada\AppData\Roaming\npm\node_modules\pomelo\node_modules\ws\build\bufferutil
.vcxproj]
..\src\bufferutil.cc(67): error C2227: left of '->ToObject' must point to class
/struct/union/generic type [C:\Users\Thada\AppData\Roaming\npm\node_modules\pom
elo\node_modules\ws\build\bufferutil.vcxproj]
..\src\bufferutil.cc(80): error C2660: 'v8::True' : function does not take 0 ar
guments [C:\Users\Thada\AppData\Roaming\npm\node_modules\pomelo\node_modules\ws
\build\bufferutil.vcxproj]
..\src\bufferutil.cc(85): error C2248: 'v8::HandleScope::HandleScope' : cannot
access protected member declared in class 'v8::HandleScope' [C:\Users\Thada\App
Data\Roaming\npm\node_modules\pomelo\node_modules\ws\build\bufferutil.vcxproj]
          C:\Users\Thada\.node-gyp\0.12.2\deps\v8\include\v8.h(816) : see decla
  ration of 'v8::HandleScope::HandleScope'
          C:\Users\Thada\.node-gyp\0.12.2\deps\v8\include\v8.h(800) : see decla
  ration of 'v8::HandleScope'
..\src\bufferutil.cc(86): error C2065: 'args' : undeclared identifier [C:\Users
\Thada\AppData\Roaming\npm\node_modules\pomelo\node_modules\ws\build\bufferutil
.vcxproj]
..\src\bufferutil.cc(86): error C2227: left of '->ToObject' must point to class
/struct/union/generic type [C:\Users\Thada\AppData\Roaming\npm\node_modules\pom
elo\node_modules\ws\build\bufferutil.vcxproj]
..\src\bufferutil.cc(87): error C2065: 'args' : undeclared identifier [C:\Users
\Thada\AppData\Roaming\npm\node_modules\pomelo\node_modules\ws\build\bufferutil
.vcxproj]
..\src\bufferutil.cc(87): error C2227: left of '->ToObject' must point to class
/struct/union/generic type [C:\Users\Thada\AppData\Roaming\npm\node_modules\pom
elo\node_modules\ws\build\bufferutil.vcxproj]
..\src\bufferutil.cc(89): error C2065: 'args' : undeclared identifier [C:\Users
\Thada\AppData\Roaming\npm\node_modules\pomelo\node_modules\ws\build\bufferutil
.vcxproj]
..\src\bufferutil.cc(89): error C2227: left of '->ToObject' must point to class
/struct/union/generic type [C:\Users\Thada\AppData\Roaming\npm\node_modules\pom
elo\node_modules\ws\build\bufferutil.vcxproj]
..\src\bufferutil.cc(90): error C2065: 'args' : undeclared identifier [C:\Users
\Thada\AppData\Roaming\npm\node_modules\pomelo\node_modules\ws\build\bufferutil
.vcxproj]
..\src\bufferutil.cc(90): error C2227: left of '->Int32Value' must point to cla
ss/struct/union/generic type [C:\Users\Thada\AppData\Roaming\npm\node_modules\p
omelo\node_modules\ws\build\bufferutil.vcxproj]
..\src\bufferutil.cc(91): error C2065: 'args' : undeclared identifier [C:\Users
\Thada\AppData\Roaming\npm\node_modules\pomelo\node_modules\ws\build\bufferutil
.vcxproj]
..\src\bufferutil.cc(91): error C2227: left of '->Int32Value' must point to cla
ss/struct/union/generic type [C:\Users\Thada\AppData\Roaming\npm\node_modules\p
omelo\node_modules\ws\build\bufferutil.vcxproj]
..\src\bufferutil.cc(105): error C2660: 'v8::True' : function does not take 0 a
rguments [C:\Users\Thada\AppData\Roaming\npm\node_modules\pomelo\node_modules\w
s\build\bufferutil.vcxproj]
..\src\bufferutil.cc(111): error C2248: 'v8::HandleScope::HandleScope' : cannot
 access protected member declared in class 'v8::HandleScope' [C:\Users\Thada\Ap
pData\Roaming\npm\node_modules\pomelo\node_modules\ws\build\bufferutil.vcxproj]
          C:\Users\Thada\.node-gyp\0.12.2\deps\v8\include\v8.h(816) : see decla
  ration of 'v8::HandleScope::HandleScope'
          C:\Users\Thada\.node-gyp\0.12.2\deps\v8\include\v8.h(800) : see decla
  ration of 'v8::HandleScope'
  validation.cc
..\src\validation.cc(116): error C4430: missing type specifier - int assumed. N
ote: C++ does not support default-int [C:\Users\Thada\AppData\Roaming\npm\node_
modules\pomelo\node_modules\ws\build\validation.vcxproj]
..\src\validation.cc(116): error C2143: syntax error : missing ',' before '&' [
C:\Users\Thada\AppData\Roaming\npm\node_modules\pomelo\node_modules\ws\build\va
lidation.vcxproj]
..\src\validation.cc(124): error C4430: missing type specifier - int assumed. N
ote: C++ does not support default-int [C:\Users\Thada\AppData\Roaming\npm\node_
modules\pomelo\node_modules\ws\build\validation.vcxproj]
..\src\validation.cc(124): error C2143: syntax error : missing ',' before '&' [
C:\Users\Thada\AppData\Roaming\npm\node_modules\pomelo\node_modules\ws\build\va
lidation.vcxproj]
..\src\validation.cc(107): error C2248: 'v8::HandleScope::HandleScope' : cannot
 access protected member declared in class 'v8::HandleScope' [C:\Users\Thada\Ap
pData\Roaming\npm\node_modules\pomelo\node_modules\ws\build\validation.vcxproj]
          C:\Users\Thada\.node-gyp\0.12.2\deps\v8\include\v8.h(816) : see decla
  ration of 'v8::HandleScope::HandleScope'
          C:\Users\Thada\.node-gyp\0.12.2\deps\v8\include\v8.h(800) : see decla
  ration of 'v8::HandleScope'
..\src\validation.cc(108): error C2664: 'v8::FunctionTemplate::New' : cannot co
nvert parameter 1 from 'v8::Handle<T> (__cdecl *)(const int)' to 'v8::Isolate *
' [C:\Users\Thada\AppData\Roaming\npm\node_modules\pomelo\node_modules\ws\build
\validation.vcxproj]
          with
          [
              T=v8::Value
          ]
          There is no context in which this conversion is possible
..\src\validation.cc(110): error C2664: 'node::NODE_SET_METHOD' : cannot conver
t parameter 3 from 'v8::Handle<T> (__cdecl *)(const int)' to 'v8::FunctionCallb
ack' [C:\Users\Thada\AppData\Roaming\npm\node_modules\pomelo\node_modules\ws\bu
ild\validation.vcxproj]
          with
          [
              T=v8::Value
          ]
          Incompatible calling conventions for UDT return value
..\src\validation.cc(111): error C2039: 'NewSymbol' : is not a member of 'v8::S
tring' [C:\Users\Thada\AppData\Roaming\npm\node_modules\pomelo\node_modules\ws\
build\validation.vcxproj]
          C:\Users\Thada\.node-gyp\0.12.2\deps\v8\include\v8.h(1599) : see decl
  aration of 'v8::String'
..\src\validation.cc(111): error C3861: 'NewSymbol': identifier not found [C:\U
sers\Thada\AppData\Roaming\npm\node_modules\pomelo\node_modules\ws\build\valida
tion.vcxproj]
..\src\validation.cc(118): error C2248: 'v8::HandleScope::HandleScope' : cannot
 access protected member declared in class 'v8::HandleScope' [C:\Users\Thada\Ap
pData\Roaming\npm\node_modules\pomelo\node_modules\ws\build\validation.vcxproj]
          C:\Users\Thada\.node-gyp\0.12.2\deps\v8\include\v8.h(816) : see decla
  ration of 'v8::HandleScope::HandleScope'
          C:\Users\Thada\.node-gyp\0.12.2\deps\v8\include\v8.h(800) : see decla
  ration of 'v8::HandleScope'
..\src\validation.cc(120): error C2065: 'args' : undeclared identifier [C:\User
s\Thada\AppData\Roaming\npm\node_modules\pomelo\node_modules\ws\build\validatio
n.vcxproj]
..\src\validation.cc(120): error C2228: left of '.This' must have class/struct/
union [C:\Users\Thada\AppData\Roaming\npm\node_modules\pomelo\node_modules\ws\b
uild\validation.vcxproj]
          type is ''unknown-type''
..\src\validation.cc(121): error C2065: 'args' : undeclared identifier [C:\User
s\Thada\AppData\Roaming\npm\node_modules\pomelo\node_modules\ws\build\validatio
n.vcxproj]
..\src\validation.cc(121): error C2228: left of '.This' must have class/struct/
union [C:\Users\Thada\AppData\Roaming\npm\node_modules\pomelo\node_modules\ws\b
uild\validation.vcxproj]
          type is ''unknown-type''
..\src\validation.cc(126): error C2248: 'v8::HandleScope::HandleScope' : cannot
 access protected member declared in class 'v8::HandleScope' [C:\Users\Thada\Ap
pData\Roaming\npm\node_modules\pomelo\node_modules\ws\build\validation.vcxproj]
          C:\Users\Thada\.node-gyp\0.12.2\deps\v8\include\v8.h(816) : see decla
  ration of 'v8::HandleScope::HandleScope'
          C:\Users\Thada\.node-gyp\0.12.2\deps\v8\include\v8.h(800) : see decla
  ration of 'v8::HandleScope'
..\src\validation.cc(127): error C2065: 'args' : undeclared identifier [C:\User
s\Thada\AppData\Roaming\npm\node_modules\pomelo\node_modules\ws\build\validatio
n.vcxproj]
..\src\validation.cc(128): error C2039: 'New' : is not a member of 'v8::String'
 [C:\Users\Thada\AppData\Roaming\npm\node_modules\pomelo\node_modules\ws\build\
validation.vcxproj]
          C:\Users\Thada\.node-gyp\0.12.2\deps\v8\include\v8.h(1599) : see decl
  aration of 'v8::String'
..\src\validation.cc(128): error C2664: 'Validation::New' : cannot convert para
meter 1 from 'const char [36]' to 'const int' [C:\Users\Thada\AppData\Roaming\n
pm\node_modules\pomelo\node_modules\ws\build\validation.vcxproj]
          There is no context in which this conversion is possible
..\src\validation.cc(128): error C3861: 'ThrowException': identifier not found
[C:\Users\Thada\AppData\Roaming\npm\node_modules\pomelo\node_modules\ws\build\v
alidation.vcxproj]
..\src\validation.cc(130): error C2065: 'args' : undeclared identifier [C:\User
s\Thada\AppData\Roaming\npm\node_modules\pomelo\node_modules\ws\build\validatio
n.vcxproj]
..\src\validation.cc(130): error C2227: left of '->ToObject' must point to clas
s/struct/union/generic type [C:\Users\Thada\AppData\Roaming\npm\node_modules\po
melo\node_modules\ws\build\validation.vcxproj]
..\src\validation.cc(133): error C2039: 'Close' : is not a member of 'v8::Handl
eScope' [C:\Users\Thada\AppData\Roaming\npm\node_modules\pomelo\node_modules\ws
\build\validation.vcxproj]
          C:\Users\Thada\.node-gyp\0.12.2\deps\v8\include\v8.h(800) : see decla
  ration of 'v8::HandleScope'
..\src\validation.cc(133): error C2660: 'v8::True' : function does not take 0 a
rguments [C:\Users\Thada\AppData\Roaming\npm\node_modules\pomelo\node_modules\w
s\build\validation.vcxproj]
..\src\validation.cc(133): error C2039: 'Close' : is not a member of 'v8::Handl
eScope' [C:\Users\Thada\AppData\Roaming\npm\node_modules\pomelo\node_modules\ws
\build\validation.vcxproj]
          C:\Users\Thada\.node-gyp\0.12.2\deps\v8\include\v8.h(800) : see decla
  ration of 'v8::HandleScope'
..\src\validation.cc(133): error C2660: 'v8::False' : function does not take 0
arguments [C:\Users\Thada\AppData\Roaming\npm\node_modules\pomelo\node_modules\
ws\build\validation.vcxproj]
..\src\validation.cc(139): error C2248: 'v8::HandleScope::HandleScope' : cannot
 access protected member declared in class 'v8::HandleScope' [C:\Users\Thada\Ap
pData\Roaming\npm\node_modules\pomelo\node_modules\ws\build\validation.vcxproj]
          C:\Users\Thada\.node-gyp\0.12.2\deps\v8\include\v8.h(816) : see decla
  ration of 'v8::HandleScope::HandleScope'
          C:\Users\Thada\.node-gyp\0.12.2\deps\v8\include\v8.h(800) : see decla
  ration of 'v8::HandleScope'

> heapdump@0.2.9 install C:\Users\Thada\AppData\Roaming\npm\node_modules\pomelo\
node_modules\pomelo-admin\node_modules\heapdump
> node-gyp rebuild

C:\Users\Thada\AppData\Roaming\npm\node_modules\pomelo\node_modules\pomelo-admin
\node_modules\heapdump>if not defined npm_config_node_gyp (node "C:\Program File
s\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node
-gyp.js" rebuild )  else (rebuild)
Building the projects in this solution one at a time. To enable parallel build,
please add the "/m" switch.
  heapdump.cc
  platform-win32.cc
LINK : fatal error LNK1181: cannot open input file 'kernel32.lib' [C:\Users\Tha
da\AppData\Roaming\npm\node_modules\pomelo\node_modules\pomelo-admin\node_modul
es\heapdump\build\heapdump.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe
` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\
npm\node_modules\node-gyp\lib\build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074
:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "node" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modu
les\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\Thada\AppData\Roaming\npm\node_modules\pomelo\node_modules
\pomelo-admin\node_modules\heapdump
gyp ERR! node -v v0.12.2
gyp ERR! node-gyp -v v1.0.3
gyp ERR! not ok
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs
\\node_modules\\npm\\bin\\npm-cli.js" "install" "pomelo" "-g"
npm ERR! node v0.12.2
npm ERR! npm  v2.7.4
npm ERR! code ELIFECYCLE

npm ERR! heapdump@0.2.9 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the heapdump@0.2.9 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the heapdump package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls heapdump
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Windows\system32\npm-debug.log

**Comment by letiennam29** [comment]
you try again:

cd C:\Users\Thada
npm cache clear
npm install pomelo -g

**Comment by fantasyni** [comment]
try to use nodejs@0.10.x version

**Comment by foolmath** [comment]
try to use Mac or Linux

**Comment by psxcode** [comment]
Solved this. The reason is v8.h changed API.
Pomelo compiles on NodeJS v0.10.25.
Install old version.

**Comment by cynron** [comment]
V8‘s API changed crazily
