### ISSUE TITLE
session在哪些情况下会触发closed？

### ISSUE THREAD

**Issue by xFaris** [NetEase/pomelo#725]
session在哪些情况下会触发closed？

**Comment by AliTiger** [comment]
顶一下 我也遇到这个问题了, 正在看源码

**Comment by ganziganzi** [comment]
遇到同样的问题，有什么结果吗？有些安卓客户端一登录上ws发送点协议 就掉线

**Comment by py8765** [comment]
主要是底层连接有断开才会close，可以先抓包看看是哪端断开的

**Comment by ganziganzi** [comment]
打印出了 close reason：
reason 'no handler for opcode 4'
在mobile 客户端上短时间狂发大量协议时，导致服务端断开该session,并提示以上reason。
这似乎是客户端错发了数据？

如果用web端狂发就没问题。
如果只是发少量，mobile 也没问题。
