### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by Azunyan-** [NetEase/pomelo#727]
Here's a paste from my cmd  that I ran as admin http://p.pomf.se/7674
And here's my npm-debug.log http://a.pomf.se/vrigwf.log

I don't know if it's because of registry errors or not I can't really decipher the errors >.<

**Comment by impcyber** [comment]
Maybe this https://helgeklein.com/blog/2010/01/visual-studio-fixing-broken-windowssdkdir-variable/ may help?

**Comment by Azunyan-** [comment]
I checked the registry and it was looked just like it was supposed to be according to the link. Spooky O.o

![image1](https://cloud.githubusercontent.com/assets/9107607/7846069/8c9451e6-04bb-11e5-8698-e6e0a42171b6.PNG)
![image2](https://cloud.githubusercontent.com/assets/9107607/7846074/92699982-04bb-11e5-85f6-b0c6426e38ad.PNG)

**Comment by impcyber** [comment]
All of the prerequisites are done from here before install pomelo: https://github.com/NetEase/pomelo/wiki/Installation#prerequisites ?
