### ISSUE TITLE
Chat Demo on Azure VM stuck on login screen only

### ISSUE THREAD

**Issue by anandreddyks** [NetEase/pomelo#732]
I have installed pomelo Chat App on Azure VM.
I can only see the login screen and its not taking me into the chat section once I click the login button.
I have opened all the ports in the "Endpoints" section. But I still face the same issue.

But I'm able to see the data I have entered in login screen inside the log file generated at the backend. 

![screen shot 2015-06-14 at 4 26 59 pm](https://cloud.githubusercontent.com/assets/6284338/8148261/3986b214-12b2-11e5-86c9-9434e3abde09.png)

I have attached the screenshots of my opened ports + Servers.json file.

![screen shot 2015-06-14 at 4 26 14 pm](https://cloud.githubusercontent.com/assets/6284338/8148262/6a2edfd6-12b2-11e5-95ff-814769affc7f.png)

![screen shot 2015-06-14 at 4 30 39 pm](https://cloud.githubusercontent.com/assets/6284338/8148265/b889289e-12b2-11e5-9190-1112cad8b90f.png)

**Comment by anandreddyks** [comment]
I forgot to add the client error.
Here is the error I'm getting in the browser.
I have also tried to remove the "heartbeat:3" in game-server/app.js file but still I have the same issue. 

![screen shot 2015-06-14 at 4 32 52 pm](https://cloud.githubusercontent.com/assets/6284338/8148277/19311616-12b3-11e5-86ad-68d3944e0a69.png)

**Comment by cynron** [comment]
Please change `127.0.0.1` to its public ip or the domain name, and then try it again.

**Comment by anandreddyks** [comment]
I have tried  that and still its the same issue

**Comment by liusida** [comment]
U can change all 127.0.0.1 to Real IP Address, then paste the browser error
