### ISSUE TITLE
WSS connection is taking more than 30 sec to connect

### ISSUE THREAD

**Issue by amrendraw3** [NetEase/pomelo#735]
I was using WS connection  with sioconnector which was working great but when i switched to WSS with same sioconnector configuration then it it taking more than 30 sec to connection with client (while disconnecting from gate server and connecting to connector servers). In WS connection the connection time is near about 6 or 7 sec only.

Previous app configuration (WS with sioconnector):

app.configure('production|development', 'connector', function(){
app.set('connectorConfig',
{
connector : pomelo.connectors.sioconnector,
transports : ['websocket'],
heartbeats : true,
closeTimeout : 60,
heartbeatTimeout : 60,
heartbeatInterval : 25
});
});

New app configuration (WSS with sioconnector):

app.configure('production|development', 'connector', function(){
app.set('connectorConfig',
{
connector : pomelo.connectors.sioconnector,
connector: pomelo.connectors.sioconnector,
key: fs.readFileSync('../shared/server.key'),
cert: fs.readFileSync('../shared/server.crt')
});
});

In the client side only change is made that we switched ws:// to wss:// (or http:// to https://)

**Comment by cynron** [comment]
could you use `tcpdump` or `wireshark` to capture some packets for analyzing?
