### ISSUE TITLE
单服掉线、立刻重启之后，removeServer 和 addServer的时序有误，导致重启的服务器无法工作

### ISSUE THREAD

**Issue by ranbochen** [NetEase/pomelo#736]
大致日志：
掉线服立刻重启：
masterwatcher.js] masterwatcher receive add server event XXXX id: server-1

等一段时间watcher超时后，会发送老的removeServer事件（由于id相同导致新服务器被踢掉）
monitorwatcher.js]  xxx receive removeServer XXXX : id server-1 

remove之后的rpc日志
pomelo-rpc\lib\rpc-client\mailstation.js] [pomelo-rpc] server is not online: server-1
可见重新连上的服务器被踢掉了

重现方式：
启动，然后结束某个服务器，立即用命令行重启这个服务器

**Comment by jesonxie** [comment]
我也碰到这样的问题，楼主有解决方法么
