### ISSUE TITLE
Is it possible to add same username to a channel at the same time? 

### ISSUE THREAD

**Issue by yoxisem544** [NetEase/pomelo#738]
Is it possible to add same username to a channel at the same time? 

I want to let user login on multiple device at the same time.
This part of code in sample code will throw error and stop me from logging in with same username.

Does anyone ever encounter this kind of problem?

我想要在不同的裝置上，同時登入。
以下這段程式碼是在samplecode裡面的一段，這段會阻止我使用一樣的使用者名稱重複登入。

有人遇過這樣的問題嗎？
```js
//query entry of connection
		queryEntry(username, function(host, port) {
			pomelo.init({
				host: host,
				port: port,
				log: true
			}, function() {
				var route = "connector.entryHandler.enter";
				pomelo.request(route, {
					username: username,
					rid: rid
				}, function(data) {
					if(data.error) {
						showError(DUPLICATE_ERROR);
						console.log(data.error);
						return;
					}
					setName();
					setRoom();
					showChat();
					initUserList(data);
				});
			});
		});
```

**Comment by yoxisem544** [comment]
sorry about the indention.....

**Comment by wuxian** [comment]
至少游戏上这样做在逻辑上不允许，试想，同时登入的两个用户，用户1修改的部分数据保存后，一定会被用户2覆盖

**Comment by yoxisem544** [comment]
是的沒錯，
我自己是想要做一般的聊天，
可以讓一個用戶同時在多個設備上登入。

我現在應該會在 username 後面加一些東西
譬如123456-web, 123456-iOS
來區分設備

我自己想了一下同時有一樣的username並且得到觸發自己的事件也是有點奇怪的事。

**Comment by wuxian** [comment]
可以的，用户名可以用一样的，如果是聊天应用，POMELO有特别做了处理，CONNECTOR里面可以同一个用户，sessionService里面有个开关singleSession可以用来开启这一项

**Comment by yoxisem544** [comment]
好的！

**Comment by yoxisem544** [comment]
@wuxian 
可以請問是否有相關說明的連結？
或者一段代碼參考呢？
