### ISSUE TITLE
How to get all BackendSession By uid or key push?

### ISSUE THREAD

**Issue by letiennam29** [NetEase/pomelo#742]
I have read doc in page api pomelo:
- this is link http://pomelo.netease.com/api.html

And I have found how get BackendSession by sid or getByUid. But not  how get many BackendSession  by uid or key. I need get all BackendSession By uid or key push.

This is get one BackendSession by sid or getByUid:
# 

BackendSessionService.prototype.get = function(frontendId, sid, cb) {
  var namespace = 'sys';
  var service = 'sessionRemote';
  var method = 'getBackendSessionBySid';
  var args = [sid];
  rpcInvoke(this.app, frontendId, namespace, service, method,
            args, BackendSessionCB.bind(null, this, cb));
};
# 

BackendSessionService.prototype.get = function(frontendId, sid, cb) {
  var namespace = 'sys';
  var service = 'sessionRemote';
  var method = 'getBackendSessionBySid';
  var args = [sid];
  rpcInvoke(this.app, frontendId, namespace, service, method,
            args, BackendSessionCB.bind(null, this, cb));
};

Can any one tell me how how get BackendSession?

**Comment by py8765** [comment]
The backend session just acts as the agent for frontend session, you can get all frontend session use the backendSessionService with server ids and session ids; there is no method can get all backend sessions.

**Comment by letiennam29** [comment]
I had understand how its work!

@py8765 tks u!
