### ISSUE TITLE
同一客户端多次登录后，会收到重复推送的消息

### ISSUE THREAD

**Issue by yuzhaoshi** [NetEase/pomelo#745]
问题如下：
我在chatofpomelo的基础上修改，对connector的entryHandler的enter方法，从原来同一uid不能登录，改成kick掉旧的session，再把新的session绑定上uid。如下：

var sessionService = self.app.get('sessionService');
    if (!!sessionService.getByUid(uid)) {
        sessionService.kick(uid, function (err, result) {
            console.debug('some other is kicked' );
            if (err == null) {
                code = CODES.CONNECT.KickOldSessionSuccess;
            } else {
                console.error('kick failed : %j', err);
                code = CODES.CONNECT.KickOldSessionFailed;
                next(err, {
                    code: code,
                    error: true
                });
                return;
            }
        });
    }

修改后，浏览器打开三个标签页（A、B、C），用两个uid（u1、u2）测试。
A用u1登录后，B再用u1登录成功，此时A触发“WebSocket is already in CLOSING or CLOSED state.”和“server heartbeat timeout”。C用u2登录后，向u1发送消息，B收到消息，A没反应。一切正常。
然后，B再用u1登录一次，查看服务器的debug，有执行kick操作，但没有触发“WebSocket is already in CLOSING or CLOSED state.”和“server heartbeat timeout”。用C向u1发送消息，此时B收到了两条相同的消息。

总结一下：这个问题就是同一个客户端，在没有断开服务器的情况下，再次登录，kick方法没有生效，客户端会被推送两次消息。

PS：
我觉得原因可能是这两个：
1、同一个uid绑定了多个session，而这多个session都是指向同一个客户端的，所以同一个客户端收到多条推送消息。
2、session只有一个，但是channel中重复add了。因为每次登录都有执行以下代码：
self.app.rpc.chat.chatRemote.add(session, uid, self.app.get('serverId'), rid, true, function (users) {
        next(null, {
            users: users
        });
    });

麻烦大神帮帮忙，谢谢！

**Comment by yuzhaoshi** [comment]
补充一下：
我跟踪到ChatRemote里面，发现channel是正常触发了onLeave方法的。就是说之前怀疑channel中多次绑定session是错的。
然后我再跟踪到pomelo的框架代码里面，查看了channelService和channelRemote里面被调用的方法，发现也没有被调用多次。
再看回客户端，与正常情况下（标签页B踢掉标签页A的情况）相比，标签页A自己重复登录的时候，没有触发“WebSocket is already in CLOSING or CLOSED state.”。因此，我想，是不是同一标签页多次登录的时候，虽然socket断开了，旧的session被踢掉了，但是websocket没有断掉，在多次登录的情况下，建立了多个websocket，都对应新的session，因此收到多条信息。
麻烦大神帮帮忙，谢谢！

**Comment by smilence86** [comment]
解决方案：修改channelService.js，在430行添加
    var g_l = {};
    var groupList = [];
    for(var i in groups[sid]){
        if(g_l[group[i]]){
            continue;
        }
        groupList.push(group[i]);
        g_l[group[i]] =1;
    }
    if(sid === app.serverId) {
        channelService.channelRemote[method](route, msg, groupList, opts, rpcCB(sid));
    } else {
        app.rpcInvoke(sid, {namespace: namespace, service: service,
        method: method, args: [route, msg, groupList, opts]}, rpcCB(sid));
    }
