### ISSUE TITLE
Pomelo Client not working when using domain name and ssl

### ISSUE THREAD

**Issue by letiennam29** [NetEase/pomelo#746]
Hi everybody,

I try connect client in web and unity client:
when i changed host from ip to domain name it not working, this is the result i get:
# 

============working==============
pomelo.init({
  host: "127.0.0.1",
  port: 4014,
  log: true
}, callback {});
# 

===========not working=============
pomelo.init({
  host: "mydomaincom", // or http://mydomain.com | https://mydomain.com
  port: 4014,
  log: true
}, callback {});
# 

I try changed config server, but not ok, this is code changed:
  app.set('connectorConfig', {
      //connector : pomelo.connectors.hybridconnector,
      connector : pomelo.connectors.sioconnector,
      transports : ['websocket'],
      useProtobuf : true
  });

who can help my problem? thanks you!

**Comment by Vvkgaming** [comment]
**https://github.com/NetEase/pomelo/wiki/Understanding-connector**

Hybridconnector supports tcp and websocket while sioconnector supports socket.io. But in practice, we may need to customize our own connector to meet special demands, pomelo provides the interface to customize connector.


this may be helpful
