### ISSUE TITLE
Installation problems

### ISSUE THREAD

**Issue by anders-akero** [NetEase/pomelo#748]
I can't install pomelo for some reason.
I can not even get pass running the following command "sudo npm install pomelo -g"

The following is the error message I get:
> heapdump@0.2.9 install /usr/local/lib/node_modules/pomelo/node_modules/pomelo-admin/node_modules/heapdump
> node-gyp rebuild
gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/0.12.0"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/local/lib/node_modules/pomelo/node_modules/pomelo-admin/node_modules/heapdump/.node-gyp"
gyp WARN install got an error, rolling back install
gyp WARN install got an error, rolling back install
gyp ERR! configure error
gyp ERR! stack Error: node-v0.12.0.tar.gz local checksum 2731700bced877412a50a1542f903cfb1dcd49c263aa1db4bf7ff0ddea07ba14 not match remote 9700e23af4e9b3643af48cef5f2ad20a1331ff531a12154eef2bfb0bb1682e32
gyp ERR! stack     at deref (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/install.js:299:20)
gyp ERR! stack     at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/install.js:340:13)
gyp ERR! stack     at IncomingMessage.emit (events.js:129:20)
gyp ERR! stack     at _stream_readable.js:908:16
gyp ERR! stack     at process._tickCallback (node.js:355:11)
gyp ERR! System Linux 3.18.14+
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/pomelo/node_modules/pomelo-admin/node_modules/heapdump
gyp ERR! node -v v0.12.0
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok
> ws@0.4.25 install /usr/local/lib/node_modules/pomelo/node_modules/ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)
make: Entering directory '/usr/local/lib/node_modules/pomelo/node_modules/ws/build'
  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
bufferutil.target.mk:83: recipe for target 'Release/obj.target/bufferutil/src/bufferutil.o' failed
make: Leaving directory '/usr/local/lib/node_modules/pomelo/node_modules/ws/build'
npm ERR! Linux 3.18.14+
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "pomelo" "-g"
npm ERR! node v0.12.0
npm ERR! npm  v2.5.1
npm ERR! code ELIFECYCLE
npm ERR! heapdump@0.2.9 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the heapdump@0.2.9 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the heapdump package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls heapdump
npm ERR! There is likely additional logging output above.
npm ERR! Please include the following file with any support request:
npm ERR!     /home/pi/nodejs/npm-debug.log

And home/pi/nodejs/npm-debug-log contains:
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'install',
1 verbose cli   'pomelo',
1 verbose cli   '-g' ]
2 info using npm@2.5.1
3 info using node@v0.12.0
4 silly cache add args [ 'pomelo', null ]
5 verbose cache add spec pomelo
6 silly cache add parsed spec { raw: 'pomelo',
6 silly cache add   scope: null,
6 silly cache add   name: 'pomelo',
6 silly cache add   rawSpec: '',
6 silly cache add   spec: '*',
6 silly cache add   type: 'range' }
7 verbose addNamed pomelo@*
8 silly addNamed semver.valid null
9 silly addNamed semver.validRange *
10 silly addNameRange { name: 'pomelo', range: '*', hasData: false }
11 silly mapToRegistry name pomelo
12 silly mapToRegistry using default registry
13 silly mapToRegistry registry https://registry.npmjs.org/
14 silly mapToRegistry uri https://registry.npmjs.org/pomelo
15 verbose addNameRange registry:https://registry.npmjs.org/pomelo not in flight; fetching
16 verbose request uri https://registry.npmjs.org/pomelo
17 verbose request no auth needed
18 info attempt registry request try #1 at 18:44:00
19 verbose request id 0aecf5119aa78867
20 verbose etag "9JSFDUEFUFHCA5J4ZONIDYIW6"
21 http request GET https://registry.npmjs.org/pomelo
22 http 304 https://registry.npmjs.org/pomelo
23 silly get cb [ 304,

I have tried to understand the problem for a few hours now and I can not understand.
Running on a raspberryPI Ubuntu

**Comment by psxcode** [comment]
first line
gyp WARN EACCES user "root" does not have permission to access the dev dir
Are you sure you're runing command with enough permissions granted.
You should run: sudo npm install -g pomelo

**Comment by anders-akero** [comment]
Yes.
As written the exact command I am trying is: "sudo npm install pomelo -g".
I even changed user of the entire root-folder (dangerous I know, but I'm out of ideas).
What is confusing me is that there is no folder called "/root/.node-gyp/0.12.0".

**Comment by psxcode** [comment]
OK. I struggled pomelo installation on Windows for couple of days, but for Ubuntu it was no problem.
Ubuntu:
1.apt-get build-essential. (C++ compiler)
2.apt-get nodejs (Ubuntu auto installed v0.10.25)
3.apt-get npm
4.apt-get node-gyp (used by pomelo as command line c++ builder, based on python scripts)
Python was already installed (should be v 2.7.*)

now sudo npm install -g pomelo
And it goes OK. Note version of NodeJS(0.10.25) Pomelo compiles its internal parts with this version of nodeJS. (When I tried last v0.12.7 - compilation failed because of API changes in V8.h).

The folder .node-gyp/*** is created automatically(!!) when pomelo builds himself by node-gyp.
Node-gyp downloads sources and dependencies(for your version of Node) before build into that folder.
So looking at your error, node-gyp cannot create that folder.
People says this is issue with node-gyp. maybe try different version. Mine is v0.12.2

**Comment by anders-akero** [comment]
I will try using nodeJS version  0.10 then.
I have been trying with version 0.12.

**Comment by psxcode** [comment]
as I can see from your error, you have not reached build phase, where nodejs version matters.
For now try different version of node-gyp.

**Comment by anders-akero** [comment]
Thank you, it helped with reinstalling node-gyp.
