### ISSUE TITLE
目前为止，Pomelo版本最新是Version:1.1.9，Node.js.Version:0.12.7

### ISSUE THREAD

**Issue by zhu603809832** [NetEase/pomelo#752]
但是Pomelo文档里面没有告诉该使用哪些Node.js版本，我是尝试了Node.js的0.12.x，0.10.x，0.8.x系列版本，使用VS2013编译安装，在部署lordofpomelo，treasures这两个游戏的时候都是失败，0.10.x可以正常编译通过，但是运行异常。只有chat of pomelo 可使用。希望哪位可以指点一下该使用node.js版本，环境相关准备。

**Comment by ChrisPei** [comment]
npm config set registry https://registry.npm.taobao.org

试试将npm源映射到国内淘宝镜像，nodejs用最新版本应该没问题，安装失败普遍是国外源超时问题。

**Comment by zhu603809832** [comment]
@ChrisPei 感谢！应该不是npm源的问题。我用以下的版本可以运行lordofpomelo了。
Linux部署成功
	1. node.js version 0.10.40
	2. npm version 1.4.28
	3. pomelo version 1.1.9
	4. gcc version 4.4.7
