### ISSUE TITLE
Pomelo memory leak problem !

### ISSUE THREAD

**Issue by saruno** [NetEase/pomelo#754]
Hi Pomelo team,

I develop a real time MMO game with pomelo use Socket.io connector. When I test with many client, I saw that pomelo memory will grow to much. When i disconnect all client, memory not decrease.

My question:
Is that a case of memory leak and how to fix this problem ?
How to custom run gc memory in pomelo.

Thanks !

**Comment by py8765** [comment]
give some detailed data
