### ISSUE TITLE
pushMessageByUids msg content is an array, session will be closed after 10 seconds.

### ISSUE THREAD

**Issue by AliTiger** [NetEase/pomelo#755]
pushMessageByUids
消息内容如果是单个数组:
var msgContent = [1,2,3,,,,,];
var uids = [{uid : 1, sid : 'connector-server-1'},,,,,];
channelService.pushMessageByUids('route', msgContent , uids);

会导致session close , Unity3D客户端断线.

**Comment by lichungod** [comment]
用json为好
