### ISSUE TITLE
Pomelo的GameServer和其他服务器断开连接，在压力测试（约200 requests/s）时

### ISSUE THREAD

**Issue by xianwen** [NetEase/pomelo#756]
MacOS上

"ps -a | grep node"
可以看到game-server的进程还在

但是"pomelo list"，可以看到服务器列表里面，game-server消失了。导致的结果，是客户端发送的所有请求，都直接返回一个空消息：

[DEBUG] pomelo - [Projects/wiss/node_modules/pomelo/lib/components/connector.js] [connector-server-1] handleMessage session id: 5, msg: {"id":2,"type":0,"compressRoute":1,"route":"connector.entryHandler.createRoom","body":{"room_id":"test_room","mode":0,"players_count":4}}
[DEBUG] pomelo - [Projects/wiss/node_modules/pomelo/lib/components/connector.js] [connector-server-1] send message reqId: 2, route: connector.entryHandler.createRoom, msg: {}, receivers: [5], opts: {"type":"response","userOptions":{},"isResponse":true}

通过"pomelo add host=127.0.0.1 port=3240 serverType=game id=game-server-1"手动添加一个新的game server，可以自动连接成功，然后客户端就可以正常运行了。

**Comment by xianwen** [comment]
在crash.log，只能看到disconnected:
 [INFO] crash-log - [Projects/wiss/node_modules/pomelo/lib/master/master.js] [game],[game-server-1],[1443085163399],[disconnect]

在game-server的log中，只能看到最后一条正常发送的消息，也没有任何的错误输出
[DEBUG] pomelo - [Projects/wiss/node_modules/pomelo/lib/common/service/channelService.js] ^[[39m[game-server-1] channelService     sendMessageByGroup route: onPlayerVote, msg: {"player":"a2","voted_player":"a"}, groups: {"connector-server-1":["a","a1","a2","a3"]}, opts: null

**请教：
如何分析，调试，解决这个问题？谢谢！**

**Comment by xianwen** [comment]
$pomelo -V
1.1.1
$ node -v
v0.10.29

**Comment by xianwen** [comment]
刚刚下载了最新的pomelo 1.2.0, 问题依然存在，表现完全相同

**Comment by hikaru7641** [comment]
1. you push code:

**Comment by xianwen** [comment]
已解决，是我自己的问题，写了个死循环……鄙视自己……
