### ISSUE TITLE
请问一下pomelo 支持的最新的node版本是多少？

### ISSUE THREAD

**Issue by blueseason** [NetEase/pomelo#758]
如题， 谢谢

**Comment by xianwen** [comment]
我是用的0.10.29，似乎没有问题，反正压力测试啥的一切正常

**Comment by Lellansin** [comment]
4.x 用不了

**Comment by py8765** [comment]
4.x 应该是有些依赖库支持有问题

**Comment by blueseason** [comment]
@py8765 有考虑什么时间节点支持4.x吗

**Comment by jipan25** [comment]
我用4.0.x 可以啊，pomelo1.2.0做了兼容修改

**Comment by Lellansin** [comment]
@jipan25  了解~

**Comment by iamchenxin** [comment]
1.2 版本的pomelo 可以在当前的 4.2.1 下面运行.
不知道网易什么时候公开 pomelo 2.x 的文档

**Comment by yaoyinbear** [comment]
win7 x64下，1.2 版本的pomelo 在4.2.1的node下 直接安装编译出错
..\src\bufferutil.cc(36): error C4430: missing type specifier - int assumed. Note: C++ does not su pport default-int [C:\Users\YaoYin\AppData\Roaming\npm\node_modules\pomelo\node_modules\ws\build\b ufferutil.vcxproj]

**Comment by 359056163** [comment]
@yaoyinbear  建议你 安装32位的nodejs版本,在windows上。64位的nodejs，安装 pomelo 会出错

**Comment by yaoyinbear** [comment]
@359056163 没用，vs2013 + node-v4.2.1-x86 + python 2.7.6 x86 + pomelo 4.2.1 还是安装编译报错
..\src\bufferutil.cc(36): error C4430: missing type specifier - int assumed. Note: C++ does not su pport default-int [C:\Users\YaoYin\AppData\Roaming\npm\node_modules\pomelo\node_modules\ws\build\b ufferutil.vcxproj]

..\src\bufferutil.cc(25): error C2248: 'v8::HandleScope::HandleScope' : cannot access protected me mber declared in class 'v8::HandleScope' [C:\Users\YaoYin\AppData\Roaming\npm\node_modules\pomelo\ node_modules\ws\build\bufferutil.vcxproj]

**Comment by yaoyinbear** [comment]
Python 2.7.6 x86
VS2013 CE
Node.js 0.12.7 x86
pomelo 1.2.0 + ws升级到0.8.0
Win7 x64 
安装成功
