### ISSUE TITLE
聊天室例子是否会出现不同connector存在 相同房间ID的情况？

### ISSUE THREAD

**Issue by qq297110281** [NetEase/pomelo#762]
最近在研究pomelo，官方聊天室例子很不错，但是我在看代码的时候有一点疑问：现在如果进行分布式部署，用户可能会被链接到不同的 connector，那么不同的connector是否会出现能创建相同房间ID的情况呢？我是在研究怎样获取整个服务的 实时 的房间列表的时候 产生这个疑问，不知各位大神能否指点一下？

**Comment by py8765** [comment]
全局的这种东西就自己搞redis数据库存吧
