### ISSUE TITLE
谁知道网易何时会发布 pomelo 2.x 的文档吗?

### ISSUE THREAD

**Issue by iamchenxin** [NetEase/pomelo#764]
透露,透露 ~
有了 2.x 再用 1.2 简直是心痒难耐.

**Comment by stableShip** [comment]
话说,2.x去哪里试用???

**Comment by IssicLzx** [comment]
同求啊 哪有2.x

**Comment by pipi32167** [comment]
有2.x的分支啊，clone下来直接checkout到2.x分支就可以了啊

**Comment by pipi32167** [comment]
不过我不确定楼主是用的这个么？

**Comment by iamchenxin** [comment]
是啊, 2.x 分支,没敢用,看了一下,变化不小,要是有公开的文档就好了.
不过我似乎搞错了一个事情,开始以为 libpomelo2 对应 pomelo的 2.x 分支,似乎不是,只是命名混乱了 .
我先去试用一下libpomelo2 .

**Comment by py8765** [comment]
首先确认一下 libpomelo2不是对应pomelo2.x，另外pomelo 2.x还在更新中，请大家耐心等待，2.0版本发布之后，1.0版本还是会继续维护。

**Comment by iamchenxin** [comment]
@py8765 感谢,pomelo 2.x 有大致的发行时间表吗

**Comment by py8765** [comment]
pomelo 2.x保守估计预发布 11月中上旬吧

**Comment by shanegxxiao** [comment]
有什么变更吗?刚开始的项目是要用1.x好还是2.x好呢?

**Comment by py8765** [comment]
刚开始的项目建议还是先用1.2.0，2.x的变化后面出一份文档介绍

**Comment by iamchenxin** [comment]
感谢

**Comment by iamchenxin** [comment]
@py8765 刚才仔细试了一下 libpomelo2 , 请问其中的 C# 客户端现在是否处于不工作状态 .<br/>
因为直接编译后并不能使用,在修改了一些代码能够启动以后,发现 C#插件 request 的实现并没有对服务器 返回的状态(host,port)解码,但这应该不是预设的状态, 因为 初步完成的测试,应该需要测试一下对返回的connector(host,port)进行连接, 因此推断, cspomelo 可能并没有实际使用过.
![out](https://cloud.githubusercontent.com/assets/8873545/10702660/b8cea6d2-79fd-11e5-96ad-d492b9813694.jpg)
但有可能是我理解错误了, 我是按之前使用的 老的纯cs的 C#客户端插件的已有行为来推断的行为.

... 再次提出要求有点不好意思,希望之后正式发布的时候能够提供 一份 libpomelo2 c实现的函数的行为说明. 我的理解是目前的 libpomelo2 是为了统一各个不同语言的客户端实现 至插件形式使用同一份代码.<br/>
如果有 libpomelo2  c实现 的说明,类似我这样项目后来的使用者能比较快速的理解项目,然后可以避免,老是疑神疑鬼自己在瞎改代码的情况 .

**Comment by sjfkai** [comment]
已经一月了，2.x发行有什么进展了吗? @py8765

**Comment by llqgithub** [comment]
@py8765 亲，2.x 有进展了吗？我们期待ing 啊。是不是会支持 socket.io 1.x 呀？
现在看来，是很“不保守”了，现在都13月中旬了快...

**Comment by py8765** [comment]
额 年底事情比较多 最近可能先发一个pre版本试用哈

**Comment by violet-day** [comment]
+1

**Comment by yoram-chan** [comment]
+1
