### ISSUE TITLE
pomelo 1.2.0 not supprot Nodejs 4.2.X

### ISSUE THREAD

**Issue by shadow0162** [NetEase/pomelo#772]
my environment is:
Windows 7
Nodejs: 4.2.2 x64 LTS
Pomelo:1.2.0
Python:2.7.11
Npm:2.14.7

got error at toobusy module,please see log:

 *,uv_timer_cb,uint64_t,uint64_t)' : cannot convert argument  2 from 'void (__cdecl *)(uv_timer_t *,int)' to 'uv_timer_cb' [F:\Server\lordofpomelo-0.3.0\game-server\node_modules\toobu sy\build\toobusy.vcxproj]
          None of the functions with this name in scope match the target type
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\12.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (E:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "E:\\Program Files\\nodejs\\node.exe" "E:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd F:\Server\lordofpomelo-0.3.0\game-server\node_modules\toobusy
gyp ERR! node -v v4.2.2
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "E:\\Program Files\\nodejs\\node.exe" "E:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "toobusy"
npm ERR! node v4.2.2
npm ERR! npm  v2.14.7
npm ERR! code ELIFECYCLE

npm ERR! toobusy@0.2.4 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the toobusy@0.2.4 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the toobusy package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls toobusy
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     F:\Server\lordofpomelo-0.3.0\game-server\npm-debug.log

**Comment by shadow0162** [comment]
I found out that toobusy is dead. Can we replace by toobusy-js?
https://github.com/STRML/node-toobusy

**Comment by moloxiao** [comment]
mac user can working on 4.2.2
