### ISSUE TITLE
请教下关于pomelo前端服务器各种问题！

### ISSUE THREAD

**Issue by jonathang4** [NetEase/pomelo#784]
我们在写一个类似于lordofpomelo的多人在线游戏。消息广播频率是150毫秒一次，广播内容是坐标索引等等。但是现在遇到瓶颈有以下几点：
1.一个前端上如果socket链接数(也就是被广播的人数)超过大概120个的时候，这个前端线程会挂掉。
2.可能是项目经验有限，现在广播消息的数据量总是很大，但是却找不到减小广播的办法。protobuf也用上了，但是数据量还是很大。大到web端可以看出20K到30K每秒的流量消耗。
3.我们在启动的时候app.js一直用的是:'production|development'。单独写production启动socket无法链接，不知道啥原因。另外想知道  production 和 development 的模式，有什么区别。
简单总结下，其实主要问题就是：1项目流量很大。2 游戏线程总是会挂掉。
还请假各位帮忙指点指点，我看文档，看源码看了好些日子了。实在是不知道怎么解决了，惭愧。

**Comment by xiaoguomeiyitian** [comment]
竟然150毫秒广播一次....

**Comment by jonathang4** [comment]
╮(￣▽￣")╭ 没办法~  实时推屏。大于150毫秒会有明显延迟感。由于游戏玩法导致玩家移动的不可预测。所以我们只能选择1、实时推送玩家行为。 2、定时(150毫秒)推送玩家坐标。
我们选择的后者。

**Comment by 7demo** [comment]
我这儿一个应用是20-30毫秒一次推送

**Comment by pipi32167** [comment]
12、广播的主要内容是什么？
3、配置里面有development块和production块：
```
 {"development":{...}, "production":{ ...}}
```

**Comment by jonathang4** [comment]
广播是玩家坐标，方向，索引 什么的。
我们的两个配置模块写的是一样的。但是好像没法单独启动一个模块，单独启动就会报错。也不知道为啥。而且最主要的是不知道这两个启动模式到底是啥区别。目前感觉应该只启动的是development。不知道对流量有没有什么帮助。因为我们的日志文件里全是session链接和关闭的记录，感觉好像是因为development模式输出的。但是却不知道怎么关闭。不知道你们都是怎么配置的，有没有体验过两种模式的区别是啥？

**Comment by pipi32167** [comment]
环境变量用于切换环境，用法如下：

pomelo start -e production
pomelo start -e development
