### ISSUE TITLE
问个问题

### ISSUE THREAD

**Issue by wenmachixue1** [NetEase/pomelo#786]
我用npm install pomelo -g 安装了
然后却提示我pomelo 不是内外部命令，是我哪出问题了么？

I:\nodejs\node_global\node_modules\pomelo\node_modules\pomelo-admin\node_module
s\socket.io-client\node_modules\ws\node_modules\nan\nan.h(767): error C3083: 's
malloc': the symbol to the left of a '::' must be a type [I:\nodejs\node_global
\node_modules\pomelo\node_modules\pomelo-admin\node_modules\socket.io-client\no
de_modules\ws\build\bufferutil.vcxproj]
I:\nodejs\node_global\node_modules\pomelo\node_modules\pomelo-admin\node_module
s\socket.io-client\node_modules\ws\node_modules\nan\nan.h(767): error C2039: 'F
reeCallback' : is not a member of 'node' [I:\nodejs\node_global\node_modules\po
melo\node_modules\pomelo-admin\node_modules\socket.io-client\node_modules\ws\bu
ild\bufferutil.vcxproj]
I:\nodejs\node_global\node_modules\pomelo\node_modules\pomelo-admin\node_module
s\socket.io-client\node_modules\ws\node_modules\nan\nan.h(767): error C2061: sy
ntax error : identifier 'FreeCallback' [I:\nodejs\node_global\node_modules\pome
lo\node_modules\pomelo-admin\node_modules\socket.io-client\node_modules\ws\buil
d\bufferutil.vcxproj]
I:\nodejs\node_global\node_modules\pomelo\node_modules\pomelo-admin\node_module
s\socket.io-client\node_modules\ws\node_modules\nan\nan.h(770): error C2065: 'c
allback' : undeclared identifier [I:\nodejs\node_global\node_modules\pomelo\nod
e_modules\pomelo-admin\node_modules\socket.io-client\node_modules\ws\build\buff
erutil.vcxproj]
I:\nodejs\node_global\node_modules\pomelo\node_modules\pomelo-admin\node_module
s\socket.io-client\node_modules\ws\node_modules\nan\nan.h(770): error C2065: 'h
int' : undeclared identifier [I:\nodejs\node_global\node_modules\pomelo\node_mo
dules\pomelo-admin\node_modules\socket.io-client\node_modules\ws\build\bufferut
il.vcxproj]
I:\nodejs\node_global\node_modules\pomelo\node_modules\pomelo-admin\node_module
s\socket.io-client\node_modules\ws\node_modules\nan\nan.h(777): error C2665: 'n
ode::Buffer::New' : none of the 4 overloads could convert all the argument type
s [I:\nodejs\node_global\node_modules\pomelo\node_modules\pomelo-admin\node_mod
ules\socket.io-client\node_modules\ws\build\bufferutil.vcxproj]
          C:\Users\Administrator\.node-gyp\4.2.4\include\node\node_buffer.h(43)
  : could be 'v8::MaybeLocal<v8::Object> node::Buffer::New(v8::Isolate *,char *
  ,size_t)'
          C:\Users\Administrator\.node-gyp\4.2.4\include\node\node_buffer.h(31)
  : or       'v8::MaybeLocal<v8::Object> node::Buffer::New(v8::Isolate *,v8::Lo
  cal<v8::String>,node::encoding)'
          while trying to match the argument list '(v8::Isolate *, const char *
  , uint32_t)'
I:\nodejs\node_global\node_modules\pomelo\node_modules\pomelo-admin\node_module
s\socket.io-client\node_modules\ws\node_modules\nan\nan.h(781): error C2664: 'v
8::Local<v8::Object>::Local(const v8::Local<v8::Object> &)' : cannot convert ar
gument 1 from 'v8::MaybeLocal<v8::Object>' to 'const v8::Local<v8::Object> &' [
I:\nodejs\node_global\node_modules\pomelo\node_modules\pomelo-admin\node_module
s\socket.io-client\node_modules\ws\build\bufferutil.vcxproj]
          Reason: cannot convert from 'v8::MaybeLocal<v8::Object>' to 'const v8
  ::Local<v8::Object>'
          No user-defined-conversion operator available that can perform this c
  onversion, or the operator cannot be called
I:\nodejs\node_global\node_modules\pomelo\node_modules\pomelo-admin\node_module
s\socket.io-client\node_modules\ws\node_modules\nan\nan.h(788): error C2039: 'U
se' : is not a member of 'node::Buffer' [I:\nodejs\node_global\node_modules\pom
elo\node_modules\pomelo-admin\node_modules\socket.io-client\node_modules\ws\bui
ld\bufferutil.vcxproj]
I:\nodejs\node_global\node_modules\pomelo\node_modules\pomelo-admin\node_module
s\socket.io-client\node_modules\ws\node_modules\nan\nan.h(788): error C3861: 'U
se': identifier not found [I:\nodejs\node_global\node_modules\pomelo\node_modul
es\pomelo-admin\node_modules\socket.io-client\node_modules\ws\build\bufferutil.
vcxproj]
I:\nodejs\node_global\node_modules\pomelo\node_modules\pomelo-admin\node_module
s\socket.io-client\node_modules\ws\node_modules\nan\nan.h(1728): error C2039: '
IsExternalAscii' : is not a member of 'v8::String' [I:\nodejs\node_global\node_
modules\pomelo\node_modules\pomelo-admin\node_modules\socket.io-client\node_mod
ules\ws\build\bufferutil.vcxproj]
          C:\Users\Administrator\.node-gyp\4.2.4\include\node\v8.h(2081) : see
  declaration of 'v8::String'
I:\nodejs\node_global\node_modules\pomelo\node_modules\pomelo-admin\node_module
s\socket.io-client\node_modules\ws\node_modules\nan\nan.h(1729): error C2039: '
ExternalAsciiStringResource' : is not a member of 'v8::String' [I:\nodejs\node_
global\node_modules\pomelo\node_modules\pomelo-admin\node_modules\socket.io-cli
ent\node_modules\ws\build\bufferutil.vcxproj]
          C:\Users\Administrator\.node-gyp\4.2.4\include\node\v8.h(2081) : see
  declaration of 'v8::String'
I:\nodejs\node_global\node_modules\pomelo\node_modules\pomelo-admin\node_module
s\socket.io-client\node_modules\ws\node_modules\nan\nan.h(1729): error C4430: m
issing type specifier - int assumed. Note: C++ does not support default-int [I:
\nodejs\node_global\node_modules\pomelo\node_modules\pomelo-admin\node_modules\
socket.io-client\node_modules\ws\build\bufferutil.vcxproj]
I:\nodejs\node_global\node_modules\pomelo\node_modules\pomelo-admin\node_module
s\socket.io-client\node_modules\ws\node_modules\nan\nan.h(1729): error C2143: s
yntax error : missing ';' before '*' [I:\nodejs\node_global\node_modules\pomelo
\node_modules\pomelo-admin\node_modules\socket.io-client\node_modules\ws\build\
bufferutil.vcxproj]
I:\nodejs\node_global\node_modules\pomelo\node_modules\pomelo-admin\node_module
s\socket.io-client\node_modules\ws\node_modules\nan\nan.h(1729): error C2065: '
ext' : undeclared identifier [I:\nodejs\node_global\node_modules\pomelo\node_mo
dules\pomelo-admin\node_modules\socket.io-client\node_modules\ws\build\bufferut
il.vcxproj]
I:\nodejs\node_global\node_modules\pomelo\node_modules\pomelo-admin\node_module
s\socket.io-client\node_modules\ws\node_modules\nan\nan.h(1730): error C2065: '
ext' : undeclared identifier [I:\nodejs\node_global\node_modules\pomelo\node_mo
dules\pomelo-admin\node_modules\socket.io-client\node_modules\ws\build\bufferut
il.vcxproj]
I:\nodejs\node_global\node_modules\pomelo\node_modules\pomelo-admin\node_module
s\socket.io-client\node_modules\ws\node_modules\nan\nan.h(1730): error C2039: '
GetExternalAsciiStringResource' : is not a member of 'v8::String' [I:\nodejs\no
de_global\node_modules\pomelo\node_modules\pomelo-admin\node_modules\socket.io-
client\node_modules\ws\build\bufferutil.vcxproj]
          C:\Users\Administrator\.node-gyp\4.2.4\include\node\v8.h(2081) : see
  declaration of 'v8::String'
I:\nodejs\node_global\node_modules\pomelo\node_modules\pomelo-admin\node_module
s\socket.io-client\node_modules\ws\node_modules\nan\nan.h(1731): error C2065: '
ext' : undeclared identifier [I:\nodejs\node_global\node_modules\pomelo\node_mo
dules\pomelo-admin\node_modules\socket.io-client\node_modules\ws\build\bufferut
il.vcxproj]
I:\nodejs\node_global\node_modules\pomelo\node_modules\pomelo-admin\node_module
s\socket.io-client\node_modules\ws\node_modules\nan\nan.h(1731): error C2227: l
eft of '->data' must point to class/struct/union/generic type [I:\nodejs\node_g
lobal\node_modules\pomelo\node_modules\pomelo-admin\node_modules\socket.io-clie
nt\node_modules\ws\build\bufferutil.vcxproj]
          type is 'unknown-type'
I:\nodejs\node_global\node_modules\pomelo\node_modules\pomelo-admin\node_module
s\socket.io-client\node_modules\ws\node_modules\nan\nan.h(1732): error C2065: '
ext' : undeclared identifier [I:\nodejs\node_global\node_modules\pomelo\node_mo
dules\pomelo-admin\node_modules\socket.io-client\node_modules\ws\build\bufferut
il.vcxproj]
I:\nodejs\node_global\node_modules\pomelo\node_modules\pomelo-admin\node_module
s\socket.io-client\node_modules\ws\node_modules\nan\nan.h(1732): error C2227: l
eft of '->length' must point to class/struct/union/generic type [I:\nodejs\node
_global\node_modules\pomelo\node_modules\pomelo-admin\node_modules\socket.io-cl
ient\node_modules\ws\build\bufferutil.vcxproj]
          type is 'unknown-type'
  validation.cc
I:\nodejs\node_global\node_modules\pomelo\node_modules\pomelo-admin\node_module
s\socket.io-client\node_modules\ws\node_modules\nan\nan.h(409): error C2039: 'E
xternalAsciiStringResource' : is not a member of 'v8::String' [I:\nodejs\node_g
lobal\node_modules\pomelo\node_modules\pomelo-admin\node_modules\socket.io-clie
nt\node_modules\ws\build\validation.vcxproj]
          C:\Users\Administrator\.node-gyp\4.2.4\include\node\v8.h(2081) : see
  declaration of 'v8::String'
I:\nodejs\node_global\node_modules\pomelo\node_modules\pomelo-admin\node_module
s\socket.io-client\node_modules\ws\node_modules\nan\nan.h(409): error C2065: 'E
xternalAsciiStringResource' : undeclared identifier [I:\nodejs\node_global\node
_modules\pomelo\node_modules\pomelo-admin\node_modules\socket.io-client\node_mo
dules\ws\build\validation.vcxproj]
I:\nodejs\node_global\node_modules\pomelo\node_modules\pomelo-admin\node_module
s\socket.io-client\node_modules\ws\node_modules\nan\nan.h(409): error C2065: 'r
esource' : undeclared identifier [I:\nodejs\node_global\node_modules\pomelo\nod
e_modules\pomelo-admin\node_modules\socket.io-client\node_modules\ws\build\vali
dation.vcxproj]
I:\nodejs\node_global\node_modules\pomelo\node_modules\pomelo-admin\node_module
s\socket.io-client\node_modules\ws\node_modules\nan\nan.h(409): error C2448: 'N
anNew' : function-style initializer appears to be a function definition [I:\nod
ejs\node_global\node_modules\pomelo\node_modules\pomelo-admin\node_modules\sock
et.io-client\node_modules\ws\build\validation.vcxproj]
I:\nodejs\node_global\node_modules\pomelo\node_modules\pomelo-admin\node_module
s\socket.io-client\node_modules\ws\node_modules\nan\nan.h(430): error C2766: ex
plicit specialization; 'v8::Local<v8::StringObject> NanNew<v8::StringObject,v8:
:Local<v8::String>>(v8::Local<v8::String>)' has already been defined [I:\nodejs
\node_global\node_modules\pomelo\node_modules\pomelo-admin\node_modules\socket.
io-client\node_modules\ws\build\validation.vcxproj]
          I:\nodejs\node_global\node_modules\pomelo\node_modules\pomelo-admin\n
  ode_modules\socket.io-client\node_modules\ws\node_modules\nan\nan.h(420) : se
  e previous definition of 'NanNew'
I:\nodejs\node_global\node_modules\pomelo\node_modules\pomelo-admin\node_module
s\socket.io-client\node_modules\ws\node_modules\nan\nan.h(447): error C2995: 'v
8::Local<v8::RegExp> NanNew(v8::Local<v8::String>,v8::RegExp::Flags)' : functio
n template has already been defined [I:\nodejs\node_global\node_modules\pomelo\
node_modules\pomelo-admin\node_modules\socket.io-client\node_modules\ws\build\v
alidation.vcxproj]
          I:\nodejs\node_global\node_modules\pomelo\node_modules\pomelo-admin\n
  ode_modules\socket.io-client\node_modules\ws\node_modules\nan\nan.h(438) : se
  e declaration of 'NanNew'
I:\nodejs\node_global\node_modules\pomelo\node_modules\pomelo-admin\node_module
s\socket.io-client\node_modules\ws\node_modules\nan\nan.h(459): error C2995: 'v
8::Local<v8::RegExp> NanNew(v8::Local<v8::String>,v8::RegExp::Flags)' : functio
n template has already been defined [I:\nodejs\node_global\node_modules\pomelo\
node_modules\pomelo-admin\node_modules\socket.io-client\node_modules\ws\build\v
alidation.vcxproj]
          I:\nodejs\node_global\node_modules\pomelo\node_modules\pomelo-admin\n
  ode_modules\socket.io-client\node_modules\ws\node_modules\nan\nan.h(450) : se
  e declaration of 'NanNew'
I:\nodejs\node_global\node_modules\pomelo\node_modules\pomelo-admin\node_module
s\socket.io-client\node_modules\ws\node_modules\nan\nan.h(767): error C3083: 's
malloc': the symbol to the left of a '::' must be a type [I:\nodejs\node_global
\node_modules\pomelo\node_modules\pomelo-admin\node_modules\socket.io-client\no
de_modules\ws\build\validation.vcxproj]
I:\nodejs\node_global\node_modules\pomelo\node_modules\pomelo-admin\node_module
s\socket.io-client\node_modules\ws\node_modules\nan\nan.h(767): error C2039: 'F
reeCallback' : is not a member of 'node' [I:\nodejs\node_global\node_modules\po
melo\node_modules\pomelo-admin\node_modules\socket.io-client\node_modules\ws\bu
ild\validation.vcxproj]
I:\nodejs\node_global\node_modules\pomelo\node_modules\pomelo-admin\node_module
s\socket.io-client\node_modules\ws\node_modules\nan\nan.h(767): error C2061: sy
ntax error : identifier 'FreeCallback' [I:\nodejs\node_global\node_modules\pome
lo\node_modules\pomelo-admin\node_modules\socket.io-client\node_modules\ws\buil
d\validation.vcxproj]
I:\nodejs\node_global\node_modules\pomelo\node_modules\pomelo-admin\node_module
s\socket.io-client\node_modules\ws\node_modules\nan\nan.h(770): error C2065: 'c
allback' : undeclared identifier [I:\nodejs\node_global\node_modules\pomelo\nod
e_modules\pomelo-admin\node_modules\socket.io-client\node_modules\ws\build\vali
dation.vcxproj]
I:\nodejs\node_global\node_modules\pomelo\node_modules\pomelo-admin\node_module
s\socket.io-client\node_modules\ws\node_modules\nan\nan.h(770): error C2065: 'h
int' : undeclared identifier [I:\nodejs\node_global\node_modules\pomelo\node_mo
dules\pomelo-admin\node_modules\socket.io-client\node_modules\ws\build\validati
on.vcxproj]
I:\nodejs\node_global\node_modules\pomelo\node_modules\pomelo-admin\node_module
s\socket.io-client\node_modules\ws\node_modules\nan\nan.h(777): error C2665: 'n
ode::Buffer::New' : none of the 4 overloads could convert all the argument type
s [I:\nodejs\node_global\node_modules\pomelo\node_modules\pomelo-admin\node_mod
ules\socket.io-client\node_modules\ws\build\validation.vcxproj]
          C:\Users\Administrator\.node-gyp\4.2.4\include\node\node_buffer.h(43)
  : could be 'v8::MaybeLocal<v8::Object> node::Buffer::New(v8::Isolate *,char *
  ,size_t)'
          C:\Users\Administrator\.node-gyp\4.2.4\include\node\node_buffer.h(31)
  : or       'v8::MaybeLocal<v8::Object> node::Buffer::New(v8::Isolate *,v8::Lo
  cal<v8::String>,node::encoding)'
          while trying to match the argument list '(v8::Isolate *, const char *
  , uint32_t)'
I:\nodejs\node_global\node_modules\pomelo\node_modules\pomelo-admin\node_module
s\socket.io-client\node_modules\ws\node_modules\nan\nan.h(781): error C2664: 'v
8::Local<v8::Object>::Local(const v8::Local<v8::Object> &)' : cannot convert ar
gument 1 from 'v8::MaybeLocal<v8::Object>' to 'const v8::Local<v8::Object> &' [
I:\nodejs\node_global\node_modules\pomelo\node_modules\pomelo-admin\node_module
s\socket.io-client\node_modules\ws\build\validation.vcxproj]
          Reason: cannot convert from 'v8::MaybeLocal<v8::Object>' to 'const v8
  ::Local<v8::Object>'
/          No user-defined-conversion operator available that can perform this c

  onversion, or the operator cannot be called
I:\nodejs\node_global\node_modules\pomelo\node_modules\pomelo-admin\node_module
s\socket.io-client\node_modules\ws\node_modules\nan\nan.h(788): error C2039: 'U
se' : is not a member of 'node::Buffer' [I:\nodejs\node_global\node_modules\pom
elo\node_modules\pomelo-admin\node_modules\socket.io-client\node_modules\ws\bui
ld\validation.vcxproj]
I:\nodejs\node_global\node_modules\pomelo\node_modules\pomelo-admin\node_module
s\socket.io-client\node_modules\ws\node_modules\nan\nan.h(788): error C3861: 'U
se': identifier not found [I:\nodejs\node_global\node_modules\pomelo\node_modul
es\pomelo-admin\node_modules\socket.io-client\node_modules\ws\build\validation.
vcxproj]
I:\nodejs\node_global\node_modules\pomelo\node_modules\pomelo-admin\node_module
s\socket.io-client\node_modules\ws\node_modules\nan\nan.h(1728): error C2039: '
IsExternalAscii' : is not a member of 'v8::String' [I:\nodejs\node_global\node_
modules\pomelo\node_modules\pomelo-admin\node_modules\socket.io-client\node_mod
ules\ws\build\validation.vcxproj]
          C:\Users\Administrator\.node-gyp\4.2.4\include\node\v8.h(2081) : see
  declaration of 'v8::String'
I:\nodejs\node_global\node_modules\pomelo\node_modules\pomelo-admin\node_module
s\socket.io-client\node_modules\ws\node_modules\nan\nan.h(1729): error C2039: '
ExternalAsciiStringResource' : is not a member of 'v8::String' [I:\nodejs\node_
global\node_modules\pomelo\node_modules\pomelo-admin\node_modules\socket.io-cli
ent\node_modules\ws\build\validation.vcxproj]
          C:\Users\Administrator\.node-gyp\4.2.4\include\node\v8.h(2081) : see
  declaration of 'v8::String'
I:\nodejs\node_global\node_modules\pomelo\node_modules\pomelo-admin\node_module
s\socket.io-client\node_modules\ws\node_modules\nan\nan.h(1729): error C4430: m
issing type specifier - int assumed. Note: C++ does not support default-int [I:
\nodejs\node_global\node_modules\pomelo\node_modules\pomelo-admin\node_modules\
socket.io-client\node_modules\ws\build\validation.vcxproj]
I:\nodejs\node_global\node_modules\pomelo\node_modules\pomelo-admin\node_module
s\socket.io-client\node_modules\ws\node_modules\nan\nan.h(1729): error C2143: s
yntax error : missing ';' before '*' [I:\nodejs\node_global\node_modules\pomelo
\node_modules\pomelo-admin\node_modules\socket.io-client\node_modules\ws\build\
validation.vcxproj]
I:\nodejs\node_global\node_modules\pomelo\node_modules\pomelo-admin\node_module
s\socket.io-client\node_modules\ws\node_modules\nan\nan.h(1729): error C2065: '
ext' : undeclared identifier [I:\nodejs\node_global\node_modules\pomelo\node_mo
dules\pomelo-admin\node_modules\socket.io-client\node_modules\ws\build\validati
on.vcxproj]
I:\nodejs\node_global\node_modules\pomelo\node_modules\pomelo-admin\node_module
s\socket.io-client\node_modules\ws\node_modules\nan\nan.h(1730): error C2065: '
ext' : undeclared identifier [I:\nodejs\node_global\node_modules\pomelo\node_mo
dules\pomelo-admin\node_modules\socket.io-client\node_modules\ws\build\validati
on.vcxproj]
I:\nodejs\node_global\node_modules\pomelo\node_modules\pomelo-admin\node_module
s\socket.io-client\node_modules\ws\node_modules\nan\nan.h(1730): error C2039: '
GetExternalAsciiStringResource' : is not a member of 'v8::String' [I:\nodejs\no
de_global\node_modules\pomelo\node_modules\pomelo-admin\node_modules\socket.io-
client\node_modules\ws\build\validation.vcxproj]
          C:\Users\Administrator\.node-gyp\4.2.4\include\node\v8.h(2081) : see
  declaration of 'v8::String'
I:\nodejs\node_global\node_modules\pomelo\node_modules\pomelo-admin\node_module
s\socket.io-client\node_modules\ws\node_modules\nan\nan.h(1731): error C2065: '
ext' : undeclared identifier [I:\nodejs\node_global\node_modules\pomelo\node_mo
dules\pomelo-admin\node_modules\socket.io-client\node_modules\ws\build\validati
on.vcxproj]
I:\nodejs\node_global\node_modules\pomelo\node_modules\pomelo-admin\node_module
s\socket.io-client\node_modules\ws\node_modules\nan\nan.h(1731): error C2227: l
eft of '->data' must point to class/struct/union/generic type [I:\nodejs\node_g
lobal\node_modules\pomelo\node_modules\pomelo-admin\node_modules\socket.io-clie
nt\node_modules\ws\build\validation.vcxproj]
          type is 'unknown-type'
I:\nodejs\node_global\node_modules\pomelo\node_modules\pomelo-admin\node_module

**Comment by wenmachixue1** [comment]
配置个环境变量就能正常使用了。。只有我遇到这个问题么。
'..\nodejs\node_global'

**Comment by llqgithub** [comment]
貌似，只有你
