### ISSUE TITLE
安装失败，求思路

### ISSUE THREAD

**Issue by wenmachixue1** [NetEase/pomelo#787]
我用npm install pomelo -g 安装的

C:\Users\Administrator>npm install pomelo -g

> heapdump@0.3.7 install I:\nodejs\node_global\node_modules\pomelo\node_modules\
pomelo-admin\node_modules\heapdump
> node-gyp rebuild

-
I:\nodejs\node_global\node_modules\pomelo\node_modules\pomelo-admin\node_modules
\heapdump>if not defined npm_config_node_gyp (node "I:\nodejs\node_modules\npm\b
in\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (n
ode  rebuild )
在此解决方案中一次生成一个项目。若要启用并行生成，请添加“/m”开关。
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\Microsoft.Cpp.InvalidPlatform
.Targets(23,7): error MSB8007: 项目“addon.vcxproj”的平台无效。平台为“x64”。
您会看到此消息的可能原因是，您尝
试在没有解决方案文件的情况下生成项目，并且为此项目指定了并不存在的非默认平台。 [
I:\nodejs\node_global\node_modules\pom
elo\node_modules\pomelo-admin\node_modules\heapdump\build\addon.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe
` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (I:\nodejs\node_modules\npm\node_modul
es\node-gyp\lib\build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_proces
s.js:200:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "I:\\nodejs\\node.exe" "I:\\nodejs\\node_modules\\npm\\node_mod
ules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd I:\nodejs\node_global\node_modules\pomelo\node_modules\pomelo-admin
\node_modules\heapdump
ERR! node -v v4.2.4
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok

> bufferutil@1.2.1 install I:\nodejs\node_global\node_modules\pomelo\node_module
s\ws\node_modules\bufferutil
> node-gyp rebuild

I:\nodejs\node_global\node_modules\pomelo\node_modules\ws\node_modules\bufferuti
l>if not defined npm_config_node_gyp (node "I:\nodejs\node_modules\npm\bin\node-
gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node  reb
uild )
在此解决方案中一次生成一个项目。若要启用并行生成，请添加“/m”开关。
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\Microsoft.Cpp.InvalidPlatform
.Targets(23,7): error MSB8007: 项目“bufferutil.vcxproj”的平台无效。平台为“x64
”。您会看到此消息的可能原
因是，您尝试在没有解决方案文件的情况下生成项目，并且为此项目指定了并不存在的非默
认平台。 [I:\nodejs\node_global\node_module
s\pomelo\node_modules\ws\node_modules\bufferutil\build\bufferutil.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe
` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (I:\nodejs\node_modules\npm\node_modul
es\node-gyp\lib\build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_proces
s.js:200:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "I:\\nodejs\\node.exe" "I:\\nodejs\\node_modules\\npm\\node_mod
ules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd I:\nodejs\node_global\node_modules\pomelo\node_modules\ws\node_modu
les\bufferutil
gyp ERR! node -v v4.2.4
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok

> utf-8-validate@1.2.1 install I:\nodejs\node_global\node_modules\pomelo\node_mo
dules\ws\node_modules\utf-8-validate
> node-gyp rebuild

I:\nodejs\node_global\node_modules\pomelo\node_modules\ws\node_modules\utf-8-val
idate>if not defined npm_config_node_gyp (node "I:\nodejs\node_modules\npm\bin\n
ode-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node
 rebuild )
在此解决方案中一次生成一个项目。若要启用并行生成，请添加“/m”开关。
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\Microsoft.Cpp.InvalidPlatform
.Targets(23,7): error MSB8007: 项目“validation.vcxproj”的平台无效。平台为“x64
”。您会看到此消息的可能原
因是，您尝试在没有解决方案文件的情况下生成项目，并且为此项目指定了并不存在的非默
认平台。 [I:\nodejs\node_global\node_module
s\pomelo\node_modules\ws\node_modules\utf-8-validate\build\validation.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe
` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (I:\nodejs\node_modules\npm\node_modul
es\node-gyp\lib\build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_proces
s.js:200:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "I:\\nodejs\\node.exe" "I:\\nodejs\\node_modules\\npm\\node_mod
ules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd I:\nodejs\node_global\node_modules\pomelo\node_modules\ws\node_modu
les\utf-8-validate
gyp ERR! node -v v4.2.4
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok
npm WARN optional dep failed, continuing bufferutil@1.2.1
npm WARN optional dep failed, continuing utf-8-validate@1.2.1

> ws@0.4.32 install I:\nodejs\node_global\node_modules\pomelo\node_modules\pomel
o-admin\node_modules\socket.io-client\node_modules\ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)

/
I:\nodejs\node_global\node_modules\pomelo\node_modules\pomelo-admin\node_modules
\socket.io-client\node_modules\ws>if not defined npm_config_node_gyp (node "I:\n
odejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gy
p.js" rebuild )  else (node  rebuild )
在此解决方案中一次生成一个项目。若要启用并行生成，请添加“/m”开关。
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\Microsoft.Cpp.InvalidPlatform
.Targets(23,7): error MSB8007: 项目“bufferutil.vcxproj”的平台无效。平台为“x64
”。您会看到此消息的可能原
因是，您尝试在没有解决方案文件的情况下生成项目，并且为此项目指定了并不存在的非默
认平台。 [I:\nodejs\node_global\node_module
s\pomelo\node_modules\pomelo-admin\node_modules\socket.io-client\node_modules\w
s\build\bufferutil.vcxproj]
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\Microsoft.Cpp.InvalidPlatform
.Targets(23,7): error MSB8007: 项目“validation.vcxproj”的平台无效。平台为“x64
”。您会看到此消息的可能原
因是，您尝试在没有解决方案文件的情况下生成项目，并且为此项目指定了并不存在的非默
认平台。 [I:\nodejs\node_global\node_module
s\pomelo\node_modules\pomelo-admin\node_modules\socket.io-client\node_modules\w
s\build\validation.vcxproj]

> ws@0.4.32 install I:\nodejs\node_global\node_modules\pomelo\node_modules\socke
t.io\node_modules\socket.io-client\node_modules\ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)

I:\nodejs\node_global\node_modules\pomelo\node_modules\socket.io\node_modules\so
cket.io-client\node_modules\ws>if not defined npm_config_node_gyp (node "I:\node
js\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.j
s" rebuild )  else (node  rebuild )
在此解决方案中一次生成一个项目。若要启用并行生成，请添加“/m”开关。
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\Microsoft.Cpp.InvalidPlatform
.Targets(23,7): error MSB8007: 项目“bufferutil.vcxproj”的平台无效。平台为“x64
”。您会看到此消息的可能原
因是，您尝试在没有解决方案文件的情况下生成项目，并且为此项目指定了并不存在的非默
认平台。 [I:\nodejs\node_global\node_module
s\pomelo\node_modules\socket.io\node_modules\socket.io-client\node_modules\ws\b
uild\bufferutil.vcxproj]
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\Microsoft.Cpp.InvalidPlatform
.Targets(23,7): error MSB8007: 项目“validation.vcxproj”的平台无效。平台为“x64
”。您会看到此消息的可能原
因是，您尝试在没有解决方案文件的情况下生成项目，并且为此项目指定了并不存在的非默
认平台。 [I:\nodejs\node_global\node_module
s\pomelo\node_modules\socket.io\node_modules\socket.io-client\node_modules\ws\b
uild\validation.vcxproj]

> ws@0.4.32 install I:\nodejs\node_global\node_modules\pomelo\node_modules\pomel
o-rpc\node_modules\socket.io-client\node_modules\ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)

I:\nodejs\node_global\node_modules\pomelo\node_modules\pomelo-rpc\node_modules\s
ocket.io-client\node_modules\ws>if not defined npm_config_node_gyp (node "I:\nod
ejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.
js" rebuild )  else (node  rebuild )
在此解决方案中一次生成一个项目。若要启用并行生成，请添加“/m”开关。
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\Microsoft.Cpp.InvalidPlatform
.Targets(23,7): error MSB8007: 项目“bufferutil.vcxproj”的平台无效。平台为“x64
”。您会看到此消息的可能原
因是，您尝试在没有解决方案文件的情况下生成项目，并且为此项目指定了并不存在的非默
认平台。 [I:\nodejs\node_global\node_module
s\pomelo\node_modules\pomelo-rpc\node_modules\socket.io-client\node_modules\ws\
build\bufferutil.vcxproj]
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\Microsoft.Cpp.InvalidPlatform
.Targets(23,7): error MSB8007: 项目“validation.vcxproj”的平台无效。平台为“x64
”。您会看到此消息的可能原
因是，您尝试在没有解决方案文件的情况下生成项目，并且为此项目指定了并不存在的非默
认平台。 [I:\nodejs\node_global\node_module
s\pomelo\node_modules\pomelo-rpc\node_modules\socket.io-client\node_modules\ws\
build\validation.vcxproj]
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "I:\\nodejs\\node.exe" "I:\\nodejs\\node_modules\\npm\\bin\\npm-cl
i.js" "install" "pomelo" "-g"
npm ERR! node v4.2.4
npm ERR! npm  v2.14.12
npm ERR! code ELIFECYCLE

npm ERR! heapdump@0.3.7 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the heapdump@0.3.7 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the heapdump package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls heapdump
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Administrator\npm-debug.log

**Comment by shanegxxiao** [comment]
这个是因为pomelo1.2.0部分依赖的库的版本不兼容你机器的node等环境导致的，有兴趣可以一起升级测试https://github.com/shanegxxiao/pomelo，这边做了些修改还没有完全改完和测试，目前试过可以正常安装和跑connector为native socket和socket.io的helloworld，环境是：node5.3.0，win10 x64，python2.7，vs2013。

**Comment by wenmachixue1** [comment]
谢谢了。安装VS2013后好了。
顺带提个BUG，之前装好后，pomelo提示“不是内/外部命令”，后来自己配置了个pomelo的环境变量后，就好了，建议这个写在文档里，‘..\nodejs\node_global’
环境：node4.2.4,win7 x64,python2.7,vs2013

**Comment by markchou** [comment]
pomelo是不是只支持0.10系列的版本啊
