### ISSUE TITLE
关于pomelo 2.x 的最新消息

### ISSUE THREAD

**Issue by llqgit** [NetEase/pomelo#788]
pomelo 2.x 现在（2016年1月8日）保守估计，什么时候能和大家见面，辛苦的亲们？

**Comment by moloxiao** [comment]
在哪里可以看到roadmap？@llqgithub

**Comment by xpol** [comment]
是不是现在的版本跑 ES6 还有问题啊？

**Comment by tongjinle** [comment]
我用es6写了下,发现remote上的方法都丢了,好像是没有了

**Comment by moloxiao** [comment]
没发现跑es6有什么问题啊

**Comment by xpol** [comment]
不 `use strict` 的话，代码里面的 `for of` 会有问题。
应该是 `--harmony_modules` 还不是 default 的原因吧。
