### ISSUE TITLE
如何保证消息到达客户端？

### ISSUE THREAD

**Issue by yuzhaoshi** [NetEase/pomelo#789]
由于业务需求，必须保证消息100%到达客户端。
我的想法是，服务端推送消息后，客户端收到返回回执。如果服务端没有收到回执，进行重发或者保存离线消息。
请问这样的方法可行吗？该如何实现？
是否有更好的方法？
请不吝赐教。

**Comment by cynron** [comment]
不知道你们的业务的qos确切要求

- 如果仅仅是客户端回ack的话，可能会造成消息重复发送，就是客户端发送ack的时候，客户端挂掉的情况

- 如果想保证有且只有一次，可以进行两次确认方法，具体可以参考mqtt的当消息qos为2时候的实现策略，但是这个也仅仅能在网络及客户端出问题的时候有效，如果服务器宕机的话，也会在一段时间内不正常
