### ISSUE TITLE
Problem installing after following the instructions

### ISSUE THREAD

**Issue by cdrandin** [NetEase/pomelo#790]
got:
Python 2.7.11
Microsoft Visual C++ 2010 Express
Windows 7 SDK (https://www.microsoft.com/en-us/download/details.aspx?id=8279)
node-gyp.

Been searching online and nothing has resolved it from not working.
This is what happens when I run the following command: npm install pomelo -g
https://ghostbin.com/paste/ye7m4

**Comment by trinhvietnam** [comment]
you don't need install pomelo in windows, i tried but i failed. Other solution is clone folder (lib) pomelo was install in ubuntu and paste it to folder node_modules of your project, it like this picture 
pomelo
![pomelo](https://cloud.githubusercontent.com/assets/5329583/12356414/33b87350-bbd5-11e5-98f3-0243c0e7a7eb.png)

And now you clone some sample project of pomelo to try it, i successed with above solotion.
Here is pomelo was complied from ubuntu that i used
https://drive.google.com/file/d/0B-hxz6ee5n8_TEtzdllzZGo5bjg/view?usp=sharing

**Comment by cdrandin** [comment]
Oh cool thanks. I will try that out.

**Comment by cdrandin** [comment]
I am having troubling running the command line tool. I am able to do something like node_modules/pomelo/bin/pomelo, but even then I still get exceptions about it running. How can I install or setup the bin for the directory?

https://ghostbin.com/paste/853t3

**Comment by trinhvietnam** [comment]
the solution only help you programming with pomelo, i'm also falil when run commanline pomelo. 
Here source chatofpomelo is customize by me, you can download and extract then run with commandline
  node app.js for both web-server and game-server.
That project i just customize with multi chat processor

{
    "development":{
        "connector":[
          {"id": "connector-server-1", "host": "127.0.0.1", "port": 4050, "clientPort": 3050, "frontend": true},
          {"id": "connector-server-2", "host": "127.0.0.1", "port": 4051, "clientPort": 3051, "frontend": true},
          {"id": "connector-server-3", "host": "127.0.0.1", "port": 4052, "clientPort": 3052, "frontend": true}
         ],
        "chat":[
          {"id": "chat-server-1", "host": "127.0.0.1", "port": 6050},
          {"id": "chat-server-2", "host": "127.0.0.1", "port": 6051},
          {"id": "chat-server-3", "host": "127.0.0.1", "port": 6052}
        ],
        "gate":[
	       {"id": "gate-server-1", "host": "127.0.0.1", "clientPort": 3014, "frontend": true}
	    ]
    },
    "production":{
      "connector":[
        {"id": "connector-server-1", "host": "127.0.0.1", "port": 4050, "clientPort": 3050, "frontend": true},
        {"id": "connector-server-2", "host": "127.0.0.1", "port": 4051, "clientPort": 3051, "frontend": true},
        {"id": "connector-server-3", "host": "127.0.0.1", "port": 4052, "clientPort": 3052, "frontend": true}
      ],
      "chat":[
        {"id": "chat-server-1", "host": "127.0.0.1", "port": 6050},
        {"id": "chat-server-2", "host": "127.0.0.1", "port": 6051},
        {"id": "chat-server-3", "host": "127.0.0.1", "port": 6052}
      ],
      "gate":[
        {"id": "gate-server-1", "host": "127.0.0.1", "clientPort": 3014, "frontend": true}
      ]
  }
}

**Comment by trinhvietnam** [comment]
@cdrandin  i just fixed it on windows to run commend line tool
please run this command line to know where is global folder of node moduls 
 npm list -g
on my computer global folder of node module is  C:\Users\KSTN-NAM\AppData\Roaming\npm
Then copy pomelo folder ( https://drive.google.com/file/d/0B-hxz6ee5n8_TEtzdllzZGo5bjg/view?usp=sharing) to that path 
and create 2 file pomelo and pomelo.cmd like in this picture
![pomelo-path](https://cloud.githubusercontent.com/assets/5329583/12370931/0965538a-bc56-11e5-9cac-7c1f7a9b56f7.png)

I attach 2 file here 
https://drive.google.com/file/d/0B-hxz6ee5n8_WmQ3NDRpZ21aR2M/view?usp=sharing

Last step is config path to system know where is pomelo using System variables Path
![pomelo-des](https://cloud.githubusercontent.com/assets/5329583/12370952/a95a77b2-bc56-11e5-803f-0ae5afe017b0.png)

ok now you can using command line like pomelo list, pomelo start ....

**Comment by cdrandin** [comment]
Awesome, thanks!. I will check this out in the morning.

**Comment by cdrandin** [comment]
Hey, sorry for the delay. I was able to get the command line tool working, however, it stopped when trying to install dependencies. 

debug log: https://ghostbin.com/paste/y27nz

I just followed the instructions for creating a new project.
Here is what I currently have in the project: https://gyazo.com/55e340a01ad2906bb8706b3cac3365f5

I also get bunch of exceptions when trying to start, list, stop using the pomelo command, but I assume that is the case because I am missing the dependencies.

**Comment by trinhvietnam** [comment]
you do not has pomelo lib in node modules.Please insert it to node_modules
And you should using command "pomelo init" to create your project
You can try this project that i create by manual commandline 'pomelo init' and copy paste pomelo lib into node_modules 
Dowload in from https://drive.google.com/file/d/0B-hxz6ee5n8_Q1JfbzRZelBqT3M/view?usp=sharing

**Comment by cdrandin** [comment]
Oh so I also need to put pomelo into the project's node_modules folder as well? I thought doing -g in npm install would just let it work since it is considered to be in global space now.

**Comment by cdrandin** [comment]
pomelo start works under game-server. However, I get the following error when trying to run node on app.js under web-server https://ghostbin.com/paste/4k22n

**Comment by cdrandin** [comment]
Upon further messing around. It seems a lot of the code in the web-server/app.js methods don't work because they are no longer bundled with Express
https://ghostbin.com/paste/mrwdo

**Comment by trinhvietnam** [comment]
please run only game-server in https://drive.google.com/file/d/0B-hxz6ee5n8_Q1JfbzRZelBqT3M/view?usp=sharing
And if error then send me some of picture about error, perhaps i can help you
Express is other node modules its is independent pomelo.
If you can run game-server is ok
Express will has other solution
Note please run project i send by link https://drive.google.com/file/d/0B-hxz6ee5n8_Q1JfbzRZelBqT3M/view

**Comment by cdrandin** [comment]
Hey, so I got pomelo working properly. It seems I couldn't have 2 different instances running.

**Comment by trinhvietnam** [comment]
like

**Comment by cdrandin** [comment]
After searching a bit I was able to find.
https://github.com/NetEase/chatofpomelo
https://github.com/NetEase/pomelo-unitychat

So far this is helping. One thing I am confused about is how the handlers are called.

How `pclient.request("connector.entryHandler.enter", userMessage, (data)=>{`
is able to call  `handler.enter = function(msg, session, next) {`

Does pomel automatically handle the naming scheme when trying to make a request on client side?
