### ISSUE TITLE
关于mqtt稳定性的问题

### ISSUE THREAD

**Issue by yuzhaoshi** [NetEase/pomelo#791]
正在做IM项目，想咨询一下，pomelo使用mqttconnector，android手机客户端使用paho，ios手机客户端使用libmosquitto，浏览器客户端使用mqtt.js，这个方案可行吗？
另外，请教一下用过的朋友，用mqtt稳定性如何？目前使用libpomelo2稳定性不好。

**Comment by cynron** [comment]
libmosquitto 以前的版本有很多问题，现在不清楚稳定性

可以考虑paho  http://www.eclipse.org/paho/ ibm出品

**Comment by cynron** [comment]
另外libpomelo2 在我们这边的服务器中跑得很稳定，移动环境下，确实没有很多测试，如果有不稳定的话，希望能有bug report，谢谢
