### ISSUE TITLE
can't install pomelo via npm

### ISSUE THREAD

**Issue by Samicelus** [NetEase/pomelo#793]
I go following error when using "npm install pomelo -g" in cmd command line:

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\
node_modules\npm\bin\npm-cli.js" "install" "pomelo" "-g"
npm ERR! node v4.2.2
npm ERR! npm  v2.14.7

npm ERR! version not found: pomelo-rpc@0.4.11
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     https://github.com/npm/npm/issues

npm ERR! Please include the following file with any support request:
npm ERR!     D:\pomelo\npm-debug.log

It seems that there are some problems with the package.json in your release, thank you!

**Comment by islq** [comment]
npm ERR! No compatible version found: pomelo-rpc@0.4.11
npm ERR! Valid install targets:
npm ERR! 1.0.2, 1.0.1, 1.0.0, 0.4.10, 0.4.9, 0.4.8, 0.4.7, 0.4.6, 0.4.5, 0.4.4, 0.4.3, 0.4.2, 0.4.1, 0.4.0, 0.3.3, 0.3.2, 0.3.1, 0.3.0, 0.2.16, 0.2.15, 0.2.14, 0.2.13, 0.2.12, 0.2.11, 0.2.10, 0.2.9, 0.2.7, 0.2.6, 0.2.5, 0.2.4, 0.2.3, 0.2.2, 0.2.1, 0.2.0, 0.1.6, 0.1.5, 0.1.4, 0.1.3, 0.1.2, 0.1.1, 0.1.0, 0.0.11

**Comment by py8765** [comment]
try again

**Comment by trinhvietnam** [comment]
you should not install pomelo in windows, i tried but i failed. Other solution is clone folder (lib) pomelo was install in ubuntu and paste it to folder node_modules of your project, it like this picture 
![pomelo](https://cloud.githubusercontent.com/assets/5329583/12356318/8c87b992-bbd4-11e5-8fda-0b5877f8b209.png)
And now you clone some sample project of pomelo to try it, i successed with above solotion.
Here is pomelo was complied from ubuntu that i used
https://drive.google.com/file/d/0B-hxz6ee5n8_TEtzdllzZGo5bjg/view?usp=sharing
