### ISSUE TITLE
The web client disconnected sometimes because of  'server heartbeat timeout' .

### ISSUE THREAD

**Issue by 7demo** [NetEase/pomelo#798]
The web client disconnected sometimes.  The config was ——

`app.configure('production|development', 'connector', function(){
    app.set('connectorConfig', {
        connector: pomelo.connectors.hybridconnector,
        heartbeat: 3,
        useDict: true,
        useProtobuf: true
    });
});`

After that, I know the reason may be the bad network. So , i set 'heartbeat: 20'. However It still happens occasionally . 

Now I realize that it can't be avoided . So  I hope konw how to catch the disconnect then try to reconnect the server.

Who can give me some tips?  Thanks !

**Comment by fantasyni** [comment]
on('disconnect') event ?
