### ISSUE TITLE
安装pomelo失败

### ISSUE THREAD

**Issue by joymzy** [NetEase/pomelo#800]
npm ERR! Linux 2.6.32-431.23.3.el6.x86_64
npm ERR! argv "/usr/local/node/bin/node" "/usr/bin/npm" "install" "pomelo" "-d"
npm ERR! node v0.12.4
npm ERR! npm  v2.10.1
npm ERR! code ELIFECYCLE

npm ERR! toobusy@0.2.4 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
[npm-debug.txt](https://github.com/NetEase/pomelo/files/132159/npm-debug.txt)

npm ERR! Failed at the toobusy@0.2.4 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the toobusy package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
[npm-debug.txt](https://github.com/NetEase/pomelo/files/132158/npm-debug.txt)

npm ERR! You can get their info via:

npm ERR!     npm owner ls toobusy
npm ERR! There is likely additional logging output above.

**Comment by joymzy** [comment]
pomelo不支持CentOS吗？

**Comment by skyblue** [comment]
话说.有没有人能把这几个依赖问题给处理下, 安装问题基本都是这方面引起的.

**Comment by kunth** [comment]
npm install 前有管理员权限吗

**Comment by hottredpen** [comment]
我的是用centos
后来找到这篇文章解决了
“CentOS 升级 gcc 和 g++ 的方法”
http://www.wengweitao.com/centos-sheng-ji-gcc-he-g-de-fang-fa.html
