### ISSUE TITLE
How to use Auto scaling with Pomelo !!

### ISSUE THREAD

**Issue by creatiosoft** [NetEase/pomelo#802]
Hello Everyone

We are using AWS to deploy pomelo but once we are getting huge traffic pomelo kick outing some instance that causing loss in term of revenue & users.I would like to discuss what is best way to implement autoscaling in pomelo with AWS server.

**Comment by pipi32167** [comment]
Back end server is stateless.

**Comment by maxc0d3r** [comment]
Does it imply that we can start connector, logic, gate servers independently without being concerned about master?
