### ISSUE TITLE
可以跨server得到其他用户的session信息吗

### ISSUE THREAD

**Issue by HeChenTao** [NetEase/pomelo#803]
在同一个房间里的用户，分配到了不同的conntetor-server，在踢人的时候，需要获得被踢用户的session，可以做到吗

**Comment by 359056163** [comment]
可以！你需要查看一下，pomelo里的一些服务对象，里面就有这方面的。去看一下文档吧

**Comment by fantasyni** [comment]
要在connector上写rpc接口，其它服务器来调用这个connector  
当然，你需要自己维护 uid, sid 的关系
