### ISSUE TITLE
The best way to reconnect player with existing session again

### ISSUE THREAD

**Issue by amrendraw3** [NetEase/pomelo#804]
I want to know the best way to reconnect a user in the existing session. The case will be as follows:

**1. Player connect to pomelo and create a session with unique playerId**
**2. Player got internet disconnection issue to his/her device**
**3. Player try to reconnect once internet has properly connected into his/her device**
**4. I want this player to connect with the same existing session**

Some of the pomelo methods i tried -

*1. Unbinding session:
- session.unbind(playerId)
- session.bind(playerId)

*2. Removing existing session
- sessionServices.remove(_existing_sesion_id_)
- session.bind(playerId)

*3. Kicking existing session
-  Kick existing session 
- session.bind(playerId)

I want as simple if player can me merged with existing session while second login (connection) attempt. I don't want to kill existing session as i have some different operations to be performed on **session close** event. I also tried to modify config for sioconnector in my app.js file by increasing the closeTimeout value along with above methods but it didn't work as expected.

Please let me know if there is any existing solution provided by pomelo. Thanks !!

**Comment by dubanflorin** [comment]
I think session close is fired automatically when the client is disconnected. This means the previous session no longer exists.

**Comment by amrendraw3** [comment]
I need to handle the request as well when client does not close his/her app (disconnect) and retry for login. Did you get what i am saying here?

**Comment by dubanflorin** [comment]
You practically have 2 sessions. I don't understand why you want to handle them as one session.
That's probably the reason why there are no methods to achieve this in the pomelo api.
