### ISSUE TITLE
channelService的sendMessageByGroup的group会话保持问题

### ISSUE THREAD

**Issue by moloxiao** [NetEase/pomelo#806]
类见https://github.com/NetEase/pomelo/blob/master/lib/common/service/channelService.js的sendMessageByGroup方法，方法在执行的整个生命周期中传入的参数group是可能发生变化的，比如一个新玩家进入房间，用channel广播一天通知，在新玩家还没有调用channel的add方法前调用channel的pushMessage方法，再调用channel的add方法，有可能导致pushMessage的消息group信息在发送的时候已经相对于传入时变更，对于group参数为什么没有在进入的时候做参数不可变的必要操作（比如深拷贝或者闭包都可以）？

**Comment by fantasyni** [comment]
我先记一下，先关了
