### ISSUE TITLE
pomelo can't be publish by Jenkins?

### ISSUE THREAD

**Issue by shadow0162** [NetEase/pomelo#807]
pomelo console need to try connect to 127.0.0.1:3005,And then callback to console.
When Jenkins setup server via SSH, there is no callback and being waiting for result. 
how to CI pomelo by Jenkins?

在使用Jenkins部署pomelo的时候，pomelo命令行的运行方式不能使用。因为Jenkins无法等待获知，pomelo start执行结束的返回。该如何解决？

**Comment by pipi32167** [comment]
试一下pm2

**Comment by shadow0162** [comment]
超时后，强制结束吧
