### ISSUE TITLE
Hybrid Connectors - Does not handle the data of ipv6 Client

### ISSUE THREAD

**Issue by episanchez** [NetEase/pomelo#811]
When my ipv6 client send data to my connectors, this one timeout and in my log, i have the next message : 'connection is timeout without communication, the remote ip is ... && port is ...'

**Comment by vannambui** [comment]
Me too! Pls fix this issue!

**Comment by fantasyni** [comment]
i see, ipv6 support ～_～

**Comment by lwcbest** [comment]
so far, dose pomelo support ipv6?

**Comment by rathore-digvijay** [comment]
Facing the same issue. 
`[2020-04-06 12:40:42.227] [WARN] pomelo - [/home/info/slots_gameserver/node_modules/pomelo/lib/connectors/hybrid/switcher.js] connection is timeout without communication, the remote ip is ::ffff:103.105.96.105 && port is 23868`

**Comment by lwcbest** [comment]
> Facing the same issue.
> `[2020-04-06 12:40:42.227] [WARN] pomelo - [/home/info/slots_gameserver/node_modules/pomelo/lib/connectors/hybrid/switcher.js] connection is timeout without communication, the remote ip is ::ffff:103.105.96.105 && port is 23868`

I had resolved this issue. you can add my wechat: liuweichang9000

**Comment by rathore-digvijay** [comment]
> > Facing the same issue.
> > `[2020-04-06 12:40:42.227] [WARN] pomelo - [/home/info/slots_gameserver/node_modules/pomelo/lib/connectors/hybrid/switcher.js] connection is timeout without communication, the remote ip is ::ffff:103.105.96.105 && port is 23868`
> 
> I had resolved this issue. you can add my wechat: liuweichang9000

If its possible will you let us know over here. As it will help others also in the community.
