### ISSUE TITLE
hybridconnector设置心跳遇到的问题

### ISSUE THREAD

**Issue by 1050676515** [NetEase/pomelo#814]
我给connector的heartbeat设置为1，当客户端连接上来后，我将客户端的网络禁止掉，查看log，发现服务器一直不会主动关闭这个session，超时机制没生效？
一直要到客户端重新恢复网络后，服务器才会将这个session关闭

**Comment by 1050676515** [comment]
我看源码发现了问题在哪
pomelo的心跳是由客户端发起的，服务端被动响应，这种做法没有什么作用啊
客户端要是不给服务器发心跳包（像上面的直接断网），服务器也没去清理这个session

**Comment by fantasyni** [comment]
合并了，多谢
