### ISSUE TITLE
How to debug server crash !

### ISSUE THREAD

**Issue by saruno** [NetEase/pomelo#820]
Hi all,

I have a problem when launch my pomelo server. My game has three servers : gate, connector, game (backend).
When i test my game with about 600 CCU, server connector and game was disconnected. When i saw in crash.log i saw that : 

[2016-04-02 14:53:43.067] [INFO] crash-log - [32m[\game-server\node_modules\pomelo\lib\master\master.js] [39m[connector],[connector-server-1],[1459583623067],[disconnect]
[2016-04-02 14:54:43.080] [INFO] crash-log - [32m[\game-server\node_modules\pomelo\lib\master\master.js] [39m[game],[game],[1459583683080],[disconnect]

I check Heap size with command "pomelo list", i saw that : 

connector-server-1 rss(133.30M) heapTotal(63.38 MB) heapUsed(34.01 MB)
game rss(122.72M) heapTotal(67.30MB) heapUsed(38.02MB)

----> Memory is not Big

What is the cause of server terminated ?? How to debug server crash reason on Pomelo ?

**Comment by saruno** [comment]
I launch server on Windows 7 64bit, Ram 4GB, nodejs v0.10.3

**Comment by hikaru7641** [comment]
1. in file app.js, you add code:
process.on('uncaughtException', function(err) {
	console.error('Caught exception: ' , err, err.stack);
});

show error why die connector?

**Comment by saruno** [comment]
I tried process.on('uncaughtException', function(err)) {} and no error out to console !

I think my server got memory leak error, but i don't know how to debug ?

**Comment by hikaru7641** [comment]
maybe you have error "ECONNRESET" so Connector-server will crash, 

you try change code in pomelo/lib/hybridconnector.js:
this.tcpServer = net.createServer();
===>

// edit by nes
this.tcpServer = net.createServer(function(socket){
	socket.on('error', function(err2) {
    	console.error('tcpServer ERROR:', err2);
  });
});

hope help to you
