### ISSUE TITLE
pomelo 例子 chatofpomelo-websocket 报错

### ISSUE THREAD

**Issue by tqknight1984** [NetEase/pomelo#822]
npm info install pomelo-rpc@0.4.3
npm info postinstall socket.io@0.9.16
npm info postinstall pomelo-rpc@0.4.3
npm info postinstall ws@0.4.25
npm ERR! Linux 2.6.32-358.6.2.el6.x86_64
npm ERR! argv "/data/app/node-v4.4.2-linux-x64/bin/node" "/data/app/node-v4.4.2-linux-x64/bin/npm" "install" "-d"
npm ERR! node v4.4.2
npm ERR! npm  v2.15.0
npm ERR! code ELIFECYCLE

npm ERR! heapdump@0.2.9 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the heapdump@0.2.9 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the heapdump package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs heapdump
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls heapdump
npm ERR! There is likely additional logging output above.
npm info preuninstall heapdump@0.2.9
npm info uninstall heapdump@0.2.9
npm info postuninstall heapdump@0.2.9
npm info preuninstall pomelo-admin@0.4.1
npm info uninstall pomelo-admin@0.4.1
npm info postuninstall pomelo-admin@0.4.1
npm info preuninstall pomelo@1.0.4
npm info uninstall pomelo@1.0.4
npm info postuninstall pomelo@1.0.4

npm ERR! Please include the following file with any support request:
npm ERR!     /data/app/chatofpomelo-websocket/game-server/npm-debug.log
============   game-server npm installed ============
npm info it worked if it ends with ok
npm info using npm@2.15.0
npm info using node@v4.4.2
npm WARN package.json chatofpomelo@0.0.1 No description
npm WARN package.json chatofpomelo@0.0.1 No repository field.
npm WARN package.json chatofpomelo@0.0.1 No README data
npm WARN package.json chatofpomelo@0.0.1 No license field.
npm info preinstall chatofpomelo@0.0.1
npm info package.json express@3.4.0 No license field.
npm info build /data/app/chatofpomelo-websocket/web-server
npm info linkStuff chatofpomelo@0.0.1
npm info install chatofpomelo@0.0.1
npm info postinstall chatofpomelo@0.0.1
npm info prepublish chatofpomelo@0.0.1
npm info ok 
============   web-server npm installed ============

以上是
$ sh npm-install.sh
这一步的时候报错，求解决办法。

**Comment by tqknight1984** [comment]
try

curl -L https://www.npmjs.org/install.sh | sudo npm_install=1.4.12 sh

**Comment by qgqceo** [comment]
有没有解决？
