### ISSUE TITLE
聊天例子 执行 sh npm-install.sh 报错

### ISSUE THREAD

**Issue by tqknight1984** [NetEase/pomelo#826]
[app@VM_42_158_centos mecha]$ sh npm-install.sh
npm info it worked if it ends with ok
npm info using npm@3.8.7
npm info using node@v4.4.3
npm info attempt registry request try #1 at 2:24:17 PM
npm http request GET https://registry.npmjs.org/pomelo
npm http 304 https://registry.npmjs.org/pomelo
npm info attempt registry request try #1 at 2:24:18 PM
npm http request GET https://registry.npmjs.org/pomelo-admin
npm http 304 https://registry.npmjs.org/pomelo-admin
npm info attempt registry request try #1 at 2:24:18 PM
npm http request GET https://registry.npmjs.org/pomelo-scheduler
npm info attempt registry request try #1 at 2:24:18 PM
npm http request GET https://registry.npmjs.org/pomelo-logger
npm info attempt registry request try #1 at 2:24:18 PM
npm http request GET https://registry.npmjs.org/heapdump
npm http 304 https://registry.npmjs.org/pomelo-scheduler
npm http 304 https://registry.npmjs.org/pomelo-logger
npm http 304 https://registry.npmjs.org/heapdump
npm info lifecycle heapdump@0.2.9~preinstall: heapdump@0.2.9
npm info lifecycle pomelo-logger@0.1.2~preinstall: pomelo-logger@0.1.2
npm info lifecycle pomelo-scheduler@0.3.8~preinstall: pomelo-scheduler@0.3.8
npm info lifecycle pomelo-admin@0.4.1~preinstall: pomelo-admin@0.4.1
npm info lifecycle pomelo@1.0.4~preinstall: pomelo@1.0.4
npm info linkStuff heapdump@0.2.9
npm info linkStuff pomelo-logger@0.1.2
npm info linkStuff pomelo-scheduler@0.3.8
npm info linkStuff pomelo-admin@0.4.1
npm info linkStuff pomelo@1.0.4
npm info lifecycle heapdump@0.2.9~install: heapdump@0.2.9

> heapdump@0.2.9 install /data/app/mecha/game-server/node_modules/heapdump
> node-gyp rebuild

gyp info it worked if it ends with ok
gyp info using node-gyp@3.3.1
gyp info using node@4.4.3 | linux | x64
gyp info spawn /usr/bin/python2
gyp info spawn args [ '/data/app/node-v4.4.3-linux-x64/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/data/app/mecha/game-server/node_modules/heapdump/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/data/app/node-v4.4.3-linux-x64/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/app/.node-gyp/4.4.3/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/home/app/.node-gyp/4.4.3',
gyp info spawn args   '-Dnode_gyp_dir=/data/app/node-v4.4.3-linux-x64/lib/node_modules/npm/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=node.lib',
gyp info spawn args   '-Dmodule_root_dir=/data/app/mecha/game-server/node_modules/heapdump',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
make: Entering directory `/data/app/mecha/game-server/node_modules/heapdump/build'
  CXX(target) Release/obj.target/heapdump/src/heapdump.o
../src/heapdump.cc: In function 'bool heapdump::WriteSnapshotHelper(v8::Isolate*, const char*)':
../src/heapdump.cc:158:74: error: no matching function for call to 'v8::HeapProfiler::TakeHeapSnapshot(v8::Local<v8::String>)'
       isolate->GetHeapProfiler()->TakeHeapSnapshot(String::Empty(isolate)));
                                                                          ^
../src/heapdump.cc:36:25: note: in definition of macro 'COMPAT'
 # define COMPAT(_, exp) exp
                         ^
../src/heapdump.cc:158:74: note: candidate is:
       isolate->GetHeapProfiler()->TakeHeapSnapshot(String::Empty(isolate)));
                                                                          ^
../src/heapdump.cc:36:25: note: in definition of macro 'COMPAT'
 # define COMPAT(_, exp) exp
                         ^
In file included from ../src/heapdump.cc:23:0:
/home/app/.node-gyp/4.4.3/include/node/v8-profiler.h:486:23: note: const v8::HeapSnapshot* v8::HeapProfiler::TakeHeapSnapshot(v8::ActivityControl*, v8::HeapProfiler::ObjectNameResolver*)
   const HeapSnapshot* TakeHeapSnapshot(
                       ^
/home/app/.node-gyp/4.4.3/include/node/v8-profiler.h:486:23: note:   no known conversion for argument 1 from 'v8::Local<v8::String>' to 'v8::ActivityControl*'
make: *** [Release/obj.target/heapdump/src/heapdump.o] Error 1
make: Leaving directory`/data/app/mecha/game-server/node_modules/heapdump/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/data/app/node-v4.4.3-linux-x64/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 2.6.32-504.30.3.el6.x86_64
gyp ERR! command "/data/app/node-v4.4.3-linux-x64/bin/node" "/data/app/node-v4.4.3-linux-x64/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /data/app/mecha/game-server/node_modules/heapdump
gyp ERR! node -v v4.4.3
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok 
npm info lifecycle heapdump@0.2.9~install: Failed to exec install script
chatofpomelo-websocket@0.0.1 /data/app/mecha/game-server
`-- (empty)

npm WARN chatofpomelo-websocket@0.0.1 No description
npm WARN chatofpomelo-websocket@0.0.1 No repository field.
npm WARN chatofpomelo-websocket@0.0.1 No license field.
npm ERR! Linux 2.6.32-504.30.3.el6.x86_64
npm ERR! argv "/data/app/node-v4.4.3-linux-x64/bin/node" "/data/app/node-v4.4.3-linux-x64/bin/npm" "install" "-d"
npm ERR! node v4.4.3
npm ERR! npm  v3.8.7
npm ERR! code ELIFECYCLE

npm ERR! heapdump@0.2.9 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the heapdump@0.2.9 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the heapdump package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs heapdump
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls heapdump
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /data/app/mecha/game-server/npm-debug.log
npm ERR! code 1
============   game-server npm installed ============
npm info it worked if it ends with ok
npm info using npm@3.8.7
npm info using node@v4.4.3

**Comment by daggerjames** [comment]
git有先checkout到'tutorial-starter'么？
