### ISSUE TITLE
怎么把socket.io升级到高级的版本呀？

### ISSUE THREAD

**Issue by linmengjie** [NetEase/pomelo#832]
怎么把socket.io升级？

**Comment by 359056163** [comment]
目前，好像 还不行。因为 高版本的 socket.io与低版本的socket.io api 差异比较大。
想升级，请手动实现 sioconnector,siosocket....
把pomelo 克隆下来 当前的版本，然后 切换到 2.x 分支。

**Comment by linmengjie** [comment]
2.0现在还跑不起来。。。
