### ISSUE TITLE
这个库是打算废弃了，还是在开发2.0，没时间维护？

### ISSUE THREAD

**Issue by YaoHuiJi** [NetEase/pomelo#833]
谢谢提供这么棒的项目。问这个没别的意思哇，我是新项目打算用这个，就想心里有个数。

**Comment by 359056163** [comment]
说是2.0 要等到年底

**Comment by cnlamplighter** [comment]
……在楼主发贴之前，2.0就有了

**Comment by violet-day** [comment]
@cnlamplighter 2.0现在有文档了嘛

**Comment by cnlamplighter** [comment]
没，在等

**Comment by YaoHuiJi** [comment]
@cnlamplighter 嗯，今天再新机器npm 安装，居然直接就装成2.0了。。。有用的的么，能从1.2.2无缝升级么，还是跟1.2.2挺大的？

**Comment by markchou** [comment]
也想知道
