### ISSUE TITLE
pomelo 2.0的一个BUG

### ISSUE THREAD

**Issue by ljhsai** [NetEase/pomelo#835]
lib/server/server.js,  使用了use strict
msg为string情况, 在msg.**route** = originMsg.route 这一处出问题, 程序异常.

**Comment by lichungod** [comment]
应该怎么改，请教
我目前是注释掉了这句，暂时没发现什么影响

**Comment by ljhsai** [comment]
先注释呗，这里只是用来记录route的，不影响其他。
