### ISSUE TITLE
Error('pomelo 2.0 cannot start without monitor, you can choose zookeeper or redis as monitor server.');

### ISSUE THREAD

**Issue by ccdlvc** [NetEase/pomelo#836]
Hi all

I just update pomelo to version 2.0 and got the Error('pomelo 2.0 cannot start without monitor, you can choose zookeeper or redis as monitor server.'); 

Can anyone tell me how to fix, and note to document. 

Thanks a lot

**Comment by 359056163** [comment]
npm install pomelo-zookeeper

**Comment by NextZeus** [comment]
mac os need to install zookeeper .

**Comment by NextZeus** [comment]
Install the App

Press Command+Space and type Terminal and press enter/return key.
Run in Terminal app:
ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)" < /dev/null 2> /dev/null
and press enter/return key. Wait for the command to finish.
Run:
brew install zookeeper
Done! You can now use zookeeper.
