### ISSUE TITLE
pomelo only have creat function, ?

### ISSUE THREAD

**Issue by regt8337** [NetEase/pomelo#838]
# pomelo --help

  Usage: pomelo [options] [command]

  Commands:

```
init [path]            create a new application
*
```

  Options:

```
-h, --help     output usage information
-V, --version  output the version number
```

---

nodejs v4.4.4； pomelo 2.0
why?

**Comment by regt8337** [comment]
Distributor ID: Ubuntu
Description:    Ubuntu 14.04.2 LTS
Release:        14.04

# nodejs -v
v4.4.4
# npm -v
2.15.1
# pomelo --version1.2.0
----------------------------------------------------------------------------------------
ok

**Comment by bruno1308** [comment]
same
