### ISSUE TITLE
发送含有Emoji的消息时，客户端报错或者出现乱码

### ISSUE THREAD

**Issue by maifine** [NetEase/pomelo#842]
发送含有Emoji的消息时，客户端报错或者出现乱码，这个问题如何解决？

**Comment by 359056163** [comment]
你的emoji 表达式 是什么样的？

**Comment by maifine** [comment]
服务端向客户端发这样的消息：
var channelService = this.app.get('channelService');
	var param = {
		msg: '😂 😃',
		msgType:msg.type,
		fromUid:uid,
		fromNickname: nickname,
		channel:msg.channel,
		createtime:new Date()
	};

客户端收到的是乱码：
{"msg":"ߘ ߘâ,"msgType":0,"fromUid":"433","fromNickname":"麦子2","channel":"0","createtime":"2016-05-21T11:12:59.613Z"}

但是，客户端向服务端发送的请求，服务端确定正常接收emoji:
handler.send = function(msg, session, next) {
	console.log(msg.content);
}

麻烦帮忙看看，pomelo的版本是1.2.2
客户端用的是聊天室的列子带的库。
谢谢

**Comment by maifine** [comment]
稍微研究了下源码，发现服务端用的是nodejs的Buffer,而客户端用的是Uint8Array，所以有这样的情况，希望能提供解决方法。

**Comment by 359056163** [comment]
Nodejs API Buffer 模块提供了以下方法
`buf.writeUInt8(value, offset[, noAssert])`
希望有帮助

**Comment by maifine** [comment]
暂时将客户端build.js 中的这句
return JSON.parse(Protocol.strdecode(msg.body));
换成
return JSON.parse(new TextDecoder("utf-8").decode(msg.body));
解决，但是这是在未启用Protobuf压缩时有效，自己还没研究Protobuf的客户端解析方法，期待对Protobuf比较熟的同学提供解决方案。

**Comment by fantasyni** [comment]
@maifine 可以pull request啊
