### ISSUE TITLE
【重要】pomelo 2.0 是内部测试版本，不对外提供使用，大家还是使用之前1.2.x 版本

### ISSUE THREAD

**Issue by zhangmin510** [NetEase/pomelo#845]

**Comment by xFurther** [comment]
兄弟，VS2015的编译器用npm install pomelo -g 报各种编译问题：
  C:\Users\xfurther\.node-gyp\4.4.4\include\node\v8.h(2081): note: 参见“v8::String”的声明
C:\Users\xfurther\AppData\Roaming\npm\node_modules\pomelo\node_modules\pomelo-admin\node_modules\socket.io-client\node_
modules\ws\node_modules\nan\nan.h(409): error C2065: “ExternalAsciiStringResource”: 未声明的标识符 [C:\Users\xfurther\AppData\
Roaming\npm\node_modules\pomelo\node_modules\pomelo-admin\node_modules\socket.io-client\node_modules\ws\build\bufferuti
l.vcxproj]
C:\Users\xfurther\AppData\Roaming\npm\node_modules\pomelo\node_modules\pomelo-admin\node_modules\socket.io-client\node_
modules\ws\node_modules\nan\nan.h(409): error C2065: “resource”: 未声明的标识符 [C:\Users\xfurther\AppData\Roaming\npm\node_mo
dules\pomelo\node_modules\pomelo-admin\node_modules\socket.io-client\node_modules\ws\build\bufferutil.vcxproj]
C:\Users\xfurther\AppData\Roaming\npm\node_modules\pomelo\node_modules\pomelo-admin\node_modules\socket.io-client\node_
modules\ws\node_modules\nan\nan.h(409): error C2433: “NanNew”: 不允许在数据声明中使用“__forceinline” [C:\Users\xfurther\AppData\Ro
aming\npm\node_modules\pomelo\node_modules\pomelo-admin\node_modules\socket.io-client\node_modules\ws\build\bufferutil.
vcxproj]
C:\Users\xfurther\AppData\Roaming\npm\node_modules\pomelo\node_modules\pomelo-admin\node_modules\socket.io-client\node_
modules\ws\node_modules\nan\nan.h(409): error C2365: “NanNew”: 重定义；以前的定义是“函数” [C:\Users\xfurther\AppData\Roaming\npm\no
de_modules\pomelo\node_modules\pomelo-admin\node_modules\socket.io-client\node_modules\ws\build\bufferutil.vcxproj]
C:\Users\xfurther\AppData\Roaming\npm\node_modules\pomelo\node_modules\pomelo-admin\node_modules\socket.io-client\node_
modules\ws\node_modules\nan\nan.h(409): error C2448: “NanNew”: 函数样式初始值设定项类似函数定义 [C:\Users\xfurther\AppData\Roaming\npm\
node_modules\pomelo\node_modules\pomelo-admin\node_modules\socket.io-client\node_modules\ws\build\bufferutil.vcxproj]
C:\Users\xfurther\AppData\Roaming\npm\node_modules\pomelo\node_modules\pomelo-admin\node_modules\socket.io-client\node_
modules\ws\node_modules\nan\nan.h(430): error C2766: 显式专用化；已定义“v8::Local<v8::StringObject> NanNew<v8::StringObject,v8::
Local<v8::String>>(v8::Local<v8::String>)” [C:\Users\xfurther\AppData\Roaming\npm\node_modules\pomelo\node_modules\pome

**Comment by felipejfc** [comment]
is it not stable yet? does it have any known bugs?

**Comment by markchou** [comment]
pomelo 2.0 什么时候可以发布啊
