### ISSUE TITLE
Pomelo Treasure on VPS server

### ISSUE THREAD

**Issue by hktplsm** [NetEase/pomelo#847]
Hi, so i installed Treasures on a simple VPS and i'm stuck : nothing happens when i enter my name and press start.

Here is the console log : 
WebSocket connection to 'ws://127.0.0.1:3014/' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED
socket error:  Event {isTrusted: true, type: "error", target: WebSocket, currentTarget: WebSocket, eventPhase: 2…}
socket close:  CloseEvent {wasClean: false, code: 1006, reason: "", type: "close", target: WebSocket…}

Is the configuration different when using a remote server ?

**Comment by fantasyni** [comment]
host should not be the localhost
