### ISSUE TITLE
服务器启动后的初始化工作，应该写在哪里？

### ISSUE THREAD

**Issue by wf744** [NetEase/pomelo#850]
每个服务器启动后，我都需要做一些初始化工作，现在写在
app.start(function(){
....
})

但是发现有时候服务器的remote部分的rpc函数还没有初始化完毕，然后我做的初始化工作就会偶尔出现失败的情况，请问这个服务器启动后的逻辑应该写在哪里？

**Comment by 359056163** [comment]
pomelo 有提供声明周期功能，在对应的server内添加 lifecycle.js，里面有这样几个事件，提前定义好久可以了，beforeStart,afterStart,beforeClose,afterClose，你可以去查看一下 文档。关于方法名 应该有点出入。
