### ISSUE TITLE
消息通过tcp传递有可能直接发送binary data么？

### ISSUE THREAD

**Issue by daggerjames** [NetEase/pomelo#851]
因为需要Broadcast一段音频，然后发现msg是文本格式。即便走的是websocket，也是用protobuf把文本格式压缩为binary data传输。想问有知道的大大们尝试过直接发送binary data么？感觉音频文件用base64压缩好大。。。
现在思路是hack掉Encode的方法，暴露出底层websocket发送binary data的方法给上面。。。有其他建议么？

**Comment by 359056163** [comment]
本来就可以。不仅仅是文本

**Comment by 359056163** [comment]
好奇问一下，如果用protobuf定义一个字段为bytes类型，然后你们在创建一个消息对象时，用buffer或者int64Array存储这段音频。客户端接收时会有什么异常无法解决吗？

**Comment by 359056163** [comment]
我的意思是这样：
message｛
 required bytes voice；
｝
以上是protobuf定义文件
｛
       voice：new Buffer（voicedata）
｝
以上是一个即将被protobuff编译的消息对象。
如果这样做了，编译有异常？还是客户端接收后，解析出来的有问题？

**Comment by suzhijie325** [comment]
可以转为base64,客户端再转回来
