### ISSUE TITLE
各位大大们，node版本6.2.2，pomelo 客户端发送消息 报错

### ISSUE THREAD

**Issue by wangcj10086** [NetEase/pomelo#857]
nodejs 最新版本报 could not find handle invalid data package，
请问下是怎么回事呢？谢谢
回退 版本到 0.10.26可以正常发送，但那个node版本太低了呢

客户端用的是这：
http://blog.csdn.net/jbboy/article/details/32913995

**Comment by markchou** [comment]
Nodejs6 你是怎么把pomelo装上去的

**Comment by Yuki001** [comment]
我就是在用nodejs6 + pomelo1.2.3, 除了几个DeprecationWarning以外,都可以用啊. 估计要重新安装一下pomelo

**Comment by markchou** [comment]
@Yuki001 分享下经验呀

**Comment by losingle** [comment]
我v6.9.1都没有问题，只有几个socket.io的DeprecationWarning
