### ISSUE TITLE
How to send message to another client in another server?

### ISSUE THREAD

**Issue by pizzae** [NetEase/pomelo#858]
In the chat example, you can only private message users within the same channel. How would you do it if you wanted to private message someone in another server, in another channel?

**Comment by mzget** [comment]
Try "channelservice.pushmessage" !
Here is api ref http://pomelo.netease.com/api.html  it would help.

**Comment by pizzae** [comment]
There is only:
Channel.prototype.pushMessage()
and
ChannelService.prototype.pushMessageByUids()

which one do I use?

And in the chat example, "channelService.pushMessageByUids" is the one being used, which is limited to only within 1 server
