### ISSUE TITLE
(node) sys is deprecated. Use util instead. + how to do profiling in pomelo?

### ISSUE THREAD

**Issue by pizzae** [NetEase/pomelo#859]
I get this error:

> "C:\Program Files (x86)\JetBrains\WebStorm 2016.1.3\bin\runnerw.exe" "C:\Program Files\nodejs\node.exe" --harmony --prof --nologfile_per_isolate --logfile=v8-9-07-2016_9-10-46-PM-.log --log-timer-events C:\Users\Admin\AppData\Local\Temp\v8profilerProxy.js
> (node) sys is deprecated. Use util instead.
> [2016-07-09 21:10:46.957] [ERROR] pomelo - [c:\Game Dev Stuff\Projects\idlecards-server\game-server\node_modules\pomelo\lib\application.js] invalid configuration with file path: master
> [2016-07-09 21:10:46.963] [ERROR] pomelo - [c:\Game Dev Stuff\Projects\idlecards-server\game-server\node_modules\pomelo\lib\application.js] invalid configuration with file path: servers
> c:\Game Dev Stuff\Projects\idlecards-server\game-server\node_modules\pomelo\lib\util\appUtil.js:165
>   var serverId = args.id || app.getMaster().id;
> .............................................^
> 
> TypeError: Cannot read property 'id' of undefined
>     at processArgs (c:\Game Dev Stuff\Projects\idlecards-server\game-server\node_modules\pomelo\lib\util\appUtil.js:165:44)
>     at Object.module.exports.defaultConfiguration (c:\Game Dev Stuff\Projects\idlecards-server\game-server\node_modules\pomelo\lib\util\appUtil.js:18:3)
>     at Object.Application.init (c:\Game Dev Stuff\Projects\idlecards-server\game-server\node_modules\pomelo\lib\application.js:63:11)
>     at Object.Pomelo.createApp (c:\Game Dev Stuff\Projects\idlecards-server\game-server\node_modules\pomelo\lib\pomelo.js:76:7)
>     at Object.<anonymous> (c:\Game Dev Stuff\Projects\idlecards-server\game-server\app.js:11:18)
>     at Module._compile (module.js:409:26)
>     at Object.Module._extensions..js (module.js:416:10)
>     at Module.load (module.js:343:32)
>     at Function.Module._load (module.js:300:12)
>     at Module.require (module.js:353:17)
> 
> Process finished with exit code 1

When I try to run the program with v8 profiling using webstorm

This program runs normally though without using the profiling, but then I cannot analyse the program for any memory leaks

This is using a app.js which is very similar to the chat example. The link in the error log takes me to this line:

var app = pomelo.createApp();

Edit:
Also how would I do profiling in pomelo? I've spent a few hours trying to fix this but I haven't been able to, so im looking for other alternatives or other pomelo libraries that may help with profiling

**Comment by tourze** [comment]
Same problem.
