### ISSUE TITLE
Pomelo app kill and remove servers automatically

### ISSUE THREAD

**Issue by amrendraw3** [NetEase/pomelo#862]
**What are the circumstances to kill pomelo app itself?**

The issue I am facing is that, the pomelo kills its own application without throwing any exception. When I try to run command 'pomelo list', it shows no server is running. The app gets close after few hours of running and automatically as well. I have gone through logs generated by pomelo on each server but there were no exception or blockage for the app.

Below are the details that might help you guys:
1. We are using **distributed server structure** of pomelo framework
2. **MongoDB** on different server
3. **Redis** instance on master-server itself
4.  **Pomelo** version 1.2.1

We are also running same architecture for our different multi-player games but haven't gone through such issues ever. Can anybody explain why it might be happening? If you need any other info then please ask for the same.

**Comment by whtiehack** [comment]
are you listened on the process `uncaughtException` event?
