### ISSUE TITLE
disconnection problem

### ISSUE THREAD

**Issue by Neimd** [NetEase/pomelo#863]
I operate the 'connector server' and the 'game server'.
When the client requests 'game.handler.entry', the game server makes player object, and manages the player by pushing in the 'pool'.
When I receive session “closed” event on the connector, I rpc invoke the game server and pop the pool which manages the player.
The problem is when the client request 'game.handler.entry'. and disconnects the socket right away, the session closes before entry logic, and therefore in the game server,  a zombie player exists in the pool
In this case, what would be a useful way to get rid of the zombie player?

//////
[2016-07-26 19:07:45.363] [INFO] console - connector-server-4 listen session closed event. start player leave process.
[2016-07-26 19:07:45.494] [INFO] console - connector-server-4 player leave process has error. [ game-server-5 ] 355 player is not existed in pool.
[2016-07-26 19:07:45.662] [INFO] console - game-server-5. 355 player request entry game.
[2016-07-26 19:07:45.662] [INFO] console - game-server-5. 355 player added to pool.

**Comment by thr0wn** [comment]
You're dealing with a race condition, a well known concurrency issue. Developers are led to believe that nodejs programming isn't subject to race conditions as it is 'single thread', but it is a mistake. In fact, presume the execution order of asynchronous code could lead to race conditions.
One approach to solve this issue is to use semaphore/queue to access your pool. In other words, game.handler.entry and the rpc method invoked on closed event must be queued to ensure the execution order.

Example using promises:
```javascript
// Dependencies: npm install promise-queue q
var Queue = require('promise-queue');
Queue.configure(require('q').Promise);
var maxConcurrent = 1;
var maxQueue = Infinity;
var queue = new Queue(maxConcurrent, maxQueue);

gameHandler.prototype.entry = function(...) {
  queue.add(function () {
    // your code goes here
    // async code must return a promise
  });
};

gameHandler.prototype.rpcInvokedOnCloseEvent = function(...) {
  queue.add(function () {
    // your code goes here
    // async code must return a promise
  });
};
```

Example using semaphores:
```javascript
// Dependencies: npm install semaphore
var capacity = 1;
var sem = require('semaphore')(capacity);

gameHandler.prototype.entry = function(...) {
  sem.take(function () {
    // your code goes here
    // sem.leave() must be called to release the semaphore
  });
};

gameHandler.prototype.rpcInvokedOnClosedEvent = function(...) {
  sem.take(function () {
    // your code goes here
    // sem.leave() must be called to release the semaphore
  });
};
```
