### ISSUE TITLE
handler的构造函数是在什么地方调用的？when and where the constructor of handler is called?

### ISSUE THREAD

**Issue by hzhxyz** [NetEase/pomelo#865]
pomelo 的game-server在什么时候实例化handler或者说调用handler的构造函数？我追踪pomelo的源码，一直没有找到有地方这么做啊！有知道的同学请告诉在哪个文件中，谢谢啊！！

**Comment by hzhxyz** [comment]
是在dictionary吗

**Comment by fantasyni** [comment]
看看 lib/common/service/handlerService.js

**Comment by shudingbo** [comment]
更改 pomelo/lib/service/handlerService.js
1.2.2 文件路径更改为 pomelo/lib/common/service/handlerService.js
```
var Service=function(app, opts){this.app = app;this.handlerMap ={};if(!!opts.reloadHandlers){
      watchHandlers(app,this.handlerMap);}// 下面是新加的
var autoStart = app.get('yz_autoStartHandler');//　在 lifecycle::beforeStartup里增加 的变量控制是否要自动启动
if( autoStart ===true){
      loadHandlers(this.app, app.getServerType(),this.handlerMap);
}
};
```

**Comment by hzhxyz** [comment]
哦，抱歉啊，这几天没上来看。我跟踪代码，发现在dictionary.js（/game-server/node_modules/pomelo/lib/components/dictionary.js, pomelo 1.0.4版本）被加载的时候，会调用/game-server/app/servers/xxx/handler/xxxHandler.js的构造函数：var Handler = function(app) {this.app = app;};。当然也会调用handlerService.js的构造函数，不过在时序和逻辑上两者关联不大。handler在加载的时候会根据server类型的不同加载不同的组件。
而在请求到达的时候会调用handlerService.js的handle函数，而且之前已经加载过的handlerMap会被再加载一次（该handler被第一次访问的时候）。这个现在对我们的业务影响不大，没怎么注意。

**Comment by hzhxyz** [comment]
另外在connector.js（/game-server/node_modules/pomelo/lib/components/connector.js，pomelo 1.0.4版本）中，在第285行有个事件派发（app.event.emit(events.CLOSE_SESSION, session);），然而我没有找到谁处理了这个事件，现在一脸懵逼中……

**Comment by hzhxyz** [comment]
又看了一下代码。当配置了useDict的时候，dictionary才会加载handler，否则不会加载dictionary，更不会在启动的时候加载handler
