### ISSUE TITLE
这个库对初学者来说就是个噩梦

### ISSUE THREAD

**Issue by tinybug** [NetEase/pomelo#866]
文档需要完善的地方还有很多啊，找了半天没找到关于adminServer.json这个配置文件的相关说明，但是不配置它又会报 `server "gate-server-1" "gate" register master failed` 这类错误，完全摸不着头脑。不知道还有没有在对这个库进行维护。

**Comment by sss316** [comment]
不维护了

**Comment by fantasyni** [comment]
就是一个服务器密钥用来验证连接上来的服务器的合法性，按照其它服务器加一行就行了

**Comment by markchou** [comment]
设计还是很好的，还在学习中

**Comment by losingle** [comment]
在adminServer.json中把gate类型加入token

**Comment by fantasyni** [comment]
已经收取到建议，之后会在配置文件头部注明文档的位置
