### ISSUE TITLE
关于gate-server返回的节点信息

### ISSUE THREAD

**Issue by voids** [NetEase/pomelo#870]
之前一直是
{"id":1,"body":{"code":200,"host":"x.x.x.x","port":x}}
我们这边在做用nginx反代，要多台gate-server，昨天还好好的，今天突然就返回
[{"id":1,"body":{"code":200,"host":"x.x.x.x","port":x}}]
咋突然返回对象列表了呢？在什么情况下产生的，我们的客户端实现是别的语言写的，没用sdk，这是个很严重的问题

**Comment by fantasyni** [comment]
现在应该还是{}对象了
