### ISSUE TITLE
频繁出现rpc socket disconnect

### ISSUE THREAD

**Issue by zjl410091917** [NetEase/pomelo#871]
pomelo版本:1.2.0
后端server会经常性的通过channel向client推送消息，从服务器日志看，每天都会出现不少的"rpc socket is disconnect, reason: undefined"提示，导致了推送消息的丢失。
disconnect的连接是后端server与前端server的rpc-client
请问，是否有人遇到过同样的问题，有什么解决方案，谢谢！

**Comment by Yuki001** [comment]
也是时不时出现这种rpc断开的问题,来顶一下,目前不知道是为什么.

**Comment by amsalt** [comment]
同问，出现频率很高

**Comment by zjl410091917** [comment]
只有同问的，出个大婶解答下哇，应该不是个例吧

**Comment by amsalt** [comment]
问题找到了，应该是 ws的版本号和node不兼容导致的，建议如果使用的是node6.0或者node4.0，考虑升级ws到1.1.0。

**Comment by zjl410091917** [comment]
@amsalt 你的意思是说自己将pomelo-rpc里的ws版本提高一下？这个可以复现吗？

**Comment by amsalt** [comment]
pomelo 和 socket.io-client里边的版本号都提高到1.1.0，目前还没发现再出现那个错误，但是有一个 rpc request is timeout 的错误，我再继续跟进下

**Comment by amsalt** [comment]
rpc request is timeout  这个错误也是由于ws版本的问题导致的，所以目前的结论是 将pomelo库以及 socket.io-client库里边的ws版本号提升到1.1.0，可以解决socket disconnect以及rpc request is timeout的问题
