### ISSUE TITLE
关于rpc route 的作用范围

### ISSUE THREAD

**Issue by zyf0330** [NetEase/pomelo#875]
rpc route 会影响客户端向目标服务器的请求吗？
例如，play 服务器上有自定义路由，客户端直接请求 play 上的 handler，应该是经由 connector 来进行 rpc 调用的，那么我认为会经过自定义路由。是否是这样呢？
我这么做的目的是，通过路由，使每个 channel 整体放在一个服务器上。

**Comment by fantasyni** [comment]
是这样的

**Comment by zyf0330** [comment]
谢谢啊。
还有一个问题，如果我有一台 connector，那我可以把路由表放到它上面，如果我有两台，我就得做同步了吧。前提是我有多台 play 服务器。
另外，app.set 的这个值只存在于当前服务器上的是吗？那么我 play 上的 channel 如果排空了，然后用 rpc 通知 connector 来移除这条路由，这样合理吗？

**Comment by fantasyni** [comment]
是的，路由信息可以记录在redis上面，我们内部都是这么做的  
其它mmo类的服务器一般都有一个master节点来做这个事情
