### ISSUE TITLE
[ERROR] console - (node:12584) DeprecationWarning: process.EventEmitter is deprecated. Use require('events') instead.

### ISSUE THREAD

**Issue by liangmuren** [NetEase/pomelo#884]
用的是nodejs 6.2.0 pomelo 1.2.3
console里出现这样的红字是什么原因呢？

**Comment by backlost** [comment]
+1 同遇到。

socket.io用的是老版本，感觉应该升级一下。。

**Comment by linxiaobai** [comment]
windows下装的7.4.0版本的nodejs也遇到类似的问题，提示EventEmitter.prototype;错误，没有定义，将process.EventEmitter;替换成require('events') ;就没有报错，但是很蛋疼。看了一下https://nodejs.org/dist/ 历史版本的doc，好像很早就替换了。。[pic](http://7u2mp7.com1.z0.glb.clouddn.com/QQ%E6%88%AA%E5%9B%BE20170118140917.jpg)

**Comment by fantasyni** [comment]
已经更新了，伙伴们
