### ISSUE TITLE
Install problem with node-gyp rebuild

### ISSUE THREAD

**Issue by ruttydm** [NetEase/pomelo#885]
I can't install pomelo and i've read all the similar issues but they didn't help me.

My error is :

> sudo npm install pomelo
> 
> > heapdump@0.2.9 install /home/ruttydm/Dropbox/CODING/node-poker-stack/game-server/node_modules/pomelo-admin/node_modules/heapdump
> > node-gyp rebuild
> 
> make: Entering directory '/home/ruttydm/Dropbox/CODING/node-poker-stack/game-server/node_modules/pomelo-admin/node_modules/heapdump/build'
>   CXX(target) Release/obj.target/heapdump/src/heapdump.o
> ../src/heapdump.cc: In function ‘bool heapdump::WriteSnapshotHelper(v8::Isolate*, const char*)’:
> ../src/heapdump.cc:158:74: error: no matching function for call to ‘v8::HeapProfiler::TakeHeapSnapshot(v8::Local<v8::String>)’
>        isolate->GetHeapProfiler()->TakeHeapSnapshot(String::Empty(isolate)));
>                                                                           ^
> ../src/heapdump.cc:36:25: note: in definition of macro ‘COMPAT’
>  # define COMPAT(_, exp) exp
>                          ^
> In file included from ../src/heapdump.cc:23:0:
> /home/ruttydm/.node-gyp/4.2.6/include/node/v8-profiler.h:486:23: note: candidate: const v8::HeapSnapshot* v8::HeapProfiler::TakeHeapSnapshot(v8::ActivityControl*, v8::HeapProfiler::ObjectNameResolver*)
>    const HeapSnapshot* TakeHeapSnapshot(
>                        ^
> /home/ruttydm/.node-gyp/4.2.6/include/node/v8-profiler.h:486:23: note:   no known conversion for argument 1 from ‘v8::Local<v8::String>’ to ‘v8::ActivityControl*’
> heapdump.target.mk:95: recipe for target 'Release/obj.target/heapdump/src/heapdump.o' failed
> make: *** [Release/obj.target/heapdump/src/heapdump.o] Error 1
> make: Leaving directory '/home/ruttydm/Dropbox/CODING/node-poker-stack/game-server/node_modules/pomelo-admin/node_modules/heapdump/build'
> gyp ERR! build error 
> gyp ERR! stack Error: `make` failed with exit code: 2
> gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/node-gyp/lib/build.js:276:23)
> gyp ERR! stack     at emitTwo (events.js:87:13)
> gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
> gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
> gyp ERR! System Linux 4.4.0-45-generic
> gyp ERR! command "/usr/bin/nodejs" "/usr/local/bin/node-gyp" "rebuild"
> gyp ERR! cwd /home/ruttydm/Dropbox/CODING/node-poker-stack/game-server/node_modules/pomelo-admin/node_modules/heapdump
> gyp ERR! node -v v4.2.6
> gyp ERR! node-gyp -v v3.4.0
> gyp ERR! not ok 
> poker-game-stack-server@0.0.1 /home/ruttydm/Dropbox/CODING/node-poker-stack/game-server
> └── (empty)
> 
> npm WARN enoent ENOENT: no such file or directory, open '/home/ruttydm/Dropbox/CODING/node-poker-stack/game-server/node_modules/heapdump/package.json'
> npm WARN poker-game-stack-server@0.0.1 No repository field.
> npm WARN poker-game-stack-server@0.0.1 No license field.
> npm ERR! Linux 4.4.0-45-generic
> npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "pomelo"
> npm ERR! node v4.2.6
> npm ERR! npm  v3.5.2
> npm ERR! code ELIFECYCLE
> 
> npm ERR! heapdump@0.2.9 install: `node-gyp rebuild`
> npm ERR! Exit status 1
> npm ERR! 
> npm ERR! Failed at the heapdump@0.2.9 install script 'node-gyp rebuild'.
> npm ERR! Make sure you have the latest version of node.js and npm installed.
> npm ERR! If you do, this is most likely a problem with the heapdump package,
> npm ERR! not with npm itself.
> npm ERR! Tell the author that this fails on your system:
> npm ERR!     node-gyp rebuild
> npm ERR! You can get information on how to open an issue for this project with:
> npm ERR!     npm bugs heapdump
> npm ERR! Or if that isn't available, you can get their info via:
> npm ERR!     npm owner ls heapdump
> npm ERR! There is likely additional logging output above.
> 
> npm ERR! Please include the following file with any support request:
> npm ERR!     /home/ruttydm/Dropbox/CODING/node-poker-stack/game-server/npm-debug.log
> npm ERR! code 1

please help me

**Comment by markchou** [comment]
try node version 0.10~0.12
