### ISSUE TITLE
Disconnect and Reconnect User

### ISSUE THREAD

**Issue by eliteinfo** [NetEase/pomelo#894]
We having issues in our game development with pomelo user disconnect and reconnect.

**Here is exact Problem** 

For ex: There is user having ID A1 who auto disconnect from game.. in this case, pomelo server remove user with ID A1 and automatically create any other random hidden user with random ID in place of that user.

When A1 ID user auto reconnect in game, polemo server assign new user ID to that user. so that user considered as a new user rather than old user who reconnect in game.

Is there any to reconnect user with same session ?

**Comment by fantasyni** [comment]
when with two connectors, for example  
you have to keep uid, sid pair in global place like redis 
then when you login, you can kick other user login in another connector
