### ISSUE TITLE
安装heapdump@0.2.9报错。能否更新一下依赖。

### ISSUE THREAD

**Issue by seeLuck** [NetEase/pomelo#900]
我试了试装最新的0.3.7没问题，好像是不支持新版本的npm。我是npm 4.1.1 , node 4.7。

**Comment by seeLuck** [comment]
我看了一下貌似很多人都有这个问题，如果我回退到node 0.10估计就可以了，因为以前我这么搞过。不过希望能整体更新一下依赖包。

**Comment by seeLuck** [comment]
还有我想在论坛留言的，但是注册出了问题，没有发送验证邮件。

**Comment by fantasyni** [comment]
建议升级最新的Pomelo

**Comment by fantasyni** [comment]
这个c++问题已经没了

**Comment by seeLuck** [comment]
oh确实是没问题了。很强！

我前面出错是还在装以前的那几个demo。

**Comment by seeLuck** [comment]
oh还有，貌似论坛的注册有点问题。我试了两个邮箱都没有发送激活链接。

**Comment by fantasyni** [comment]
这就略尴尬了，囧
