### ISSUE TITLE
update npm version

### ISSUE THREAD

**Issue by Edisoni** [NetEase/pomelo#921]
from npm version
![2017-02-15 10 58 17](https://cloud.githubusercontent.com/assets/10086099/22965236/ac5fd49e-f36d-11e6-8c6a-224b5d806b58.png)
![2017-02-15 10 57 36](https://cloud.githubusercontent.com/assets/10086099/22965237/af835b3c-f36d-11e6-9b7f-bde877ed3a5b.png)

**Comment by cynron** [comment]
these error log is output from socket.io, you can refer the README of it
