### ISSUE TITLE
默认管理服务器端口 DEFAULT_MASTER_PORT 

### ISSUE THREAD

**Issue by zyf0330** [NetEase/pomelo#929]
这个改了 master.json ， pomelo 命令还是按照默认的 3005，看源码也没发现可以自定义端口的地方。重新安装 pomelo 也一样。

**Comment by zyf0330** [comment]
如何修改 DEFAULT_MASTER_PORT 使得 pomelo 命令能按照新的值来？

**Comment by lichungod** [comment]
你用的是哪个版本

**Comment by zyf0330** [comment]
2.2.5

**Comment by zyf0330** [comment]
`start`, `stop` 都没问题，但是 `list` 有问题

**Comment by zyf0330** [comment]
有人吗。

**Comment by zyf0330** [comment]
最近发现 `pomelo list` 和 `pomelo stop` 有 -P 可以设置端口
