### ISSUE TITLE
使用pomelo实现私聊功能的最佳实践？

### ISSUE THREAD

**Issue by danlanxiaohei** [NetEase/pomelo#934]
我想问一下，用pomelo如何实现私聊呢？

我看了一些demo，基本都是客户端连接到服务器后，需要加入某个channel，我想知道如果不加入channel可以聊天吗？

如果必须使用channel的话有两种办法也可以实现:
1，所有人用户默认都在一个全局channel里，然后使用channelService.pushMessageByUids来发送私聊消息。
2，给聊天的两个人创建一个房间，比如uid=1和uid=2的房间就是rid="1+2"，然后通过这个房间来发消息。

希望高手指导一下，给出一个最佳实践方案，多谢！

**Comment by danlanxiaohei** [comment]
@fantasyni 大神可以帮我看看吗？

**Comment by fantasyni** [comment]
记录一下uid, sid关系，然后pushMessageByUids直接发就好了

2017-03-09 

nizhenyang 



发件人：danlanxiaohei <notifications@github.com>
发送时间：2017-03-09 11:25
主题：[NetEase/pomelo] 使用pomelo实现私聊功能的最佳实践？ (#934)
收件人："NetEase/pomelo"<pomelo@noreply.github.com>
抄送："Subscribed"<subscribed@noreply.github.com>

我想问一下，用pomelo如何实现私聊呢？
我看了一些demo，基本都是客户端连接到服务器后，需要加入某个channel，我想知道如果不加入channel可以聊天吗？
如果必须使用channel的话有两种办法也可以实现:
1，所有人用户默认都在一个全局channel里，然后使用channelService.pushMessageByUids来发送私聊消息。
2，给聊天的两个人创建一个房间，比如uid=1和uid=2的房间就是rid="1+2"，然后通过这个房间来发消息。
希望高手指导一下，给出一个最佳实践方案，多谢！

**Comment by danlanxiaohei** [comment]
明白了，我试试，多谢
