### ISSUE TITLE
java.io.FileNotFoundException: http://xxxx:3014/socket.io/1/

### ISSUE THREAD

**Issue by 10cl** [NetEase/pomelo#942]
03-24 08:47:57.329 32512-32593/com.toscl.st.myapplication W/System.err: io.socket.SocketIOException: Error while handshaking
03-24 08:47:57.329 32512-32593/com.toscl.st.myapplication W/System.err:     at io.socket.IOConnection.handshake(IOConnection.java:322)
03-24 08:47:57.329 32512-32593/com.toscl.st.myapplication W/System.err:     at io.socket.IOConnection.access$600(IOConnection.java:39)
03-24 08:47:57.329 32512-32593/com.toscl.st.myapplication W/System.err:     at io.socket.IOConnection$ConnectThread.run(IOConnection.java:199)
03-24 08:47:57.329 32512-32593/com.toscl.st.myapplication W/System.err: Caused by: java.io.FileNotFoundException: http://172.20.3.5:3014/socket.io/1/
03-24 08:47:57.329 32512-32593/com.toscl.st.myapplication W/System.err:     at com.android.okhttp.internal.http.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:186)
03-24 08:47:57.329 32512-32593/com.toscl.st.myapplication W/System.err:     at io.socket.IOConnection.handshake(IOConnection.java:313)
03-24 08:47:57.329 32512-32593/com.toscl.st.myapplication W/System.err: 	... 2 more
03-24 08:47:57.329 32512-32593/com.toscl.st.myapplication I/io.socket: Cleanup

----

web(chatofpomelo)客户端正常使用，Android上 (androidchat)出现这个问题，无解，很久了。

**Comment by 10cl** [comment]
版本问题，新版本无法和Android-chat 同步，Android端 和 chatpomelo 都切换到三年前版本成功。

**Comment by cynron** [comment]
socket.io 1.x 相比于 0.9.x，修改了协议格式，而且没有做兼容

正常来说，当有重大更新的时候，至少应该有一个过渡版本，帮助大家做平滑升级，然后在下一个版本再删除，唉.........
