### ISSUE TITLE
hybridconnector的heartbeat设置为3，disconnectOnTimeout设置为true，client端正常连接，并没有断线，server端会出现client %j heartbeat timeout的问题

### ISSUE THREAD

**Issue by linsainan** [NetEase/pomelo#955]
hybridconnector的heartbeat设置为3，disconnectOnTimeout设置为true，client端正常连接，并没有断线，server端会出现client 2 heartbeat timeout的情况。client 2 heartbeat timeout中并不固定是2，有时候是3有时候是6.不同id的socket都有出现这个情况。
出现此问题会导致server端一直不停的断开client端的正常socket连接。导致pomelo不能正常工作。

**Comment by linsainan** [comment]
哈哈。好尴尬，是自己代码的问题。问题已经解决。

**Comment by acter** [comment]
hi,boy! 我也遇这个问题了，是咋回事呢？

**Comment by NextZeus** [comment]
@linsainan 分享一下你的解决方法呗，别这么吝啬。

**Comment by zhangqi0927** [comment]
@linsainan 不上代码说毛线
