### ISSUE TITLE
 i want to add two users(connected from different front end servers) in one channel, how can i do this?

### ISSUE THREAD

**Issue by sushiljainam** [NetEase/pomelo#959]
We are developing a multiplayer game, with multiple connector servers and multiple logic(backend) servers.
If two users connected from different connectors want to join same game (one channel), 
How can it be managed?

I suppose, i can not access channel created on one connector, on another connector OR any backend server. Am i wrong?

And i have tried using globalchannel-plugin, but for existing codebase it is not right choice for us.

**Comment by dubanflorin** [comment]
You could try to route the requests for the players in the same game to the same server where the common channel resides. I did this in the beginning of my project but as soon as I discovered the globalchannel plugin I switched to it.

**Comment by sushiljainam** [comment]
yeah,
I got it now, 
> I can create channel at backend server and route such request to that server.

Thanks.
