### ISSUE TITLE
question about using adminConsole

### ISSUE THREAD

**Issue by qiankanglai** [NetEase/pomelo#96]
Hi, I encountered an exception when trying adminConsole: 

[2013-02-17 20:16:57.962] [ERROR] /usr/local/share/npm/lib/node_modules/pomelo/node_modules/pomelo-admin/lib/consoleService.js - unknown module: "onlineUser".

It seems pomelo-admin-web tries to request onlineUser from pomelo.
(in pomelo/node_modules/, there are pomelo-monitor & pomelo-admin, etc.)

However, I've added

  app.enable('systemMonitor');

in the app.js. What else should I do?

**Comment by betapcode** [comment]
i added module "onlineUser" ok, but when i see in admin tool web , tab 'Online User" not display username columns, who can help me please ? thanks |
