### ISSUE TITLE
特性需求：管理模块加入非周期的主动推送方式（万一你们看了呢）

### ISSUE THREAD

**Issue by SteveCruise** [NetEase/pomelo#974]
master的功能不该只有监控，而是监控和管理。
如给特定用户充值游戏币，推送停服通知等等，需要GM操作后即时见效。现有的周期性接收推送设计不能满足此类需求。

**Comment by jiangzhuo** [comment]
这是在0.1.x就支持的功能 五年前就有了，到现在一直保留，如果有问题要顾问或者外包开发可以找我

**Comment by ChrisPei** [comment]
一直都有管理功能啊。。。

**Comment by SteveCruise** [comment]
谢谢，发现机制上支持，通过在clientHandler中直接操作数据库，可以给玩家立即充值
