### ISSUE TITLE
请问pomelo可以监听http请求吗

### ISSUE THREAD

**Issue by wangdao2017** [NetEase/pomelo#985]
pomelo可以监听http请求吗，然后通知相应的服务器去做些事情

**Comment by whtiehack** [comment]
可以,你可以通过组件实现

**Comment by yunmin97** [comment]
用这个插件 pomelo-http-plugin，怎么和其他的服务器交互？没办法发起rpc调用啊！rpc调用得有session才行啊！！求指教
